### PR TITLE
[SFlowTest] Dynamic Agent-id and ifindex issue resolved

### PR DESCRIPTION
**Pull request by vivekreddynv**
Signed-off-by: Vivek Reddy Karri <vkarri@nvidia.com>

### Description of PR

Summary:
Fixes # (issue)
This PR addresses the following issues:

1) Currently, hsflowd trasmits index in the SFlow UDP datagram, but the test expects ifindex. Considering, index as a valid option, the test has to be fixed. Modified test to collect index info and then made the ptftests/sflow_test.py to verify on index in the datagram received. More Info on [#3234 ](https://github.com/Azure/sonic-mgmt/issues/3234)

2) If the Agent-id is left to default, the hsflowd assigns docker0 (When nothing is assigned, it's upto to the hsflowd to choose any ip) as the agent-id, but the test was hard coded to verify for mgmt-ip as the agent-id. As a fix, used a fixture in the test to set Loopback0 address as agent-id before running these tests.  More Info on [#3233 ](https://github.com/Azure/sonic-mgmt/issues/3233)
 
3) Point 23 in [HLD:Test_Plan](https://github.com/Azure/SONiC/blob/master/doc/sflow/sflow_hld.md#11-unit-test-cases) suggests a test case for warm-reboot. Essentially, the test programs a valid configuration for sflow and then performs a warm-reboot and then to check if the sflow is working as expected. This test case is not intend to test sFlow working during warmboot and that warmboot traffic is not affected but rather making sure than when sFlow is configured and activated warmboot can be executed and completed with no issue. [#3236 ](https://github.com/Azure/sonic-mgmt/issues/3236)

4) Minor refactoring of TestSflowPolling & TestAgentId Classes by running the fixture once per class instead of running it for every method.

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

#### What is the motivation for this PR?
Community Test is failing

#### How did you do it?
Modified the test

#### How did you verify/test it?
Ran the Community Test

### CODE REVIEW

**Comment by dgsudharsan** [comment]
@prsunny @chitra-raghavan Can you please review?

**Review by prsunny — APPROVED** [review]
lgtm, wait for other reviewers before merge

**Comment by liat-grozovik** [comment]
@vivekreddynv could you please share more information on the PR description on what are the changes and how they are intend to fix?
i also see you modified warmboot test. can you please explain the motivation and what is this test is expected to test?

**Comment by vivekreddynv** [comment]
> @vivekreddynv could you please share more information on the PR description on what are the changes and how they are intend to fix?
> i also see you modified warmboot test. can you please explain the motivation and what is this test is expected to test?

@liat-grozovik Updated the Description

**Review by liat-grozovik — APPROVED** [review]

**Pull request merged**
