### PR TITLE
Removed test cases already converted to pytest.

### PR DESCRIPTION
**Pull request by yvolynets-mlnx**
Signed-off-by: Yuriy Volynets <yuriyv@mellanox.com>

### Description of PR

Summary: Removed ansible test cases which are already converted to pytest:
acltb.yml
bgp_speaker.yml
dhcp_relay.yml
lldp.yml
snmp/cpu.yml
snmp/interfaces.yml
snmp/lldp.yml
snmp/pfc_counters.yml
snmp/queues.yml

Fixes # (issue)

### Type of change

- [] Bug fix
- [] Testbed and Framework(new/improvement)
- [+] Test case(new/improvement)

**How to run test cases:**
py.test acl -k \"acl and not egress and not reboot and not port_toggle\" --testbed DEVICE-TOPO --inventory ../ansible/inventory --testbed_file ../ansible/testbed.csv --host-pattern=DEVICE-TOPO --module-path=../ansible/library -v

py.test --pdb --inventory ../ansible/inventory --host-pattern DEVICE --module-path ../ansible/library/ --testbed DEVICE-TOPO --testbed_file ../ansible/testbed.csv --show-capture=no --log-cli-level info -ra -vvvvv test_bgp_speaker.py

py.test --pdb --inventory ../ansible/inventory --host-pattern DEVICE --module-path ../ansible/library/ --testbed DEVICE-TOPO --testbed_file ../ansible/testbed.csv --show-capture=no --log-cli-level info -ra -vvvvv test_dhcp_relay.py

py.test --pdb --inventory ../ansible/inventory --host-pattern DEVICE --module-path ../ansible/library/ --testbed DEVICE-TOPO --testbed_file ../ansible/testbed.csv --show-capture=no --log-cli-level info -ra -vvvvv test_lldp.py

py.test --pdb --inventory ../ansible/inventory --host-pattern DEVICE --module-path ../ansible/library/ --testbed DEVICE-TOPO --testbed_file ../ansible/testbed.csv --show-capture=no --log-cli-level info -ra -vvvvv snmp/test_snmp_cpu.py

For rest SNMP just specify appropriate file path

### CODE REVIEW

**Comment by msosyak** [comment]
What is the reason to remove these wrappers???

**Comment by yvolynets-mlnx** [comment]
> 
> 
> What is the reason to remove these wrappers???

As those tests are just calling pytest based test cases, there is no reason to keep pytest test cases and reference to them.
General idea is to move from ansible to pytest in the future.

**Comment by akokhan** [comment]
@yvolynets-mlnx how about backward compatibility? how about other vendors that uses this for the regression? Also, please provide the reference to the HLD or other documentation that describes new steps to run TCs.

**Comment by yvolynets-mlnx** [comment]
> 
> 
> @yvolynets-mlnx how about backward compatibility? how about other vendors that uses this for the regression? Also, please provide the reference to the HLD or other documentation that describes new steps to run TCs.

Updated description

**Comment by akokhan** [comment]
> > @yvolynets-mlnx how about backward compatibility? how about other vendors that uses this for the regression? Also, please provide the reference to the HLD or other documentation that describes new steps to run TCs.
> 
> Updated description

Still, these changes make code inconsistent with https://github.com/Azure/sonic-mgmt/blob/master/ansible/doc/README.testbed.Example.md

This breaks backward compatibility without a benefit.

**Comment by yvolynets-mlnx** [comment]
Ansible wrappers should not be removed.

**Pull request closed without merging**
