### PR TITLE
Log Analyzer improvements

### PR DESCRIPTION
**Pull request by AharonMalkin**
### Description of PR
The current UI of Log Analyzer reports in allure is messy, isn’t organized and has bad readability. 
The current format consists of 2 inner dictionaries inside the main dictionary, which prints the error messages “as is” without newlines.
The improvement includes a new method for LogAnalyzer class, which represents the dictionary as a readable string, and prints only the relevant data to the user.

### Type of change

- [ ] Bug fix
- [x] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [x] 202012
- [x] 202111

#### What is the motivation for this PR?
Creating a readable format and removing unnecessary information, while keeping the essential details needed to analyze the errors.

#### How did you do it?
I created a new method, which prints the total amount of matches, checks the lists of match messages, and prints them as a string if they aren't empty.

#### How did you verify/test it?
I ran full regression on community tests.

#### Any platform specific information?
Relevant for all platforms.

### CODE REVIEW

**Comment by Blueve** [comment]
Do you have example output to show the before/after difference?

**Comment by AharonMalkin** [comment]
> Do you have example output to show the before/after difference?
@Blueve 
Yes, attached.
LA example

**Review by roysr-nv — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@AharonMalkin  great improvement. thank you.

**Pull request merged**
