### PR TITLE
[dhcp_relay] DHCPv6 automatic test

### PR DESCRIPTION
**Pull request by shlomibitton**
### Description of PR

Summary:
DHCPv6 infrastructure and automatic test.

### Type of change

- [ ] Bug fix
- [x] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

#### What is the motivation for this PR?
Add DHCPv6 automatic test infrastructure and PTF test.

#### How did you do it?
Enhance the minigraph_facts.py and minigraph_dpg.j2 to support DHCPv6 instances.
Add DHCPv6 servers to lab.yml file.
This will deploy on a DUT DHCPv6 servers on regression run.
Develop a test with 3 test cases:
- test_dhcp_relay_default
- test_dhcp_relay_after_link_flap
- test_dhcp_relay_start_with_uplinks_down

Develop a PTF runner test to simulate the traffic according to the test case from sonic-mgmt.

#### How did you verify/test it?
- Use testbed-cli.sh to generate and deploy a minigraph with DHCPv6 instances on a switch.
- Run the test.
- This test depends on PR: https://github.com/Azure/sonic-buildimage/pull/7772

#### Supported testbed topology if it's a new test case?
T0

### CODE REVIEW

**Review by wangxin — APPROVED** [review]
Please do not merge this PR until https://github.com/Azure/sonic-buildimage/pull/7772 is merged.

**Comment by shlomibitton** [comment]
test_dhcp_relay_default is failing since PR https://github.com/Azure/sonic-buildimage/pull/7772 is not merged yet.

**Comment by lguohan** [comment]
build image pr has been merged, please retest when the image is built.

**Comment by shlomibitton** [comment]
@lguohan Test passed with built image including the buildimage PR.

**Comment by shlomibitton** [comment]
@wangxin can we proceed with the merge?
Azure/sonic-buildimage#7772 is merged and test is passed.

**Comment by anshuv-mfst** [comment]
Hi @wangxin -  could you please review and approve asap, this is needed in 202106 release

**Review by wangxin — APPROVED** [review]

**Pull request merged**
