### PR TITLE
[system-health] Disable logger analyzer for test_system_health_config

### PR DESCRIPTION
**Pull request by Junchao-Mellanox**
Change-Id: I47ded16d59e71c4bda03da2447b31a2a444cab28

### Description of PR

Summary:
Disable logger analyzer for test_system_health_config test case

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911

#### What is the motivation for this PR?

In case test_system_health_config, it mocks fan absence which removes sysfs node. There is chance that thermalctld would access the sysfs node while test case is removing it. In order to avoid such conflict, the log analyzer should be disabled for this test case like other cases in test_system_health.py

#### How did you do it?

Disable logger analyzer for test_system_health_config

### CODE REVIEW

**Review by keboliu — DISMISSED** [review]

**Comment by Junchao-Mellanox** [comment]
Hi @sujinmkang , could you please review and sign-off?

**Comment by ZhaohuiS** [comment]
@Junchao-Mellanox could you please have a look at a comment left by me? I am wondering why do you set marker_prefix to "turn_on_off_psu_and_check_psustatus" in test_system_health.py.

**Comment by Junchao-Mellanox** [comment]
> @Junchao-Mellanox could you please have a look at a comment left by me? I am wondering why do you set marker_prefix to "turn_on_off_psu_and_check_psustatus" in test_system_health.py.

Fixed.

**Comment by ZhaohuiS** [comment]
@Junchao-Mellanox I have updated this test script days ago in #5113. It seems yours is not the latest code, could you please update it? Otherwise you will have conflicts.

**Comment by Junchao-Mellanox** [comment]
I don't see conflict in this PR...

**Review by wangxin — APPROVED** [review]

**Comment by wangxin** [comment]
> 

Changes in this PR updated different lines of the script comparing with #5113. That's why there is no conflict. The code changes LGTM.

**Review by liat-grozovik — APPROVED** [review]

**Pull request merged**
