### PR TITLE
Add route flow counter related test cases

### PR DESCRIPTION
**Pull request by Junchao-Mellanox**
### Description of PR

Summary:
Added test cases for route flow counter feature. HLD: https://github.com/Azure/SONiC/pull/908

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 201911

#### What is the motivation for this PR?

Add route flow counter related test cases

#### How did you do it?

1. Add new test case file test_route_flow_counter.py to covers basic function of this feature
2. Add check in test_vnet_vxlan.py to cover VNET route
3. Add check in test_bgp_speaker.py to cover BGP route
4. Add check in test_static_route.py to cover static route

#### How did you verify/test it?

Run the test cases

#### Any platform specific information?

N/A

#### Supported testbed topology if it's a new test case?

N/A

### CODE REVIEW

**Comment by Junchao-Mellanox** [comment]
Hi @keboliu and @roysr-nv , could you please sign-off as there is no change compare to previous approved one?

**Review by keboliu — APPROVED** [review]

**Review by roysr-nv — DISMISSED** [review]

**Review by keboliu — APPROVED** [review]

**Review by roysr-nv — APPROVED** [review]

**Comment by Junchao-Mellanox** [comment]
Hi @liat-grozovik , could you please help merge this ?

**Review by liat-grozovik — APPROVED** [review]

**Comment by zhangyanzhao** [comment]
@Junchao-Mellanox  can you please add this code PR into https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2FSONiC%2Fpull%2F908&data=04%7C01%7Cyuvalbo%40nvidia.com%7C98a255c5d57247174e1d08d9e73732de%7C43083d15727340c1b7db39efd9ccc17a%7C0%7C0%7C637795046558169261%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=aW30J6Mu2JB3Sgekw1enmihdBH1iGLTnkk86EOVMcsg%3D&reserved=0 for tracking? Thanks.

**Comment by Junchao-Mellanox** [comment]
> @Junchao-Mellanox can you please add this code PR into [sonic-net/SONiC#908](https://github.com/sonic-net/SONiC/pull/908) for tracking? Thanks.

Done

**Comment by ZhaohuiS** [comment]
@Junchao-Mellanox Does the script test_route_flow_counter support T1? Is the pytestmark same with test_static_router.py? Or it only supports mellanox?
Whatever same or not, could you please add pytestmark for this script? Otherwise it will skipped in our nightly test.
`testcase route/test_route_flow_counter.py::TestRouteCounter::test_max_match_count is skipped when no topology marker is given
`
```
pytestmark = [
    pytest.mark.topology('t0'),
    pytest.mark.device_type('vs')
]
```

**Pull request merged**
