### PR TITLE
[kvmtest]: Add dual ToR ARP tests to KVM test suite

### PR DESCRIPTION
**Pull request by theasianpianist**
Signed-off-by: Lawrence Lee <lawlee@microsoft.com>

### Description of PR

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### CODE REVIEW

**Comment by lguohan** [comment]
i have fixed the pr test issue, can you resolve the conflict?

**Comment by lguohan** [comment]
looks like the test failed.

**Comment by yxieca** [comment]
@theasianpianist I restarted the test. can you check if the test fail again and address issues accordingly?

**Review by yxieca — APPROVED** [review]

**Pull request merged**
