### PR TITLE
[sku_sensors]: Updating sensor values for cisco-8102 platform

### PR DESCRIPTION
**Pull request by vperumal**
### Description of PR
Updating sensor values for Cisco 8102 platform

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911

#### What is the motivation for this PR?
Updating sensor values for Cisco 8102 platforms

#### How did you verify/test it?
Verified that test_sensor.py passed for Cisco 8102 platform

### CODE REVIEW

**Review by wangxin — APPROVED** [review]

**Comment by wangxin** [comment]
This change was merged before 202305 was branched out. No need to back port to 202305.

**Comment by kevinskwang** [comment]
@vperumal  need another PR to address the conflicts on 202205.

**Comment by vperumal** [comment]
> @vperumal need another PR to address the conflicts on 202205.

Hi @kevinskwang , this change was merged before 202205 was branched out and it is already present in it. Can you please check on your end too.

**Comment by wangxin** [comment]
Let's remove the labels requesting cherry-pick.

**Pull request merged**
