### PR TITLE
[Mellanox SimX] upstream scripts for SimX virtual testbed management

### PR DESCRIPTION
**Pull request by mykolaf**
Signed-off-by: Mykola Faryma <mykolaf@mellanox.com>

### Description of PR

Summary:
Upstream the scripts used for SimX virtual testbed management

This allows us to run t1 topology over ptf32(using only ptf docker and no VMs)
 

It does several things:
 - Configure the routes for t1 topology
 - Start a LLDP script on ptf docker that emulates the lldp traffic from the VMs

Fixes # (issue)

### Type of change

- [ ] Bug fix
- [X] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### CODE REVIEW

**Comment by lguohan** [comment]
it is hard to understand why we need the scripts for simx virtual testbed. Please have a description on what problem you are trying to solve.

**Comment by mykolaf** [comment]
@lguohan These scripts solved a problem of fast bringing up of a a testbed on limited resources. 
We could make the same topology as the kvm testbed(not done yet, need time), but this is what we're using now.

**Comment by mykolaf** [comment]
@lguohan the SimX runs on CentOS, so deploying the same kvm virtual testbed is not possible without updating the scripts. To integrate it with kvm virtual testbed means more work

**Comment by liat-grozovik** [comment]
Following earlier discussion about this approach we agreed that this can be used as initial step in order to be able to push simx on top of Mellanox ASICs and later on we can extend it to work with the EOS VMs topology. If there are no additional open issues, i would appreciate if this can be merged to be used by anyone who would like to.

**Comment by liat-grozovik** [comment]
@maggiemsft @lguohan  can you please refer to the comment and let us know if something else is missing?

**Pull request closed without merging**
