### PR TITLE
[Sub-ports] Added test case which validates that packets are routed between sub-ports

### PR DESCRIPTION
**Pull request by OleksandrKozodoi**
Signed-off-by: Oleksandr Kozodoi <oleksandrx.kozodoi@intel.com>

### Description of PR

Summary:

- Added new sub-ports tests: [test_routing_between_sub_ports](https://github.com/OleksandrKozodoi/sonic-mgmt/blob/32128a30c0b2728689a1350b354e59b783de006b/tests/sub_port_interfaces/test_sub_port_interfaces.py#L233-L268)
- Added fixture for setup route between port and port in namespace on the PTF: [apply_route_config](https://github.com/Azure/sonic-mgmt/compare/master...OleksandrKozodoi:add_routing_sub_ports_test_cases?expand=1#diff-c1a46395dc2a8ee7f7114c4a63ebc73394fbc59df9ea692c17350bc55b3ac090R166-R227)
- Added new helpers methods
- Changed approach to removing ports from the PTF
- Updated Test Plan
#### Note:
Tests verifies two cases of routing between sub-ports:
1) Routing between sub-ports on the same port
2) Routing between sub-ports on the different ports

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

#### What is the motivation for this PR?
Coverage of sub-ports feature by test cases to improve the quality of SONiC.
#### How did you do it?
Added new test cases to PyTest.
Implementation is based on the [Sub-ports design spec](https://github.com/Azure/SONiC/blob/master/doc/subport/sonic-sub-port-intf-hld.md)
#### How did you verify/test it?
`py.test --testbed=testbed-t0 --inventory=../ansible/lab --testbed_file=../ansible/testbed.csv --host-pattern=testbed-t0 -- module-path=../ansible/library sub_port_interfaces`
#### Any platform specific information?
SONiC Software Version: SONiC.master.152-dirty-20210317.033059
Distribution: Debian 10.8
Kernel: 4.19.0-12-2-amd64
Build commit: 43d4d456
Build date: Wed Mar 17 14:05:52 UTC 2021
Platform: x86_64-accton_as9516_32d-r0
HwSKU: newport
ASIC: barefoot
#### Supported testbed topology if it's a new test case?
T0, T1

### CODE REVIEW

**Comment by OleksandrKozodoi** [comment]
@wangxin Could you please review?

**Comment by OleksandrKozodoi** [comment]
@wangxin @yxieca @lguohan Can you take a look? Thank you in advance.

**Comment by SavchukRomanLv** [comment]
Hi @wangxin @lguohan. I would appreciate if you take a look  at this PR. We do have more cases to cover, but it relies on your review comments. Thank you in advance!

**Review by wangxin — APPROVED** [review]
LGTM

**Comment by yxieca** [comment]
@neethajohn  can you also take a look?

**Pull request merged**
