### PR TITLE
[test_ntp] Increase NTP sync wait time

### PR DESCRIPTION
**Pull request by lolyu**
### Description of PR

Summary:
Fixes # (issue)

300s might be limited for DUT to sync with ptf, increased to 720s.

Signed-off-by: Longxiang Lyu <lolv@microsoft.com>

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

#### What is the motivation for this PR?
Test failed because DUT cannot sync with NTP server(`ptf`).

#### How did you do it?
Increase wait time for sync.

#### How did you verify/test it?
run testcase `ntp/test_ntp.py`.

#### Any platform specific information?
Arista 7260

### CODE REVIEW

**Comment by lguohan** [comment]
any idea why take so long? the dut ntp is trying to sync with ptf ntpd, they are on the same subnet, should be fast.

**Comment by lolyu** [comment]
> any idea why take so long? the dut ntp is trying to sync with ptf ntpd, they are on the same subnet, should be fast.

It seems that there is a significant time gap between the DUT and ptf:
```
$ ntpq -p
     remote           refid      st t when poll reach   delay   offset  jitter
==============================================================================
 10.64.247.17    LOCAL(0)         6 u   28   64    7    0.426  -392838 282.189
```

**Comment by lguohan** [comment]
> > any idea why take so long? the dut ntp is trying to sync with ptf ntpd, they are on the same subnet, should be fast.
> 
> It seems that there is a significant time gap between the DUT and ptf:
> 
> ```
> $ ntpq -p
>      remote           refid      st t when poll reach   delay   offset  jitter
> ==============================================================================
>  10.64.247.17    LOCAL(0)         6 u   28   64    7    0.426  -392838 282.189
> ```

if DUT does not do time jump, it will really hard for DUT to be in sync with ptf. I am not sure if increase to 480 is enough. @ying xie, should we first let DUT do a long jump?

**Comment by yxieca** [comment]
I think this test is setup ntp to do one long jump to sync. It is still weird that the sync takes so long. But from my observation, once it is synced with the server, the clock is set.

**Pull request merged**
