### PR TITLE
[Mellanox] Adjust test case due to support of PSU max fan speed

### PR DESCRIPTION
**Pull request by Junchao-Mellanox**
### Description of PR

Summary:
As we support getting max PSU fan speed in Mellanox platform API, we need make some adjustment to the existing test cases:

1. "show platform fan" no longer display PSU fan speed as percentage instead of RPM, need adjust the existing data mocker
2. Test case "test_set_psu_fan_speed" can directly verify the PSU fan speed now.

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

#### What is the motivation for this PR?

As we support getting max PSU fan speed in Mellanox platform API, we need make some adjustment to the existing test cases.

#### How did you do it?

1. "show platform fan" no longer display PSU fan speed as percentage instead of RPM, adjust the existing data mocker to expect the speed in percentage
2. Verify the PSU fan speed directly in test case "test_set_psu_fan_speed".

#### How did you verify/test it?

Manually run the related regression cases

#### Any platform specific information?

Mellanox platforms

#### Supported testbed topology if it's a new test case?

N/A

### CODE REVIEW

**Comment by Junchao-Mellanox** [comment]
Depends on https://github.com/Azure/sonic-buildimage/pull/5682

**Comment by wangxin** [comment]
retest this please

**Review by liat-grozovik — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@Junchao-Mellanox as the related PR is for master only, how do we expect the test to distinguish if psu max is supported or not ? unfortunately community wize there is no sonic-mgmt for 201911 and there is no easy way to differentiate.
please suggest how to overcome it before merge.

**Comment by Junchao-Mellanox** [comment]
@liat-grozovik I saw the "Request for 201911 branch" label in the related PR. See https://github.com/Azure/sonic-buildimage/pull/5682.

**Comment by keboliu** [comment]
retest vs please

**Comment by keboliu** [comment]
retest vsimage please

**Review by jleveque — APPROVED** [review]

**Pull request merged**
