### PR TITLE
[test_auto_techsupport] Implemented auto-techsupport test cases

### PR DESCRIPTION
**Pull request by ppikh**
Signed-off-by: Petro Pikh <petrop@nvidia.com>

### Description of PR
Implemented auto-techsupport test cases which will validate auto-techsupport feature

Summary: Implemented auto-techsupport test cases
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012

#### What is the motivation for this PR?
New tests added for new SONiC feature

#### How did you do it?
Implemented new tests(see code)

#### How did you verify/test it?
Executed new tests on latest master image

#### Supported testbed topology if it's a new test case?
any

### CODE REVIEW

**Review by roysr-nv — DISMISSED** [review]

**Comment by yxieca** [comment]
@ppikh this test has lots of "with allure..." blocks, if allure is not configured, what is the impact to this test?

**Comment by ppikh** [comment]
Hi,

It requires only allure lib installed(which is already part of sonic-mgmt docker.
If allure not installed(if run not from sonic-mgmt) - it will fail, but it’s not our case.
If user provide allure dir as test argument - then user will be able to see allure report, id not - the test will be executed without allure report.

Надіслано з iPhone

4 квіт. 2022 р. о 19:40 Ying Xie ***@***.***> пише:

﻿

@ppikh<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fppikh&data=04%7C01%7Cpetrop%40nvidia.com%7C656f4606a8464b174d0208da1659d698%7C43083d15727340c1b7db39efd9ccc17a%7C0%7C0%7C637846872357641172%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=8RBw%2FgEFW%2BtWTEHzPnOkStr%2FqmlK1hkF4LdNNPyTn4o%3D&reserved=0> this test has lots of "with allure..." blocks, if allure is not configured, what is the impact to this test?

**Comment by liat-grozovik** [comment]
@yxieca could you please help to review or assign someone to do so?

**Comment by yxieca** [comment]
@ppikh I suggest skip the test if the allure lib is not installed. Can you add this test case to the kvmtest.sh?

**Comment by ppikh** [comment]
> @ppikh I suggest skip the test if the allure lib is not installed. Can you add this test case to the kvmtest.sh?

I added logic which will skip test case in case when allure lib missed.

```
try:
    import allure
except ImportError:
    pytest.skip('Allure library not available. Skipping tests')
```

About kvmtests.sh - what exactly should be added to this file?

**Review by roysr-nv — APPROVED** [review]

**Comment by roysr-nv** [comment]
@yxieca - is there anything missing to approve this PR?

**Comment by yxieca** [comment]
> @yxieca - is there anything missing to approve this PR?

Can this test be executed on KVM switch? If so, please add this test to kvmtest.sh.

**Comment by liat-grozovik** [comment]
@yxieca can you please signoff?

**Comment by liat-grozovik** [comment]
This one is currently merged. still waiting for update from @ppikh regarding KVM.

**Review by liat-grozovik — APPROVED** [review]

**Pull request merged**
