### PR TITLE
Changes for testing Multi NPU platforms

### PR DESCRIPTION
**Pull request by arlakshm**
Signed-off-by: Arvindsrinivasan Lakshmi Narasimhan <arlakshm@microsoft.com>

### Description of PR

This PR has the changes to support testing for Multi NPU SONiC platforms
Changes done:
 - Add a new option to the bgp_fact module to get the bgp facts from multiple bgp dockers
 - Add an option "filename" in the config_facts to the pass the config_db.json file
 - changes to the SonicHost class to detect if the platform is single or multi NPU
 - changes to the sanity check and bgp_facts tests to test multi NPU platforms

Summary:
Fixes # (issue)

### Type of change

- [] Bug fix
- [] Testbed and Framework(new/improvement)
- [-] Test case(new/improvement)

#### How did you verify/test it?
Verifyied the basic sanity and test_bgp_fact tests run properly on single and multi NPU platforms.

### CODE REVIEW

**Comment by lguohan** [comment]
can you give command line how to use it when testing multi npu platforms?

**Comment by arlakshm** [comment]
@lguohan , the command is same as the one used currently for single NPU platforms, no new command-line arguments are added. I used the following command

py.test --inventory $INVT --host-pattern all --user admin --testbed $TB --testbed_file $TBFILE --junitxml=tr.xml test_bgp_fact.py

**Comment by yxieca** [comment]
Can you upload a test result output too?

**Comment by arlakshm** [comment]
@yxieca, Please find the logs  below
[test_bgp_facts_results.zip](https://github.com/Azure/sonic-mgmt/files/4278273/test_bgp_facts_results.zip)

**Comment by yxieca** [comment]
Why didn't I find keyword 'num_npu' in the xml output? Should I expect to see it?

**Pull request merged**
