### PR TITLE
Fix test_sub_port_interfaces

### PR DESCRIPTION
**Pull request by bingwang-ms**
### Description of PR

Summary:
Fixes # (issue)
This PR is to stabilize ```test_sub_port_interfaces``` on some platform.
There are two major reasons for test failure of ```test_sub_port_interfaces```
1. The ports selected for testing may be members of PortChannels. Adding such ports into other PortChannel or adding sub ports for such ports will cause exception.
2. The length of name of ```PortChannel + sub port tag``` might exceed 15, which is not allowed.

This PR addresses these 2 issues.

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

#### What is the motivation for this PR?
This PR is to stabilize ```test_sub_port_interfaces``` on some platform.

#### How did you do it?
1. Ensure interfaces selected for testing are not members of other portchannels.
2. Shorten the name of added portchannel.

#### How did you verify/test it?
Verified on SN4600 testbed. All cases passed.

#### Any platform specific information?
No.

#### Supported testbed topology if it's a new test case?
No.

### CODE REVIEW

**Comment by OleksandrKozodoi** [comment]
Hi, @bingwang-ms. I've added PR #3528 which fixes the issue of port selection. In my opinion, this approach is more flexible and allows to control the range of parent ports for different platforms. Could you please take a look?

**Comment by OleksandrKozodoi** [comment]
The change of PortChannels naming looks good to me.

**Review by wangxin — APPROVED** [review]

**Comment by bingwang-ms** [comment]
> Hi, @bingwang-ms. I've added PR #3528 which fixes the issue of port selection. In my opinion, this approach is more flexible and allows to control the range of parent ports for different platforms. Could you please take a look?

Sure. Will do. Maybe we can try to merge these 2 PRs into one.

**Comment by OleksandrKozodoi** [comment]
LGTM!

**Comment by bingwang-ms** [comment]
> LGTM!

Thanks

**Pull request merged**
