### PR TITLE
PFC tests with Snappi

### PR DESCRIPTION
**Pull request by ANISH-GOTTAPU**
### Description of PR
Migration of PFC tests from `abstract open traffic generator` to `snappi`

Summary:
Test case(new/improvement)

### Type of change
- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x ] Test case(new/improvement)

#### What is the motivation for this PR?
The motivation for this PR is to migrate the tests that are written with `abstract open traffic generator` to `snappi`

#### How did you do it?
Replaced the code where abstract is used to snappi

#### How did you verify/test it?
verified all the tests in sonic-mgmt using pytest with DUT and IXIA connections 
snappi version used for the development of tests `snappi[ixnetwork]==0.3.13`

### CODE REVIEW

**Comment by yxieca** [comment]
@baiwei0427  can you help review this change?

**Comment by yxieca** [comment]
@ANISH-GOTTAPU your change is causing KVM switch test to fail. can you look into it?

**Comment by ANISH-GOTTAPU** [comment]
@yxieca : Thanks for raising this, the PR needs supporting library `snappi`. 
I have added supporting PR for this  https://github.com/Azure/sonic-buildimage/pull/7292

**Comment by yxieca** [comment]
@ANISH-GOTTAPU can you solve the merge conflict?

**Comment by ANISH-GOTTAPU** [comment]
@yxieca : There was a discussion, @baiwei0427 is expecting to make more changes to the existing files. I shall wait for all the changes to go in and restart work on this PR.

**Comment by ANISH-GOTTAPU** [comment]
closing this PR as this will be addressed with #3641

**Pull request closed without merging**
