### PR TITLE
[everflow] enabled everflow per interfaces for barefoot asic

### PR DESCRIPTION
**Pull request by SavchukRomanLv**
### Description of PR

Summary:
Remove barefoot asic for everflow_per_interfaces TC

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012

#### What is the motivation for this PR?
Functional tested by everflow_per_interfaces TC has been added to Barefoot 
#### How did you do it?
Removed asic type from skip list
#### How did you verify/test it?
Run everflow_per_interfaces TC. TC passed

### CODE REVIEW

**Comment by SavchukRomanLv** [comment]
@wangxin @yxieca could you please take a look?

**Comment by SavchukRomanLv** [comment]
@wangxin @yxieca could you please take a look?

**Review by ZhaohuiS — APPROVED** [review]
LGTM

**Review by wangxin — APPROVED** [review]

**Pull request merged**
