### PR TITLE
Add a fixture to disable thermal policy

### PR DESCRIPTION
**Pull request by Junchao-Mellanox**
### Description of PR

Summary:
Add a fixture to disable thermal policy 

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

#### What is the motivation for this PR?

In some test cases, thermal policy would override the mock value and cause test case failure sporadicly. So need a way to disable thermal policy during that test. The idea is to make thermalctld load an invalid thermal policy file. This PR provides a handy fixture to achieve this function.

#### How did you do it?

1. add a fixture to disable thermal policy
2. use this fixture in test_show_platform_fanstatus_mocked and test_device_checker

#### How did you verify/test it?

Manually run test_platform_info and test_snmp_phy_entity

#### Any platform specific information?

N/A

#### Supported testbed topology if it's a new test case?

N/A

### CODE REVIEW

**Review by jleveque — APPROVED** [review]

**Comment by jleveque** [comment]
@Junchao-Mellanox: I'll run the test again.

**Comment by Junchao-Mellanox** [comment]
thanks!

**Pull request merged**
