### PR TITLE
[Arista] Fix 7050QX-32 sku sensors data

### PR DESCRIPTION
**Pull request by zzhiyuan**
### Description of PR
Fix Arista 7050QX-32 sku sensors data according to raw data from Sujin.

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### CODE REVIEW

**Comment by rlhui** [comment]
@jleveque , does this one need to be cherry-picked to 201911 branch or there's a separate PR for that?  Would be good to mention  it.  Thanks.

**Comment by jleveque** [comment]
@rlhui, gechiang: There is no 201911 branch of sonic-mgmt at this time.

I am removing the labels.

**Comment by rlhui** [comment]
@jleveque, thanks.  I didn't pay attention to the repo earlier.

**Comment by gechiang** [comment]
Hi Joe,
It was my mistake in creating it as I originally thought that this fix is applicable within the Sonic code and not paying attention that it is actually for the sonic-mgmt repo instead...  I was thinking that this fix is needed in 201911 and since there is no label for that request so I created it and used it.  Then I found out later that I should not have labeled this fix with the 201911 label so I quickly removed it but forgot to also delete the label itself from possible selection.  Sorry for causing the confusion and thank you for removing it from possible selections.

**Pull request merged**
