### PR TITLE
[vnet] Fix wr_arp test with vnet config

### PR DESCRIPTION
**Pull request by bingwang-ms**
Signed-off-by: bingwang <bingwang@microsoft.com>

### Description of PR

Summary:
This PR is to fix wr_arp test with vnet config.
Changes include
1. Add an Ansible library `vlan_facts` to retrieve running vlan config from DUT
2. Improve `test_wr_arp` to make it callable from `vnet_vxlan` test
3. Improve `ferret.py` to support ARP request with VLAN tag 

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 201911
- [x] 202012

#### What is the motivation for this PR?
This PR is to fix wr_arp test with vnet config.

#### How did you do it?
1. Add an Ansible library `vlan_facts` to retrieve running vlan config from DUT
2. Improve `test_wr_arp` to make it callable from `vnet_vxlan` test
3. Improve `ferret.py` to support ARP request with VLAN tag 

#### How did you verify/test it?
Verified on SN4600c testbed.
```
collected 4 items                                                                                                                                                                                     

vxlan/test_vnet_vxlan.py::test_vnet_vxlan[Disabled] PASSED                                                                                                                                      [ 25%]
vxlan/test_vnet_vxlan.py::test_vnet_vxlan[Enabled] PASSED                                                                                                                                       [ 50%]
vxlan/test_vnet_vxlan.py::test_vnet_vxlan[WR_ARP] PASSED                                                                                                                                        [ 75%]
vxlan/test_vnet_vxlan.py::test_vnet_vxlan[Cleanup] PASSED                                                                                                                                       [100%]
```
#### Any platform specific information?
`Mellanox` platform specific testcase.

### CODE REVIEW

**Comment by bingwang-ms** [comment]
@volodymyrsamotiy Can you please help take a look? Thanks

**Review by volodymyrsamotiy — DISMISSED** [review]

**Comment by liat-grozovik** [comment]
@bingwang-ms could you please check the new LGTM issue? i see new alert but checkers are all passing (strange?) 
if all good, lets signoff

**Comment by bingwang-ms** [comment]
> @bingwang-ms could you please check the new LGTM issue? i see new alert but checkers are all passing (strange?) if all good, lets signoff

@liat-grozovik  Addressed the LGTM issue, Thanks.

**Comment by liat-grozovik** [comment]
approved previously and now that all is passing and no new LGTM issues, signing off.

**Review by liat-grozovik — APPROVED** [review]

**Pull request merged**
