### PR TITLE
GCU tests add to kvm test

### PR DESCRIPTION
**Pull request by wen587**
### Description of PR

[Done]Wait for issue https://github.com/Azure/sonic-utilities/issues/2041 to be resolved to pass the bgpl test.
[Done]Wait for updated sonic-utilities including https://github.com/Azure/sonic-utilities/pull/2044 advanced in sonic-buildimage.
[Done]Remove cacl_test.
[Done]wait for 2092 sonic-util submodule update
Summary:
Add previous Generic Configer Updater tests into kvm test suite
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 201911

#### What is the motivation for this PR?
Move GCU test into kvm daily test
#### How did you do it?
Add GCU test case into kvmtest.sh
#### How did you verify/test it?
Run test of sonic-mgmt/tests/generic_config_updater/*.py on KVM

### CODE REVIEW

**Comment by wen587** [comment]
Wait for issue https://github.com/Azure/sonic-utilities/issues/2041 to be resolved to pass the bgpl test.

**Review by qiluo-msft — APPROVED** [review]

**Pull request merged**
