### PR TITLE
[test_traffic_shift] Changed path key due to FRR update

### PR DESCRIPTION
**Pull request by SavchukRomanLv**
Signed-off-by: Roman Savchuk <romanx.savchuk@intel.com>

### Description of PR

Summary:
After FRR update to FRR 7.5, output of vtysh -c "show bgp ipv4 json" does not contain key "aspath":
`
{
    "valid":true,
    "bestpath":true,
    "pathFrom":"external",
    "prefix":"100.1.0.32",
    "prefixLen":32,
    "network":"100.1.0.32\/32",
    "weight":0,
    "peerId":"10.0.0.63",
    "path":"64016",
    "origin":"IGP",
    "nexthops":[
      {
        "ip":"10.0.0.63",
        "afi":"ipv4",
        "used":true
      }
    ]
}
`

### Type of change

- [+] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

#### What is the motivation for this PR?
Test test_traffic_shift failed with error:
`no key "aspath"`
#### How did you do it?
Changed key from "aspath" to "path"
#### How did you verify/test it?
Run test test_traffic_shift; test passed

TC will be backward compatible with oldest versions of FRR as in output it has 2 keys with values:
`"aspath": "64600 65534 64799 65515", "path": "64600 65534 64799 65515"`

#### Any platform specific information?
SONiC Software Version: SONiC.master.91-dirty-20210111.022412
Distribution: Debian 10.7
Kernel: 4.19.0-9-2-amd64
Build date: Mon Jan 11 10:22:26 UTC 2021

Platform: x86_64-accton_wedge100bf_32x-r0
HwSKU: montara
ASIC: barefoot

### CODE REVIEW

**Comment by SavchukRomanLv** [comment]
@bingwang-ms can you please take a look?

**Comment by bingwang-ms** [comment]
> @bingwang-ms can you please take a look?

Thanks for the quick fix. 
You mentioned that
> TC will be backward compatible with oldest versions of FRR as in output it has 2 keys with values:
> ```"aspath": "64600 65534 64799 65515", "path": "64600 65534 64799 65515"```

Do you mean that both key (```path``` and ```aspath```) are available in FRR pre version 7.5?

**Comment by SavchukRomanLv** [comment]
@bingwang-ms yes. FRR version installed on latest 201911 (#203) is FRRouting 7.2.1-sonic (sonic). The output has both key (aspath and aspath) with same values.

**Comment by bingwang-ms** [comment]
> @bingwang-ms yes. FRR version installed on latest 201911 (#203) is FRRouting 7.2.1-sonic (sonic). The output has both key (aspath and aspath) with same values.

I see. Thanks

**Review by bingwang-ms — APPROVED** [review]

**Pull request merged**
