### PR TITLE
Fix missed template t0-56-po2vlan-leaf.j2 that used by topology t0-56-po2vlan

### PR DESCRIPTION
**Pull request by Pterosaur**
Signed-off-by: Ze Gan <ganze718@gmail.com>

### Description of PR

Summary:
Fixes # (issue)
Fix missed link file in templates
The file `ansible/roles/eos/templates/t0-56-po2vlan-leaf.j2 ` is needed by `ansible/vars/topo_t0-56-po2vlan.yml` 
### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### CODE REVIEW

**Comment by lguohan** [comment]
@qiluo-msft, can you check?

**Review by lguohan — APPROVED** [review]

**Review by qiluo-msft — APPROVED** [review]

**Pull request merged**
