### PR TITLE
[loganalyzer]add log patterns to the common ignore

### PR DESCRIPTION
**Pull request by StormLiangMS**
### Description of PR

There are PR tests failed due to loganalyzer, some of the error logs should be ignored by loganalyzer, in order to unblock the PR procedure, move those errors to common ignore for now, and filed an issue to have code owner to check later. https://github.com/Azure/sonic-mgmt/issues/5410

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012

### CODE REVIEW

**Comment by wangxin** [comment]
There are more error messages need to be temporarily ignored to unblock PR testing:
```
LogAnalyzerError: {'match_messages': {'/tmp/syslog.vlab-01.2022-03-28-04:46:34': ['Mar 28 04:46:24.861033 vlab-01 ERR sonic_yang: exceptionList:[]\n', "Mar 28 04:46:24.862357 vlab-01 ERR sonic_yang: Data Loading Failed:All Keys are not parsed in TACPLUS#012dict_keys(['global'])\n"]}, 'total': {'expected_match': 0, 'expected_missing_match': 0, 'match': 2}, 'match_files': {'/tmp/syslog.vlab-01.2022-03-28-04:46:34': {'expected_match': 0, 'match': 2}}, 'expect_messages': {'/tmp/syslog.vlab-01.2022-03-28-04:46:34': []}, 'unused_expected_regexp': []}
```

**Comment by wen587** [comment]
> There are more error messages need to be temporarily ignored to unblock PR testing:
> 
> ```
> LogAnalyzerError: {'match_messages': {'/tmp/syslog.vlab-01.2022-03-28-04:46:34': ['Mar 28 04:46:24.861033 vlab-01 ERR sonic_yang: exceptionList:[]\n', "Mar 28 04:46:24.862357 vlab-01 ERR sonic_yang: Data Loading Failed:All Keys are not parsed in TACPLUS#012dict_keys(['global'])\n"]}, 'total': {'expected_match': 0, 'expected_missing_match': 0, 'match': 2}, 'match_files': {'/tmp/syslog.vlab-01.2022-03-28-04:46:34': {'expected_match': 0, 'match': 2}}, 'expect_messages': {'/tmp/syslog.vlab-01.2022-03-28-04:46:34': []}, 'unused_expected_regexp': []}
> ```

GCU test's log analyzer failure will be fixed by this PR.
https://github.com/Azure/sonic-mgmt/pull/5391

**Comment by wen587** [comment]
Hi @wangxin @StormLiangMS , Seems the added regex are all GCU regex. Currently they are all covered in GCU ignored regex.
You can ignore the errors in  (Test kvmtest-t0-part2)  as the test have passed after the PR merge https://github.com/Azure/sonic-mgmt/pull/5411

**Comment by wangxin** [comment]
@wen587 Do you mean PR #5391? Let's try to get this PR passed to unblock PR testing asap.

**Comment by wen587** [comment]
Hi @wangxin , yes I mean PR #5391. It has been merged. So you can rebase the recent change. The t0-part2 error should be gone.

**Comment by wangxin** [comment]
The log analyzer fix was reverted. Let's abandon this one. I'll submit a new PR to include both the log analyzer fix and the changes of this PR.

**Pull request closed without merging**
