### PR TITLE
[LLDP] Fix lldp test to align with a bug fix

### PR DESCRIPTION
**Pull request by shlomibitton**
Signed-off-by: Shlomi Bitton <shlomibi@nvidia.com>

### Description of PR

Summary:
Fixes # (issue)

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

#### What is the motivation for this PR?
There is a bug fix on PR https://github.com/Azure/sonic-buildimage/pull/5698
The test fail after the change, this PR is to align the new change to the test case.

#### How did you do it?
Parse correct keys from mg_facts.

#### How did you verify/test it?
Run the test manually after applying the changes on sonic-buildimage and sonic-mgmt.

### CODE REVIEW

**Comment by shlomibitton** [comment]
Have a dependency on https://github.com/Azure/sonic-buildimage/pull/5698

**Review by keboliu — APPROVED** [review]

**Comment by wangxin** [comment]
Please hold on merging this PR until https://github.com/Azure/sonic-buildimage/pull/5698 is merged and backported to 201911 branch.

**Comment by yxieca** [comment]
retest vsimage please

**Comment by shlomibitton** [comment]
@yxieca This PR will fail the vsimage build unless https://github.com/Azure/sonic-buildimage/pull/5698 is merged.
These two PR's are dependent on each other, the vsimage is failing because the test for LLDP neighbour is adapted to the new change, which is not merged yet.

**Comment by wangxin** [comment]
@shlomibitton @yxieca I have created a PR to temporarily disable LLDP in KVM testing to workaround this mutually dependent issue: https://github.com/Azure/sonic-mgmt/pull/2451

**Comment by wangxin** [comment]
retest this please

**Review by wangxin — APPROVED** [review]

**Pull request merged**
