### PR TITLE
[platform api] Fix argument mismatch in platform API test

### PR DESCRIPTION
**Pull request by Junchao-Mellanox**
### Description of PR

Summary:
Fix argument mismatch in platform API test

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

#### What is the motivation for this PR?

Fix argument mismatch in platform API test

#### How did you do it?

Add missed argument to the function argument list.

#### How did you verify/test it?

Manual test

#### Any platform specific information?

N/A

#### Supported testbed topology if it's a new test case?

N/A

### CODE REVIEW

**Comment by Junchao-Mellanox** [comment]
retest vsimage please

**Comment by Junchao-Mellanox** [comment]
retest vsimage please

**Review by yxieca — APPROVED** [review]

**Comment by jleveque** [comment]
@Junchao-Mellanox: The PR title and description don't seem to match the actual changes in the PR. I added support for is_replaceable and get_position_in_parent test for psu_fan, fan_drawer_fan and module recently. It appears this is a bug fix instead. Can you please update the title and description?

**Comment by Junchao-Mellanox** [comment]
> @Junchao-Mellanox: The PR title and description don't seem to match the actual changes in the PR. I added support for is_replaceable and get_position_in_parent test for psu_fan, fan_drawer_fan and module recently. It appears this is a bug fix instead. Can you please update the title and description?

Sure.

**Review by jleveque — APPROVED** [review]

**Pull request merged**
