### PR TITLE
[testcase]MACsec basic test

### PR DESCRIPTION
**Pull request by Pterosaur**
<!--
Please make sure you've read and understood our contributing guidelines;
https://github.com/Azure/SONiC/blob/gh-pages/CONTRIBUTING.md

Please provide following information to help code review process a bit easier:
-->
### Description of PR
<!--
- Please include a summary of the change and which issue is fixed.
- Please also include relevant motivation and context. Where should reviewer start? background context?
- List any dependencies that are required for this change.
-->

Summary:
Fixes # (issue)

Need the PR: https://github.com/Azure/sonic-buildimage/pull/8554

### Type of change

<!--
- Fill x for your type of change.
- e.g.
- [x] Bug fix
-->

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Approach
#### What is the motivation for this PR?
This PR includes the basic test, control plane and data plane, for MACsec.

#### How did you do it?
- Control plane
1. Check the control plane processes, wpa_supplicant, can running 
2. Check the related entries in APP_DB
3. To virtual switch, Check the mka session by iproute2

- Data Plane
1. Check the traffic from down link to up link
2. Check the traffic from a neighbor device to others

#### How did you verify/test it?

Build testbed of SONiC neighbor devices
Please refer this document https://github.com/Azure/sonic-mgmt/blob/master/docs/testbed/README.testbed.VsSetup.md to 1setup your environment. the neighbor devices should be SONiC with the **latest image** and the vm_type should choose `vsonic`
```
./testbed-cli.sh -m veos_vtb -n 4 -k vsonic start-vms server_1 password.txt
./testbed-cli.sh -t vtestbed.csv -m veos_vtb -k vsonic add-topo vms-kvm-t0 password.txt
./testbed-cli.sh -t vtestbed.csv -m veos_vtb deploy-mg vms-kvm-t0 veos_vtb password.txt
```
Verify health
```
./run_tests.sh -u -n vms-kvm-t0 -d vlab-01 -c test_nbr_health.py -f vtestbed.csv -i veos_vtb -e "--neighbor_type=sonic --skip_sanity --disable_loganalyzer"
```
Run MACsec Test
```
./run_tests.sh -u -n vms-kvm-t0 -d vlab-01 -c macsec/test_macsec.py -f vtestbed.csv -i veos_vtb -e "--neighbor_type=sonic --skip_sanity --disable_loganalyzer"
```

You should get
```
=== Running tests in groups ===                                                                                                                                                                                                                                                
/usr/local/lib/python2.7/dist-packages/ansible/parsing/vault/__init__.py:44: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.               
  from cryptography.exceptions import InvalidSignature                                                                                                                                                                                                                         
============================================================================================= test session starts ==============================================================================================                                                               
platform linux2 -- Python 2.7.17, pytest-4.6.5, py-1.11.0, pluggy-0.13.1 -- /usr/bin/python                                                                                                                                                                                    
cachedir: .pytest_cache                                                                                                                                                                                                                                                        
metadata: {'Python': '2.7.17', 'Platform': 'Linux-5.4.0-37-generic-x86_64-with-Ubuntu-18.04-bionic', 'Packages': {'py': '1.11.0', 'pytest': '4.6.5', 'pluggy': '0.13.1'}, 'Plugins': {u'repeat': u'0.9.1', u'ordering': u'0.6', u'ansible': u'2.2.2', u'xdist': u'1.28.0', u'al
lure-pytest': u'2.8.22', u'html': u'1.22.1', u'forked': u'1.3.0', u'metadata': u'1.11.0'}}                                                                                                                                                                                     
ansible: 2.8.12                                                                                                                                                                                                                                                                
rootdir: /data/sonic-mgmt_sonic_vm_topology/tests, inifile: pytest.ini                                                                                                                                                                                                         
plugins: forked-1.3.0, xdist-1.28.0, repeat-0.9.1, metadata-1.11.0, html-1.22.1, allure-pytest-2.8.22, ordering-0.6, ansible-2.2.2                                                                                                                                             
collecting ... ['conf-name', 'group-name', 'topo', 'ptf_image_name', 'ptf', 'ptf_ip', 'ptf_ipv6', 'server', 'vm_base', 'dut', 'inv_name', 'auto_recover', 'comment']                                                                                                           
Finished testbed info generating.                                                                                                                                                                                                                                              
/usr/local/lib/python2.7/dist-packages/ansible/parsing/vault/__init__.py:44: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.               
  from cryptography.exceptions import InvalidSignature                                                                                                                                                                                                                         
collecting 0 items                                                                                                                                                                                             ['conf-name', 'group-name', 'topo', 'ptf_image_name', 'ptf', 'pt
f_ip', 'ptf_ipv6', 'server', 'vm_base', 'dut', 'inv_name', 'auto_recover', 'comment']                                                                                                                                                                                          
Finished testbed info generating.                                                                                                                                                                                                                                              
collected 40 items                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                               
macsec/test_macsec.py::TestControlPlane::test_wpa_supplicant_processes[GCM-AES-128-security-true] PASSED                                                                                                 [  2%]                                                                
macsec/test_macsec.py::TestControlPlane::test_appl_db[security-GCM-AES-128-true] PASSED                                                                                                                  [  5%]                                                                
macsec/test_macsec.py::TestControlPlane::test_mka_session[security-GCM-AES-128-true] PASSED                                                                                                              [  7%]                                                                
macsec/test_macsec.py::TestDataPlane::test_server_to_neighbor[GCM-AES-128-security-true] PASSED                                                                                                          [ 10%]                                                                
macsec/test_macsec.py::TestDataPlane::test_neighbor_to_neighbor[GCM-AES-128-security-true] PASSED                                                                                                        [ 12%]                                                                
macsec/test_macsec.py::TestControlPlane::test_wpa_supplicant_processes[GCM-AES-128-security-false] PASSED                                                                                                [ 15%]                                                                
macsec/test_macsec.py::TestControlPlane::test_appl_db[security-GCM-AES-128-false] PASSED                                                                                                                 [ 17%]                                                                
macsec/test_macsec.py::TestControlPlane::test_mka_session[security-GCM-AES-128-false] PASSED                                                                                                             [ 20%]                                                                
macsec/test_macsec.py::TestDataPlane::test_server_to_neighbor[GCM-AES-128-security-false] PASSED                                                                                                         [ 22%]                                                                
macsec/test_macsec.py::TestDataPlane::test_neighbor_to_neighbor[GCM-AES-128-security-false] PASSED                                                                                                       [ 25%]                                                                
macsec/test_macsec.py::TestControlPlane::test_wpa_supplicant_processes[GCM-AES-256-security-false] PASSED                                                                                                [ 27%]                                                                
macsec/test_macsec.py::TestControlPlane::test_appl_db[security-GCM-AES-256-false] PASSED                                                                                                                 [ 30%]                                                                
macsec/test_macsec.py::TestControlPlane::test_mka_session[security-GCM-AES-256-false] PASSED                                                                                                             [ 32%]                                                                
macsec/test_macsec.py::TestDataPlane::test_server_to_neighbor[GCM-AES-256-security-false] PASSED                                                                                                         [ 35%]                                                                
macsec/test_macsec.py::TestDataPlane::test_neighbor_to_neighbor[GCM-AES-256-security-false] PASSED                                                                                                       [ 37%]                                                                
macsec/test_macsec.py::TestControlPlane::test_wpa_supplicant_processes[GCM-AES-256-security-true] PASSED                                                                                                 [ 40%]                                                                
macsec/test_macsec.py::TestControlPlane::test_appl_db[security-GCM-AES-256-true] PASSED                                                                                                                  [ 42%]                                                                
macsec/test_macsec.py::TestControlPlane::test_mka_session[security-GCM-AES-256-true] PASSED                                                                                                              [ 45%]                                                                
macsec/test_macsec.py::TestDataPlane::test_server_to_neighbor[GCM-AES-256-security-true] PASSED                                                                                                          [ 47%]                                                                
macsec/test_macsec.py::TestDataPlane::test_neighbor_to_neighbor[GCM-AES-256-security-true] PASSED                                                                                                        [ 50%]                                                                
macsec/test_macsec.py::TestControlPlane::test_wpa_supplicant_processes[GCM-AES-XPN-128-security-false] PASSED                                                                                            [ 52%]                                                                
macsec/test_macsec.py::TestControlPlane::test_appl_db[security-GCM-AES-XPN-128-false] PASSED                                                                                                             [ 55%]                                                                
macsec/test_macsec.py::TestControlPlane::test_mka_session[security-GCM-AES-XPN-128-false] PASSED                                                                                                         [ 57%]                                                                
macsec/test_macsec.py::TestDataPlane::test_server_to_neighbor[GCM-AES-XPN-128-security-false] PASSED                                                                                                     [ 60%]                                                                
macsec/test_macsec.py::TestDataPlane::test_neighbor_to_neighbor[GCM-AES-XPN-128-security-false] PASSED                                                                                                   [ 62%]                                                                
macsec/test_macsec.py::TestControlPlane::test_wpa_supplicant_processes[GCM-AES-XPN-128-security-true] PASSED                                                                                             [ 65%]                                                                
macsec/test_macsec.py::TestControlPlane::test_appl_db[security-GCM-AES-XPN-128-true] PASSED                                                                                                              [ 67%]                                                                
macsec/test_macsec.py::TestControlPlane::test_mka_session[security-GCM-AES-XPN-128-true] PASSED                                                                                                          [ 70%]                                                                
macsec/test_macsec.py::TestDataPlane::test_server_to_neighbor[GCM-AES-XPN-128-security-true] PASSED                                                                                                      [ 72%]                                                                
macsec/test_macsec.py::TestDataPlane::test_neighbor_to_neighbor[GCM-AES-XPN-128-security-true] PASSED                                                                                                    [ 75%]                                                                
macsec/test_macsec.py::TestControlPlane::test_wpa_supplicant_processes[GCM-AES-XPN-256-security-false] PASSED                                                                                            [ 77%]                                                                
macsec/test_macsec.py::TestControlPlane::test_appl_db[security-GCM-AES-XPN-256-false] PASSED                                                                                                             [ 80%]                                                                
macsec/test_macsec.py::TestControlPlane::test_mka_session[security-GCM-AES-XPN-256-false] PASSED                                                                                                         [ 82%]                                                                
macsec/test_macsec.py::TestDataPlane::test_server_to_neighbor[GCM-AES-XPN-256-security-false] PASSED                                                                                                     [ 85%]                                                                
macsec/test_macsec.py::TestDataPlane::test_neighbor_to_neighbor[GCM-AES-XPN-256-security-false] PASSED                                                                                                   [ 87%]                                                                
macsec/test_macsec.py::TestControlPlane::test_wpa_supplicant_processes[GCM-AES-XPN-256-security-true] PASSED                                                                                             [ 90%]                                                                
macsec/test_macsec.py::TestControlPlane::test_appl_db[security-GCM-AES-XPN-256-true] PASSED                                                                                                              [ 92%]                                                                
macsec/test_macsec.py::TestControlPlane::test_mka_session[security-GCM-AES-XPN-256-true] PASSED                                                                                                          [ 95%]                                                                
macsec/test_macsec.py::TestDataPlane::test_server_to_neighbor[GCM-AES-XPN-256-security-true] PASSED                                                                                                      [ 97%]                                                                
macsec/test_macsec.py::TestDataPlane::test_neighbor_to_neighbor[GCM-AES-XPN-256-security-true] PASSED                                                                                                    [100%]          
```

#### Any platform specific information?
Tested in Virtual Switch and Arista 7280

#### Supported testbed topology if it's a new test case?
T0

### Documentation 
https://github.com/Azure/sonic-mgmt/pull/4885
<!--
(If it's a new feature, new test case)
Did you update documentation/Wiki relevant to your implementation?
Link to the wiki page?
-->

### CODE REVIEW

**Comment by Pterosaur** [comment]
Hi @wangxin , You don't need to review this PR, it's just for a temporary purpose. Please review https://github.com/Azure/sonic-mgmt/pull/3481 which is included by this PR and is a isolated PR.

**Comment by rlhui** [comment]
@Pterosaur - can we add a doc for macsec test plan? Thanks.

**Comment by sacnaik** [comment]
This PR is in Draft state. can you please share the plan to commit this PR to master? 
Are these planned to be validated on Virtual platform (VS) only? 
 
Most of the control path tests regarding macsec are limited test coverage within the scope of properties verification into DBs. In my opinion these test cases need to be extended at system behavior functional level.
Such as,
Macsec on VRF interface.
Rekey behavior
Fallback CKN feature
Macsec packet without encryption (i.e when policy = INTEGRITY_ONLY)
Key server selection with higher and lower priority value
Macsec traffic resumes when interface administrative status shutdown and resume
Macsec feature's behavior on config reload, fastboot and LC reload
send_sci true/false etc
Counters and stat based test.
Platform agnostic tests for check mka session(Currently it is limited to VM)
 
The macsec test plan(https://github.com/Pterosaur/sonic-mgmt/blob/macsec_platform/docs/testplan/MACsec-test-plan.md#) covers very few of them under functional area.
 
Is there a plan to document and validate the above-mentioned MACSec functional area/scenarios? If so, can you please share the relevant document, test scripts etc.

**Comment by Pterosaur** [comment]
> This PR is in Draft state. can you please share the plan to commit this PR to master? Are these planned to be validated on Virtual platform (VS) only?
> 
> Most of the control path tests regarding macsec are limited test coverage within the scope of properties verification into DBs. In my opinion these test cases need to be extended at system behavior functional level. Such as, Macsec on VRF interface. Rekey behavior Fallback CKN feature Macsec packet without encryption (i.e when policy = INTEGRITY_ONLY) Key server selection with higher and lower priority value Macsec traffic resumes when interface administrative status shutdown and resume Macsec feature's behavior on config reload, fastboot and LC reload send_sci true/false etc Counters and stat based test. Platform agnostic tests for check mka session(Currently it is limited to VM)
> 
> The macsec test plan(https://github.com/Pterosaur/sonic-mgmt/blob/macsec_platform/docs/testplan/MACsec-test-plan.md#) covers very few of them under functional area.
> 
> Is there a plan to document and validate the above-mentioned MACSec functional area/scenarios? If so, can you please share the relevant document, test scripts etc.

This PR is been developed. We plan that there is a community review meeting to MACsec test plan doc this month and  we will release this PR about next month.

In this PR, we focused on our scenario that MACsec will be only enabled on Ethernet Port so we don't have a short-term plan to support the VRF port. But other suggestions are very useful and we are considering to add them into this PR. All related document will be added to the document you mentioned by (https://github.com/Azure/sonic-mgmt/pull/4885).

**Review by jimmyzhai — DISMISSED** [review]

**Review by jimmyzhai — APPROVED** [review]

**Pull request merged**
