### PR TITLE
[BGP] Adding checks for bgp sessions and routes on VMs

### PR DESCRIPTION
**Pull request by congh-nvidia**
### Description of PR

Summary:
This change is to fix the test issue Fixes https://github.com/Azure/sonic-mgmt/issues/4337 [bgp_traffic_shift] no neighbors check after restart bgp service | dependency of execution tests order.

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012

#### What is the motivation for this PR?
This change is to fix the test issue Fixes https://github.com/Azure/sonic-mgmt/issues/4337 [bgp_traffic_shift] no neighbors check after restart bgp service | dependency of execution tests order.
#### How did you do it?
When another bgp test run after test_traffic_shfit.py::test_TSA_B_C_with_no_neighbors, there is a chance that the routes used in the test have not yet been learnt by the VMs.
To resolve the issue, all routes on the VMs need to be checked at the end of test_TSA_B_C_with_no_neighbors.
It costs a lot of time if we verify routes on VMs one by one. So I changed parse_routes_on_eos() to run in parallel on all VMs to shorten the checking time.
#### How did you verify/test it?
Have run the test on two different t0 setups, all passed.
The run time of case test_TSA_B_C_with_no_neighbors will increase by about 5 mins due to the new checks. But because parse_routes_on_eos() is also used in the other two cases of test_traffic_shift.py, the total run time of test_traffic_shift.py will decrease by about 1 minute.

### CODE REVIEW

**Comment by liat-grozovik** [comment]
@wangxin could you please help to review?

**Comment by liat-grozovik** [comment]
@roysr-nv could you please review?
@yxieca could you please review or assign someone?

**Review by yxieca — APPROVED** [review]

**Pull request merged**
