### PR TITLE
[testbed]: Add t0-64-32 topo

### PR DESCRIPTION
**Pull request by pavel-shirshov**
This topology is a copy of t0-64 topology but with reduced number of ports under Vlan2.
It should work for testing fast-reboot for devices with 32 ports.

### CODE REVIEW

**Comment by stcheng** [comment]
resolve the conflicts?

**Comment by paulnice** [comment]
Probably we need to decide first do we need this change or not.
This t0-32 topology is modification of t0-64. I removed last 32 ports to allow run t0-64 topology on 32 port devices. I think, probably we need to name this topology t0-64-32. But it looks ugly for me.
Any thoughts?

**Comment by pavel-shirshov** [comment]
Probably we need to decide first do we need this change or not.
This t0-32 topology is modification of t0-64. I removed last 32 ports to allow run t0-64 topology on 32 port devices. I think, probably we need to name this topology t0-64-32. But it looks ugly for me.
Any thoughts?

**Comment by pavel-shirshov** [comment]
Renamed and updated. The conflict resolved

**Pull request merged**
