### PR TITLE
Fix docker shell 2

### PR DESCRIPTION
**Pull request by msosyak**
### Description of PR

In this PR #1253 I have tested docker plugin by running dip_sib and lag2 (lldp task run in lldp container) test cases and everything was fine.
But after regression, I have noticed that some tests failed due to this plugin with error:
```KeyError: 'Requested entry (plugin_type: shell plugin: docker setting: ansible_python_interpreter ) was not defined in configuration.'``` on copy task.

Here is the fix for the error described above.

Summary:
Fixed docker shell plugin part 2
Fixes # (issue)

### Type of change

- [x] Bug fix
- [] Testbed and Framework(new/improvement)
- [] Test case(new/improvement)

#### How did you do it?
Defined mandatory `container_name` option for this plugin
Change `remove` and `build_module_command` to use it as a container name source and replace:
```
vars:
    ansible_shell_type: docker
    ansible_python_interpreter: docker exec -i swss python
```
to
```
vars:
    ansible_shell_type: docker
    container_name: swss
```
#### How did you verify/test it?
run ecn_wred, coop and dip_sib test_cases

### CODE REVIEW

**Comment by msosyak** [comment]
@qiluo-msft could you have a look at this?

**Comment by qiluo-msft** [comment]
I suspect you are not fixing the root issue. I did a while and found one missing in docker.py, you may need to override `ShellBase.append_command()`.

Please help open an issue, and provide the verbose error message in order to better communicate.

**Comment by msosyak** [comment]
Related issue https://github.com/Azure/sonic-mgmt/issues/1268
@qiluo-msft  I am not sure that append_command() will really help us as it just called to concatenate two commands. I go deep and have made this PR https://github.com/Azure/sonic-mgmt/pull/1269 where I used native docker connection plugin.

**Comment by msosyak** [comment]
Closed In favor of #1269

**Pull request closed without merging**
