### PR TITLE
BGP Convergence Testplan for Benchmark Performance

### PR DESCRIPTION
**Pull request by selldinesh**
### Description of PR

Summary:
- This PR is a contribution on behalf of Keysight Technologies.
- The test covers BGP data plane convergence for local link failure scenario.
- Traffic generator will be used to configure ebgp peering between chassis ports and SONiC DUT by advertising IPv4 routes
- Receiving ports will be advertising the same virtual IPv4 addresses.
- link failures will be simulated on the port by "simulating link down" event.
- Dut fixture configures N path ecmp between sonic and tgen ports and runs the test by simulating link down on tgen ports and 
-  calculates the average packet loss duration over multiple iterations which results in the convergence value
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Documentation 
https://github.com/Azure/sonic-mgmt/blob/master/docs/testplan/BGP%20Convergence%20Testplan%20for%20single%20DUT.md#test-case--1--convergence-performance-when-remote-link-fails-route-withdraw

### CODE REVIEW

**Comment by wangxin** [comment]
PR testing failed with below error, can you look into it?
```
__________________ ERROR collecting ixia/test_ixia_traffic.py __________________
ImportError while importing test module '/var/src/s/tests/ixia/test_ixia_traffic.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
ixia/test_ixia_traffic.py:22: in <module>
    from tests.common.ixia.ixia_fixtures import ixia_api_serv_ip, ixia_api_serv_user,\
common/ixia/ixia_fixtures.py:14: in <module>
    import snappi
E   ImportError: No module named snappi
```
https://dev.azure.com/mssonic/build/_build/results?buildId=7411&view=logs&j=3f6395b2-1619-5ebe-f305-2aedcf353cb5&t=f9db2383-9349-50ba-61c3-4bde15cec59e&l=456

**Comment by selldinesh** [comment]
Can you please do a pip install snappi and try again

**Comment by wangxin** [comment]
@selldinesh If this case depends on specific version of package installed in sonic-mgmt docker image, can you submit a PR to update the sonic-mgmt Dockerfile to include this dependency?

**Comment by selldinesh** [comment]
@wangxin There is no need for a separate docker image, future releases of snappi[ixnetwork} should also be support.

**Comment by selldinesh** [comment]
@wangxin Raised a PR for the docker file ` Update Dockerfile.j2 for snappi[ixnetwork]==0.3.4 #7204 `

**Comment by wangxin** [comment]
Thanks @selldinesh!
We need to wait until https://github.com/Azure/sonic-buildimage/pull/7204 is merged and new sonic-mgmt image is available for this PR to pass PR testing.

**Comment by wangxin** [comment]
@selldinesh Package snappi has been added to sonic-mgmt docker in PR https://github.com/Azure/sonic-buildimage/pull/7292
Can you resolve the merge conflicts? Then we can retry another round of PR testing to see if can pass.

**Comment by selldinesh** [comment]
@wangxin may i know what is the merge conflict?

**Comment by selldinesh** [comment]
@wangxin It seems I don't have the write access to resolve the merge conflict.

**Pull request closed without merging**
