### PR TITLE
Add the readonly command rvtysh in the test case

### PR DESCRIPTION
**Pull request by xumia**
### Description of PR

Summary:
Fixes # (issue)
Support to test the new readonly command rvtysh, not support the vtysh as readonly command.
See https://github.com/Azure/sonic-buildimage/pull/7383

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

#### What is the motivation for this PR?
Test the command rvtysh, allow any user running the command with sudo permission.

#### How did you do it?
Add the command in the existing test case test_ro_user_allowed_command.

### CODE REVIEW

**Comment by qiluo-msft** [comment]
> def test_ro_user_allowed_command(localhost, duthosts, enum_rand_one_per_hwsku_hostname, creds_all_duts, test_tacacs):

This testcase will run on image version >= 201911. So will it work on old images? If not, please backport features before you merge this PR.

---
Refers to: tests/tacacs/test_ro_user.py:74 in 0a971ff. [](commit_id = 0a971ff1c158248cd83e04f23c1f943c41947126, deletion_comment = False)

**Comment by qiluo-msft** [comment]
> def test_ro_user_banned_command(localhost, duthosts, enum_rand_one_per_hwsku_hostname, creds_all_duts, test_tacacs):

Do you want to test some banned command?

---
Refers to: tests/tacacs/test_ro_user.py:143 in 0a971ff. [](commit_id = 0a971ff1c158248cd83e04f23c1f943c41947126, deletion_comment = False)

**Comment by xumia** [comment]
> > def test_ro_user_banned_command(localhost, duthosts, enum_rand_one_per_hwsku_hostname, creds_all_duts, test_tacacs):
> 
> Do you want to test some banned command?
> 
> Refers to: tests/tacacs/test_ro_user.py:143 in [0a971ff](https://github.com/Azure/sonic-mgmt/commit/0a971ff1c158248cd83e04f23c1f943c41947126). [](commit_id = [0a971ff](https://github.com/Azure/sonic-mgmt/commit/0a971ff1c158248cd83e04f23c1f943c41947126), deletion_comment = False)

We do not ban any commands yet, we need to check-in the sonic-utilities PR https://github.com/Azure/sonic-utilities/pull/1572, and send another PR to change sudoers, and then we can do it.

**Comment by xumia** [comment]
> > def test_ro_user_allowed_command(localhost, duthosts, enum_rand_one_per_hwsku_hostname, creds_all_duts, test_tacacs):
> 
> This testcase will run on image version >= 201911. So will it work on old images? If not, please backport features before you merge this PR.
> 
> Refers to: tests/tacacs/test_ro_user.py:74 in [0a971ff](https://github.com/Azure/sonic-mgmt/commit/0a971ff1c158248cd83e04f23c1f943c41947126). [](commit_id = [0a971ff](https://github.com/Azure/sonic-mgmt/commit/0a971ff1c158248cd83e04f23c1f943c41947126), deletion_comment = False)

@qiluo-msft , the feature has been merged to 201911, can we merge it now?

**Review by qiluo-msft — APPROVED** [review]

**Pull request merged**
