### PR TITLE
[cacl][pytest] Test control plane ACL application

### PR DESCRIPTION
**Pull request by jleveque**
- Add new test_cacl_application.py file to test that caclmgrd is applying the expected iptables/ip6tables rules
- Rename `test_control_plane_acl.py` as `test_cacl_function.py`, as its purpose is to test the actual control plane ACL functionality

### CODE REVIEW

**Comment by jleveque** [comment]
Retest vsimage please

**Comment by jleveque** [comment]
Retest vsimage please

**Comment by jleveque** [comment]
Retest vsimage please

**Comment by jleveque** [comment]
Retest vsimage please

**Comment by jleveque** [comment]
Retest vsimage please

**Comment by lguohan** [comment]
@jleveque , if you look at the error, it is because you have changed the test name.

**Comment by jleveque** [comment]
> @jleveque , if you look at the error, it is because you have changed the test name. retry won't work.

True. However, I encountered different, unrelated errors on the first couple runs. And from the last run, you can see it never made it to the cacl tests, it failed on DHCP relay tests:

```
04:02:45  =================================== FAILURES ===================================
04:02:45  ___________________ test_dhcp_relay_start_with_uplinks_down ____________________
...
```

Nevertheless, I think we need a way for the check builds to pick up test name changes.

**Pull request merged**
