### PR TITLE
[Mellanox][platform] Adjust test case according to get_fan_direction update

### PR DESCRIPTION
**Pull request by stephenxs**
### Description of PR

Summary:
Adjust test case according to get_fan_direction update
This PR depends on Azure/sonic-buildimage#7386

Signed-off-by: Stephen Sun <stephens@nvidia.com>

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

#### What is the motivation for this PR?
Adjust test case according to get_fan_direction update

#### How did you do it?
Replace the old way to mock fan direction with the new way.
- The old way: fan direction is fetched via reading `/var/run/hw-management/system/fan_dir`, supported on Spetrum-2/3 platforms.
- The new way: fan direction is fetched via reading `/var/run/hw-management/thermal/fanX_dir`, supported on all platforms.

#### How did you verify/test it?
Run regression test.

### CODE REVIEW

**Comment by stephenxs** [comment]
> This pull request **introduces 1 alert** when merging [52dc540](https://github.com/Azure/sonic-mgmt/commit/52dc540a7053774df6d1947c8ad0acdb55def7de) into [1e30b38](https://github.com/Azure/sonic-mgmt/commit/1e30b383615cc8946ffbeded76c04475ba7f709c) - [view on LGTM.com](https://lgtm.com/projects/g/Azure/sonic-mgmt/rev/pr-ff23f36308a8f17a234dc0d4a052eb41d5139818)
> 
> **new alerts:**
> 
> * 1 for Variable defined multiple times

Fixed.

**Comment by liat-grozovik** [comment]
will the test know how to run with an old image which is not pending on the new PR you are referring to?

**Comment by stephenxs** [comment]
> will the test know how to run with an old image which is not pending on the new PR you are referring to?

No. I assume the pending PR should be merged before the test can run.
Do we need to support run the new test without it? I think we don't need to if it will be cherry-picked to 202012.

**Comment by stephenxs** [comment]
> will the test know how to run with an old image which is not pending on the new PR you are referring to?

I just realized that this test can run against 201911. Just update it to tolerance it.

**Review by jleveque — APPROVED** [review]

**Comment by stephenxs** [comment]
Hi @jleveque can we have this PR merged as all tests passed? thanks

**Pull request merged**
