### PR TITLE
[Platform API] Remove bounds check for thermal values

### PR DESCRIPTION
**Pull request by zzhiyuan**
### Description of PR

Summary:
Fixes platform API test failure due to thermals with low thresholds too low or high thresholds too high.
Thermals vary vastly with low bounds being -55 or lower, and high bounds with 115 or higher. It's hard to set a good threshold while still making the test useful.

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

#### What is the motivation for this PR?
In Arista's testing we found thermal sensors that do not conform to existing checks.

### CODE REVIEW

**Comment by jleveque** [comment]
@zzhiyuan: Please fix conflicts.

**Comment by zzhiyuan** [comment]
> @zzhiyuan: Please fix conflicts.

Done.

**Review by jleveque — APPROVED** [review]

**Pull request merged**
