### PR TITLE
fixed T0 patch preparation in add_rack test

### PR DESCRIPTION
**Pull request by antonptashnik**
### Description of PR

Summary: fixed T0 patch preparation in add_rack test
Fixes # (issue)

The test removes one T0 from config and restores it using configlet. When preparing T0 config for restore, the test makes a wrong assumption about a config present for T0 and thus fails. The mentioned config is queue profile assignment for an interface queues 5-6. It is listed in [the default config](https://github.com/Azure/sonic-buildimage/blob/master/files/build_templates/buffers_config.j2) but vendors may redefine it [like Barefoot does](https://github.com/Azure/sonic-buildimage/blob/master/device/barefoot/x86_64-accton_wedge100bf_32x-r0/montara/buffers_defaults_t1.j2).
The PR fixes the issue removing explicit config reference and collects present queue-profile assignments only.

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012

#### What is the motivation for this PR?
Make the test work on more platforms
#### How did you do it?
Removed an explicit reference to the config that may vary
#### How did you verify/test it?
py.test --inventory=../ansible/lab,../ansible/veos --testbed_file=../ansible/testbed.csv --module-path=../ansible/library -v -rA --topology=t1,any configlet/test_add_rack.py

### CODE REVIEW

**Comment by SavchukRomanLv** [comment]
@wangxin @yxieca could you please take a look?

**Comment by SavchukRomanLv** [comment]
@renukamanavalan could you please take a look?

**Review by renukamanavalan — APPROVED** [review]

**Comment by antonptashnik** [comment]
@wangxin @neethajohn please take a look

**Review by wangxin — APPROVED** [review]

**Pull request merged**
