### PR TITLE
[kvm] Enable loganalyzer for KVM tests

### PR DESCRIPTION
**Pull request by daall**
Signed-off-by: Danny Allen <daall@microsoft.com>

### Description of PR

Summary: Enable loganalyzer for KVM tests
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [x] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

#### What is the motivation for this PR?
We often experience widespread failures due to persistent loganalyzer failures. The goal is to try to reduce these by running loganalyzer during PR tests here and also during buildimage PR tests.

#### How did you do it?
Remove the disable flag.

#### How did you verify/test it?
Tested locally, also going to let it run several times on Jenkins to verify.

### CODE REVIEW

**Review by lguohan — APPROVED** [review]

**Comment by daall** [comment]
@lguohan this PR hit the bulk API error

**Comment by daall** [comment]
Waiting for: https://sonic-jenkins.westus2.cloudapp.azure.com/job/vs/job/buildimage-vs-image/537/

**Comment by daall** [comment]
retest this please

**Comment by daall** [comment]
Waiting for: https://sonic-jenkins.westus2.cloudapp.azure.com/job/vs/job/buildimage-vs-image/541/ for the LLDP fix

**Comment by daall** [comment]
retest this please

**Comment by daall** [comment]
retest this please

**Comment by daall** [comment]
retest this please

**Comment by daall** [comment]
retest this please

**Comment by daall** [comment]
@lguohan it looks like there is still some sort of lldp crash, I'll try to see if it's the same one as before

**Comment by daall** [comment]
retest vsimage please

**Comment by yxieca** [comment]
retest vsimage please

**Comment by daall** [comment]
@yxieca @lguohan we're very close now, we just need a swss submodule update to pick up the reference counting fix and then we should be gtg

**Comment by lguohan** [comment]
@shi-su can you update the swss submodule?

**Comment by shi-su** [comment]
> @shi-su can you update the swss submodule?

swss submodule update PR submitted. https://github.com/Azure/sonic-buildimage/pull/5964

**Comment by daall** [comment]
retest this please

**Comment by daall** [comment]
retest vsimage please

**Comment by daall** [comment]
retest this please

**Comment by daall** [comment]
retest this please

**Comment by daall** [comment]
retest this please

**Pull request merged**
