### PR TITLE
[chassis] Enhance Fib and IP Decap test case

### PR DESCRIPTION
**Pull request by abdosi**
What I did:

1. Fixes: https://github.com/Azure/sonic-mgmt/issues/4982
2. Enhance IP Decap test case for chassis.
3. Depends on https://github.com/Azure/sonic-mgmt/pull/5011

Following changes done:-
1. For T2 make VOQ Data fetch option using switch_type
2. Support router-mac per asic and make test case adapt to that using PTF Port map.
3. Fib Balancing test case take care for multi-dut if there single vs multiple routing hop.

How I verify:

Manual Verification

### CODE REVIEW

**Comment by abdosi** [comment]
cc @vperumal  fixes both fib and decap test case.

**Review by wangxin — DISMISSED** [review]

**Comment by wangxin** [comment]
@abdosi The change looks good to me. Can you check and resolve the merge conflicts?

**Comment by abdosi** [comment]
> @abdosi The change looks good to me. Can you check and resolve the merge conflicts?

@wangxin can you please re-approve.

**Review by wangxin — APPROVED** [review]

**Pull request merged**
