### PR TITLE
Add lldpd.conf for AS7512

### PR DESCRIPTION
**Pull request by NStetskovych**
Signed-off-by: Nadiya.Stetskovych <Nadiya.Stetskovych@cavium.com>

### CODE REVIEW

**Comment by NStetskovych** [comment]
@stcheng pls review

**Comment by lguohan** [comment]
if you use minigraph of ACS-MSN2700, you would not need this file at all, it will be simpler.

**Comment by NStetskovych** [comment]
@lguohan Is it ok  if we will  share one config file wtith ACS-MSN2700? Please advice correct place to set minigraph facts(file) for AS7512 asic ( add if i main task?) I`ve  found it inconveniently manually change mgmt_ip, for example.

**Comment by stcheng** [comment]
I think it is okay to put a switchX.xml file in the minigraph folder for AS7512. The only thing that is needed for manual change is the mgmt._ip in the minigraph file. With #88, only Force10-S6000 requires an lldp.conf file.

**Pull request closed without merging**
