### PR TITLE
update show_muxcable_status

### PR DESCRIPTION
**Pull request by zjswhhh**
### Description of PR

Summary:
Fixes # (issue)

Stemming from
https://github.com/Azure/sonic-utilities/pull/1961
https://github.com/Azure/sonic-utilities/pull/2067

New columns are added to ```show muxcable status``` outputp. Update show_cable_status to use ```--json``` to avoid parsing error. 

Checked other usage of ```show muxcable status``` in sonic-mgmt, it's either using ```--json``` already, or for logging, or the current parse approach is compatible. 

signed-off: Jing Zhang zhangjing@microsoft.com

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911

### CODE REVIEW

**Review by lolyu — APPROVED** [review]

**Comment by vdahiya12** [comment]
Hi @zjswhhh is this the only fixture using show mux status in Dual-ToR testbeds

**Comment by zjswhhh** [comment]
> Hi @zjswhhh is this the only fixture using show mux status in Dual-ToR testbeds ?

Not really, but some are already using ```--json```, some are just simply recording the raw output when tests fail.

**Comment by vdahiya12** [comment]
> > Hi @zjswhhh is this the only fixture using show mux status in Dual-ToR testbeds ?
> 
> Not really, but some are already using `--json`, some are just simply recording the raw output when tests fail.

We should change all the fixtures then.

**Comment by zjswhhh** [comment]
@vdahiya12  - can I have your approval on this PR?

**Review by vdahiya12 — APPROVED** [review]

**Pull request merged**
