### PR TITLE
[Platform API][pytest] fix test_platform_info.py::test_thermal_control_load_invalid_value_json

### PR DESCRIPTION
**Pull request by vdahiya12**
Signed-off-by: vaibhav-dahiya <vdahiya@microsoft.com>

### Description of PR
Currently Arista Platforms do not support speed setting of fans in the thermalctl script, so in order to apply an invalid value policy what we would do is apply a duplicate policy, in order to raise an exception and hence loganalyzer issue would be fixed.

Summary:
Fixes # (issue)

### Type of change

- [] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 201911

#### How did you do it?
Ran the changes on Arista7050cx3 testbed

#### How did you verify/test it?
Verified that the test case works fine.

### CODE REVIEW

**Comment by sujinmkang** [comment]
is this error not failure?

**Comment by vdahiya12** [comment]
> is this fix for an error not a failure?

For a failure. Actually, it looks like the test test_platform_info.py::test_thermal_control_load_invalid_value_json requires thermalctl to raise an exception when loading an invalid json file(loganalyzer requirement), it seems in Arista they wont run the policy upon load, so I just put a duplicate action which will catch an exception, and fix the test

**Comment by vdahiya12** [comment]
close this because its fixed in image.
https://github.com/Azure/sonic-buildimage/pull/8903

**Comment by vdahiya12** [comment]
close this because its fixed in image.
Azure/sonic-buildimage#8903

**Pull request closed without merging**
