### PR TITLE
[multi-asic]: Skip sanity check for multi-asic testing.

### PR DESCRIPTION
**Pull request by SuvarnaMeenakshi**
Signed-off-by: Suvarna Meenakshi <sumeenak@microsoft.com>

### Description of PR

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911

#### What is the motivation for this PR?
On multi-asic VS testbed, sanity check runs for long time and times out without completing sanity check.
24/08/2021 01:01:08 parallel.parallel_run                    L0073 DEBUG  | Started process 14462 running target "_check_processes_on_dut--<MultiAsicSonicHost> vlab-08"
24/08/2021 01:01:08 parallel.parallel_run                    L0077 DEBUG  | Wait for process "_check_processes_on_dut--<MultiAsicSonicHost> vlab-08" with pid "14462" to complete, timeout=1000
…
24/08/2021 01:17:48 parallel.parallel_run                    L0079 DEBUG  | Process "_check_processes_on_dut--<MultiAsicSonicHost> vlab-08" with pid "14462" completed
24/08/2021 01:17:48 parallel.parallel_run                    L0098 ERROR  | Process _check_processes_on_dut--<MultiAsicSonicHost> vlab-08 with pid 14462 is still alive, try to force terminate it.

Until a fix is done to reduce time of sanity check on multi-asic VS and root cause of increased time, skip sanity check for multi-asic VS testing.
#### How did you do it?
add skip_sanity parameter for multi-asic tests.

#### How did you verify/test it?
Tested on multi-asic VS testbed.

### CODE REVIEW

**Review by wangxin — COMMENTED** [review]
This would skip sanity check for all tests, not just multi-asic platforms. Is there a better way?

**Comment by SuvarnaMeenakshi** [comment]
> This would skip sanity check for all tests, not just multi-asic platforms. Is there a better way?

No, this will only skip for "test_multi_asic_t1_lag" TestSuite" and not for all.

**Comment by wangxin** [comment]
> > This would skip sanity check for all tests, not just multi-asic platforms. Is there a better way?
> 
> No, this will only skip for "test_multi_asic_t1_lag" TestSuite" and not for all.

Oh, I see, I didn't expand the context. This should just be a temporary workaround, not a long term solution, right?

**Comment by SuvarnaMeenakshi** [comment]
> > > This would skip sanity check for all tests, not just multi-asic platforms. Is there a better way?
> > 
> > 
> > No, this will only skip for "test_multi_asic_t1_lag" TestSuite" and not for all.
> 
> Oh, I see, I didn't expand the context. This should just be a temporary workaround, not a long term solution, right?

Yes, there is a TODO comment line added in the script as well.
"# TODO: Remove disable of loganaler and sanity check once multi-asic testbed is stable."

This is to kick start multi-asic VS testing.

**Review by wangxin — APPROVED** [review]

**Pull request merged**
