### PR TITLE
[tests] add sym link to ansible.cfg for pytest-tests

### PR DESCRIPTION
**Pull request by stepanblyschak**
Need to make pytest-ansible to use ansible.cfg, otherwise if hosts
are not in known_hosts we will get the following error:

```
16:02:49         "    def _run(self, *module_args, **complex_args):",
16:02:49         "        module_ignore_errors = complex_args.pop('module_ignore_errors', False)",
16:02:49         "        module_async = complex_args.pop('module_async', False)",
16:02:49         "    ",
16:02:49         "        if module_async:",
16:02:49         "            def run_module(module_args, complex_args):",
16:02:49         "                return self.module(*module_args, **complex_args)[self.hostname]",
16:02:49         "            pool = ThreadPool()",
16:02:49         "            result = pool.apply_async(run_module, (module_args, complex_args))",
16:02:49         "            return pool, result",
16:02:49         "    ",
16:02:49         "        res = self.module(*module_args, **complex_args)[self.hostname]",
16:02:49         "        if res.is_failed and not module_ignore_errors:",
16:02:49         ">           raise RunAnsibleModuleFail(\"run module {} failed, errmsg {}\".format(self.module_name, res))",
16:02:49         "E           RunAnsibleModuleFail: run module command failed, errmsg {'msg': u\"ERROR! Using a SSH password instead of a key is not possible because Host Key checking is enabled and sshpass does not support this.  Please add this host's fingerprint to your known_hosts file to manage this host.\", 'failed': True}",
16:02:49         "",
```

Signed-off-by: Stepan Blyschak <stepanb@mellanox.com>

### Description of PR

Summary:
Fixes # (issue)

### Type of change

- [x] Bug fix
- [] Testbed and Framework(new/improvement)
- [] Test case(new/improvement)

### CODE REVIEW

**Comment by liat-grozovik** [comment]
Note: required for 201811 as platform test backported to 201811 is pytest base.

**Comment by lguohan** [comment]
suggest to copy and paste a new file, so that ansible test changes won't affect pytest changes.

**Comment by stepanblyschak** [comment]
@lguohan
Why they should be different if they pytest still uses ansible transport and ansible modules?
Besides, we and I assume some one else have different ansible.cfg tailored for our environment.
Creating a copy based on upstream may produce a difference for us between ansible and pytest transport/module settings and we will have to maintain both files.

**Comment by liat-grozovik** [comment]
@lguohan can we assume the comment is addressed and merge is allowed?

**Comment by lguohan** [comment]
let me merge to unblock this.

**Pull request merged**
