### PR TITLE
[test_fib] Enable backend topologies

### PR DESCRIPTION
**Pull request by lolyu**
### Description of PR

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 201911

#### What is the motivation for this PR?
Make `test_fib` compatible with backend topologies

Signed-off-by: Longxiang Lyu <lolv@microsoft.com>

#### How did you do it?
1. In retrieving fib info, add support to parse subinterfaces as the destination ports
2. Adding pseudo default ipv4 and ipv6 routes to the fib.

#### How did you verify/test it?
Run `test_fib`
```
fib/test_fib.py .                                                                                                                                                                                         [100%]

=========================================================================================== 1 passed in 43.87 seconds ===========================================================================================
```

### CODE REVIEW

**Comment by lolyu** [comment]
depends on https://github.com/Azure/sonic-mgmt/pull/3727

**Comment by lolyu** [comment]
```
fib/test_fib.py ...                                                                                                                                                                                       [100%]

========================================================================================== 3 passed in 790.54 seconds ===========================================================================================
```

**Comment by lolyu** [comment]
Current issue:
```
E               "stderr_lines": [
E                   "WARNING: No route found for IPv6 destination :: (no default route?)", 
E                   "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py:33: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.", 
E                   "  from cryptography.hazmat.backends import default_backend", 
E                   "fib_test.FibTest ... ERROR", 
E                   "", 
E                   "======================================================================", 
E                   "ERROR: fib_test.FibTest", 
E                   "----------------------------------------------------------------------", 
E                   "Traceback (most recent call last):", 
E                   "  File \"ptftests/fib_test.py\", line 429, in runTest", 
E                   "    self.check_ip_ranges()", 
E                   "  File \"ptftests/fib_test.py\", line 157, in check_ip_ranges", 
E                   "    self.check_balancing(covered_ip_ranges, dut_index, ipv4)", 
E                   "  File \"ptftests/fib_test.py\", line 196, in check_balancing", 
E                   "    src_port, exp_port_list, next_hop = self.get_src_and_exp_ports(dst_ip)", 
E                   "  File \"ptftests/fib_test.py\", line 166, in get_src_and_exp_ports", 
E                   "    next_hop = self.fibs[active_dut_index][dst_ip]", 
E                   "  File \"ptftests/fib.py\", line 71, in __getitem__", 
E                   "    return self._ipv4_lpm_dict[str(ip)]", 
E                   "  File \"ptftests/lpm.py\", line 77, in __getitem__", 
E                   "    return self._subnet_tree[key]", 
E                   "  File \"/usr/local/lib/python2.7/dist-packages/SubnetTree.py\", line 157, in __getitem__", 
E                   "    return _SubnetTree.SubnetTree___getitem__(self, cidr)", 
E                   "KeyError: '192.168.60.145'", 
E                   "", 
E                   "----------------------------------------------------------------------", 
E                   "Ran 1 test in 2.887s", 
E                   "", 
E                   "FAILED (errors=1)"
E               ], 
E               "stdout": "", 
E               "stdout_lines": []
E           }
```
* This is because routes in the DUT splits the whole IP range (`0.0.0.0`~`255.255.255.255`) into IP ranges. And some of those ranges are not **routable** by the DUT because there is no default route on storage backend T1 devices. Since there is no default route, the prefix tree(`SubnetTree`) could find a match for those un-routable ranges. So in this patch, adding a pseudo default route with no next-hops to enable the prefix tree to route those IP ranges, but since the default route has no next-hops, the test will skip:
https://github.com/Azure/sonic-mgmt/blob/990bab8a765d571ba89425766b9afc63b966170f/ansible/roles/test/files/ptftests/fib_test.py#L184

**Comment by wangxin** [comment]
This change will conflict with https://github.com/Azure/sonic-mgmt/pull/3702

**Review by neethajohn — APPROVED** [review]

**Pull request merged**
