### PR TITLE
configlet test code for AddRack scenario

### PR DESCRIPTION
**Pull request by renukamanavalan**
### Description of PR

Summary:
Added test case for configlet to test AddRack scenario.

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [x] 201911

#### What is the motivation for this PR?
Provide test coverage for AddRack scenario

#### How did you do it?
Wrote a test code to simulate AddRack scenario and test.

#### How did you verify/test it?
Run the test to pass
#### Any platform specific information?
None
#### Supported testbed topology if it's a new test case?
T1

### CODE REVIEW

**Comment by lguohan** [comment]
can you fix lgtm alerts and also add this to kvm test

**Comment by renukamanavalan** [comment]
test_container_checker is failing repeatedly.

**Comment by yozhao101** [comment]
@renukamanavalan I discussed this issue with Vaibhav who also catch this. Can you re-run this PR testing with the command `/azp run` please?

**Comment by renukamanavalan** [comment]
Container checker failure again.

2021-09-01T00:55:15.2433058Z =================================== FAILURES ===================================
2021-09-01T00:55:15.2435309Z ____________________ test_container_checker[vlab-03|teamd] _____________________

**Comment by yozhao101** [comment]
> Container checker failure again.
> 
> 2021-09-01T00:55:15.2433058Z =================================== FAILURES ===================================
> 2021-09-01T00:55:15.2435309Z ____________________ test_container_checker[vlab-03|teamd] _____________________

Thanks for update! I am working on this issue.

**Review by prsunny — APPROVED** [review]

**Pull request merged**
