### PR TITLE
[sensors_test] check stderr value before decoding

### LINKED ISSUE #4643: [sensors_facts] test_sensors failed due to test issue
**Description**
The test_sensors failed due to the last test changes #4612 
No checks of the _stderr_ before decoding. The value can be _None_.

**Steps to reproduce the issue:**
1. Run test_sensors

**Describe the results you received:**

        # Gather sensor facts 
       sensors_facts = duthost.sensors_facts(checks=sensors_checks[platform])['ansible_facts'] 

E               }, 
E               "msg": "'NoneType' object has no attribute 'decode'" 
E           } 

**Describe the results you expected:**
The test case is passed and stable.

**Additional information you deem important:**

N/A as it's test issue

### PR DESCRIPTION
**Pull request by AntonHryshchuk**
Signed-off-by: Anton <antonh@nvidia.com>

### Description of PR

Summary: Added validation of the value before decoding.
Fixes #4643 

### Type of change

- [X] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911

#### What is the motivation for this PR?
Fix the test.

#### How did you do it?
Added validation of the value before working with it.

#### How did you verify/test it?
The test_sensors executed on physical after the change

#### Any platform specific information?
N/A

#### Supported testbed topology if it's a new test case?
N/A

### Documentation 

N/A

### CODE REVIEW

**Comment by liat-grozovik** [comment]
@AntonHryshchuk  what is the expected behaviour in case the value does not meet the requirement? test fail? any error in the log that can explain the failure/return?

**Comment by AntonHryshchuk** [comment]
> @AntonHryshchuk what is the expected behaviour in case the value does not meet the requirement? test fail? any error in the log that can explain the failure/return?




In the PR #4612 was added python3 support to sensor test - decote to output and error msgs.
The change was not correct and when the no error msg exists (a lot of time) - the test failed with error: "'NoneType' object has no attribute 'decode'"

**Comment by liat-grozovik** [comment]
@wangxin could you please help to review or suggest someone?

**Review by bingwang-ms — APPROVED** [review]

**Review by liat-grozovik — APPROVED** [review]

**Comment by AntonHryshchuk** [comment]
already fixed in #4650

**Pull request closed without merging**
