### PR TITLE
Add search_regex option for wait_for.

### PR DESCRIPTION
**Pull request by iris00522**
Summary:

Fixes # (issue)

Pytest run test_reboot.py test fail on broadcom platform.
I modified the code reference from ansible reboot yml file, then the tests passed.
========== test session starts ===============================
platform linux2 -- Python 2.7.12, pytest-4.6.7, py-1.8.0, pluggy-0.13.1 -- /usr/bin/python
cachedir: .pytest_cache
ansible: 2.8.7
rootdir: /var/sonic/sonic-mgmt/tests, inifile: pytest.ini
plugins: ansible-2.2.2
collecting ...
collected 6 items

platform/test_reboot.py::test_cold_reboot FAILED
platform/test_reboot.py::test_fast_reboot FAILED
platform/test_reboot.py::test_warm_reboot FAILED

### Type of change
[v] Bug fix
[] Testbed and Framework(new/improvement)
[] Test case(new/improvement)
Approach
How did you do it?
I modified the code reference from ansible reboot yml file.
(sonic-mgmt/ansible/roles/test/tasks/common_tasks/reboot_sonic.yml)
There are 2 modification:
1.Add search_regex option for wait_for.
2.Modify host from hostname to ansible_host.

#### How did you verify/test it?
I run pytest on broadcom platform.
========== test session starts ===============================
platform linux2 -- Python 2.7.12, pytest-4.6.7, py-1.8.0, pluggy-0.13.1 -- /usr/bin/python
cachedir: .pytest_cache
ansible: 2.8.7
rootdir: /var/sonic/sonic-mgmt/tests, inifile: pytest.ini
plugins: ansible-2.2.2
collecting ...
collected 6 items

platform/test_reboot.py::test_cold_reboot PASSED
platform/test_reboot.py::test_fast_reboot PASSED
platform/test_reboot.py::test_warm_reboot PASSED

#### Any platform specific information?
no

#### Supported testbed topology if it's a new test case?
no

Documentation

### CODE REVIEW

**Comment by lguohan** [comment]
LGTM

**Comment by lguohan** [comment]
it looks like there is conflict. hi @iris00522, can you help to resolve the conflict?

**Comment by lguohan** [comment]
still conflict. can you pull the latest master?

**Comment by iris00522** [comment]
I pull the latest master, thanks.

**Pull request merged**
