### PR TITLE
Migration of PFCWD tests to Snappi

### PR DESCRIPTION
**Pull request by ANISH-GOTTAPU**
### Description of PR
Migration of PFCWD tests from `ixnetwork-open-traffic-generator` to `snappi`

Summary:
Test case(new/improvement)

### Type of change
- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x ] Test case(new/improvement)

#### What is the motivation for this PR?
The motivation for this PR is to migrate the tests that are written with `ixnetwork open traffic generator` to `snappi`

#### How did you do it?
Replaced the code where abstract is used to snappi

#### How did you verify/test it?
verified all the tests in sonic-mgmt using pytest with DUT and IXIA connections 
snappi version used for the development of tests `snappi[ixnetwork]==0.4.20`

### CODE REVIEW

**Comment by ANISH-GOTTAPU** [comment]
This PR is dependent on https://github.com/Azure/sonic-buildimage/pull/7829/files & #3794 (will be using the same changes of common_helpers.py & snappi_helpers.py from this PR)

**Comment by baiwei0427** [comment]
@neethajohn  Can you rerun tests?

**Review by neethajohn — APPROVED** [review]

**Pull request merged**
