### PR TITLE
[vrf_test] use strings for booleans in vrf_attr_ip_state.json and vrf_restore.json

### PR DESCRIPTION
**Pull request by vboykox**
Signed-off-by: Volodymyr Boyko <volodymyrx.boiko@intel.com>

### Description of PR

Summary:
Fixes # (issue)

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012

#### What is the motivation for this PR?
Use lowercase bool string representation expected by orchagent and https://github.com/Azure/sonic-buildimage/blob/master/src/sonic-yang-models/doc/Configuration.md

#### How did you verify/test it?
by running vrf/test_vrf_attr.py, the following tests pass after the change:
test_vrf1_drop_pkts_with_ip_opt (fixed vrf_restore.json - clean-up from previous tests)
test_vrf1_drop_v4 (fixed vrf_attr_ip_state.json)
test_vrf2_drop_v6 (fixed vrf_attr_ip_state.json)

### CODE REVIEW

**Comment by vboykox** [comment]
@yejianquan Hi, please review

**Comment by yejianquan** [comment]
@vboykox 
Can you fill in the "How did you verify/test it?" section by describing how did you test it and the test results?

**Comment by vboykox** [comment]
> @vboykox Can you fill in the "How did you verify/test it?" section by describing how did you test it and the test results?

Done

**Review by yejianquan — APPROVED** [review]
LGTM

**Pull request merged**
