### PR TITLE
[Testbed 2.0]add celery executor

### PR DESCRIPTION
**Pull request by yejianquan**
### Description of PR

Summary:
Celery executor code

### Type of change

- [ ] Bug fix
- [x] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012

#### What is the motivation for this PR?
In testbed2.0, Scheduler needs sonic-mgmt dockers to execute test cases remotely as agents.
This is the celery executor code
#### How did you do it?
Implement celery executor
#### How did you verify/test it?
Run it on dev machine, it works well

### CODE REVIEW

**Comment by wangxin** [comment]
Why put this script in the sonic-mgmt repository? In my opinion, this script should stay in its own repository. We can inject it to the sonic-mgmt docker when needed.

**Comment by yejianquan** [comment]
> Why put this script in the sonic-mgmt repository? In my opinion, this script should stay in its own repository. We can inject it to the sonic-mgmt docker when needed.
Hi @wangxin 
This script belongs to sonic-mgmt repo, it enables sonic-mgmt as a remote agent. Scheduler leverages the agent's ability but not own it.
In the future, we can add various functionalities to it, like testbed healthy detecting and executing any specific test cases remotely via sonic webtools.

**Comment by yejianquan** [comment]
Will not include this agent code in sonic-mgmt repo, currently check it out from internal repo on the starting of pr test

**Pull request closed without merging**
