### PR TITLE
LACP Failover Test Scripts

### PR DESCRIPTION
**Pull request by selldinesh**
### Description of PR

Summary: LACP Failover Test Scripts
Add/Remove links physically
Add/Remove links from dut
LACP Timer Effect
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911

### CODE REVIEW

**Comment by selldinesh** [comment]
@wangxin Hi, can you please approve this merge request

**Review by yxieca — APPROVED** [review]

**Pull request merged**
