### PR TITLE
[pfc_wd] Add 150 ms delta for pfc_wd detect and restore wait time

### PR DESCRIPTION
**Pull request by vsenchyshyn**
Signed-off-by: Vitaliy Senchyshyn <vsenchyshyn@barefootnetworks.com>

### Description of PR
The timer accuracy test as it's written right now shows very random results. This is because it expects that PFC detection/restoration time is equal to pfc_wd_detect_time + pfc_wd_poll_time. In fact the worst case looks as follows:

wait time == pfc_wd_detect_time + pfc_wd_poll_time + delta1(time while "storm"/"restore" flag gets stored to REDIS) + delta2 (time while these flags are read from REDIS by orchdaemon) + delta3 (time when PFC WD storm detect/restore log appears in syslog). I don't know what the exact sum of this delta but on BFN paltform I see that it's usually in the range from 10-85ms for detect time and up to 150 ms for restore time.

So I added 150ms delta to wait time which should solve this. 

Summary:
Fixes # (issue)

### Type of change

- [] Bug fix
- [] Testbed and Framework(new/improvement)
- [*] Test case(new/improvement)

#### How did you do it?

Added 100 ms delta to PFC WD wait time in timer accuracy check.

### CODE REVIEW

**Comment by vsenchyshyn** [comment]
@wendani @neethajohn Please have a look

**Comment by vsenchyshyn** [comment]
@wendani @lguohan Could you pleas review this

**Comment by SavchukRomanLv** [comment]
@lguohan could you please merge this change? thanks

**Comment by SavchukRomanLv** [comment]
@daall could you please take a look? thanks

**Pull request closed without merging**
