### PR TITLE
[test_bgp_bbr] Fixed issue "ValueError: Circular reference detected" in case when test failed, removed unused dictionary which has had recursion

### PR DESCRIPTION
**Pull request by ppikh**
Fixed issue "ValueError: Circular reference detected" in case when test failed, removed unused dictionary which has had recursion

Signed-off-by: Petro Pikh <petrop@nvidia.com>

### Description of PR
In case when test failed - it raise "ValueError: Circular reference detected". Because we have line which creates recursion:
`vm_route['tor_route'] = vm_route`

Key 'tor_route' from dictionary 'vm_route' not used in other places and does not make sense.

Summary: Fixed issue "ValueError: Circular reference detected" in case when test failed
Fixes # (issue)

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911

#### What is the motivation for this PR?
In case when test failed - it raise "ValueError: Circular reference detected". Because we have line which creates recursion:
`vm_route['tor_route'] = vm_route`

#### How did you do it?
Removed unused part of code

#### How did you verify/test it?
Executed test case test_bgp_bbr.py

### CODE REVIEW

**Review by wangxin — APPROVED** [review]

**Review by liat-grozovik — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@ppikh  can you please resolve the conflict so we can merge?

**Review by liat-grozovik — APPROVED** [review]

**Comment by ppikh** [comment]
@liat-grozovik I fixed merge conflict. Please re-run tests(it failed but not related to my changes)

**Pull request merged**
