### PR TITLE
Revert "Snappi sample"

### PR DESCRIPTION
**Pull request by bingwang-ms**
Reverts Azure/sonic-mgmt#3653

This new script causes regression for almost all testbeds.
```
2021-07-11 07:00:31.791  
2021-07-11 07:00:31.791  ==================================== ERRORS ====================================
2021-07-11 07:00:31.791  _________________ ERROR collecting tests/snappi/test_snappi.py _________________
2021-07-11 07:00:31.792  ImportError while importing test module '/var/sonicbld/workspace/NewTests/TEMPLATE_PYTEST_T0_M4600C/tests/snappi/test_snappi.py'.
2021-07-11 07:00:31.792  Hint: make sure your test modules/packages have valid Python names.
2021-07-11 07:00:31.792  Traceback:
2021-07-11 07:00:31.792  snappi/test_snappi.py:7: in <module>
2021-07-11 07:00:31.792      from tests.common.snappi.snappi_fixtures import snappi_api_serv_ip, snappi_api_serv_port,\
2021-07-11 07:00:31.792  common/snappi/snappi_fixtures.py:5: in <module>
2021-07-11 07:00:31.792      import snappi
2021-07-11 07:00:31.792  E   ImportError: No module named snappi
```

### CODE REVIEW

**Comment by baiwei0427** [comment]
Snappi should have been included in the latest sonic mgmt docker (https://github.com/Azure/sonic-buildimage/blob/master/dockers/docker-sonic-mgmt/Dockerfile.j2#L45).

**Comment by wangxin** [comment]
Somehow, the sonic-mgmt docker used by nightly test does not include this package. We need to firstly unblock nightly testing by reverting this PR. Then we need to resolve the sonic-mgmt docker not up to date issue.

**Review by wangxin — APPROVED** [review]

**Comment by bingwang-ms** [comment]
> Snappi should have been included in the latest sonic mgmt docker (https://github.com/Azure/sonic-buildimage/blob/master/dockers/docker-sonic-mgmt/Dockerfile.j2#L45).

Thanks. Please reopen the original PR once the sonic-mgmt is updated.

**Comment by ANISH-GOTTAPU** [comment]
@wangxin & @bingwang-ms : I am not sure how to check the nightly test uses updated sonic-mgmt. Please let me know once it is updated, I will reopen the PR

**Pull request merged**
