### PR TITLE
add /etc/mlnx/msn2700 start/stop in syncd service

### PR DESCRIPTION
**Pull request by lguohan**

### CODE REVIEW

**Comment by marian-pritsak** [comment]
Is hw-management going to be used by syncd or some other docker?

**Comment by lguohan** [comment]
hw-management is not going to be used by syncd. The reason to add here is that sx-kernel stop will fail if we do not do msn2700 stop as drivers in hw-management depends on the drivers in sx-kernel.

**Comment by marian-pritsak** [comment]
Yes, but if it is going to be used by another entity, my concern is if we will have any troubles with synchronization between hw-management and its client

**Comment by lguohan** [comment]
agree with your concern, but I do not have any other solution.

**Comment by marian-pritsak** [comment]
Ok then
Anyway, if we'll have such a problem, systemd allows to put dependencies between cervices

**Comment by lguohan** [comment]
btw, I think the solution is to not to restart sx-kernel when you update the sdk, or make the hw-management not to depend on the sx-kernel. that requires some work on your side.

**Comment by marian-pritsak** [comment]
I'm afraid it is not possible
If we update sdk, sx-kernel is always restarted because it is simply another binary
And hw-management uses sx-core from sx-kernel as a backbone to talk to ASIC, It cannot be standalone

**Pull request merged**
