### PR TITLE
fix test_unknown_mac testcase failure in backend T0 topology

### LINKED ISSUE #4033: Analyze/fix pfc/test_unknown_mac.py failures
Failures seen on backend T0
Version: 20201231.15

### PR DESCRIPTION
**Pull request by yejianquan**
### Description of PR

Summary:
Fixes #4033
1. enhance test_unknown_mac testcase, fix failure in backend T0 topology, test sub interfaces instead of portchannels in backend topology.
2. code refine.
### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 201911

#### What is the motivation for this PR?
Fix test_unknown_mac testcase failure in backend T0 topology,
#### How did you do it?
test sub interfaces instead of portchannels in backend topology.
#### How did you verify/test it?
Run it again:
pfc/test_unknown_mac.py::TestUnknownMac::test_unknown_mac[dscp-3] PASSED [ 33%]
pfc/test_unknown_mac.py::TestUnknownMac::test_unknown_mac[dscp-4] PASSED [ 66%]
pfc/test_unknown_mac.py::TestUnknownMac::test_unknown_mac[dscp-8] PASSED [100%]

-------- generated xml file: /var/src/sonic-mgmt-int/tests/logs/tr.xml ---------
========================== 3 passed in 281.17 seconds ==========================

### CODE REVIEW

**Comment by yxieca** [comment]
LGTM, did you test it on both regular and backend topology?

**Comment by yejianquan** [comment]
> LGTM, did you test it on both regular and backend topology?

@yxieca 
Yes, tested on another nightly regular t0 testbed, passed

 pfc/test_unknown_mac.py::TestUnknownMac::test_unknown_mac[dscp-3] PASSED                                                                                    [ 33%]
pfc/test_unknown_mac.py::TestUnknownMac::test_unknown_mac[dscp-4] PASSED                                                                                    [ 66%]
pfc/test_unknown_mac.py::TestUnknownMac::test_unknown_mac[dscp-8] PASSED                                                                                    [100%]

**Comment by yejianquan** [comment]
Test result in vms20-t0-*******-1 testbed:
pfc/test_unknown_mac.py::TestUnknownMac::test_unknown_mac[dscp-3] PASSED                                                                                    [ 33%]
pfc/test_unknown_mac.py::TestUnknownMac::test_unknown_mac[dscp-4] PASSED                                                                                    [ 66%]
pfc/test_unknown_mac.py::TestUnknownMac::test_unknown_mac[dscp-8] PASSED                                                                                    [100%]

-------------------------------------------------- generated xml file: /var/src/sonic-mgmt-int/tests/logs/tr.xml --------------------------------------------------
=================================================================== 3 passed in 216.12 seconds ====================================================================

**Review by lolyu — APPROVED** [review]

**Pull request merged**
