### PR TITLE
Added CEOS role.

### PR DESCRIPTION
**Pull request by urvishpanchal**
### Description of PR

Fixes # (issue)

### Type of change
- [ ] Bug fix
- [*] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Approach
How did you do it?
How did you verify/test it?
Any platform specific information?
Supported testbed topology if it's a new test case?

### CODE REVIEW

**Comment by pavel-shirshov** [comment]
Is it possible to merge this functionality into veos role?
I see a lot of functions just a copy of veos role.

**Comment by urvishpanchal** [comment]
Hmm…Ill have to put a condition to check if it needs to start ceos or veos. Is that okay?

Thank you,
Urvish

**Comment by pavel-shirshov** [comment]
I think it's ok

**Comment by lguohan** [comment]
Need proper documentation on this cEOS in the testbed setup.

https://github.com/Azure/sonic-mgmt/blob/master/ansible/doc/README.testbed.Setup.md

what is cEOS, where to download cEOS?

**Comment by lguohan** [comment]
where does this switch1.xml.orig used? I cannot find reference to it in your PR.

**Comment by lguohan** [comment]
can we run link state propagator in cEOS? 

https://github.com/Azure/sonic-mgmt/tree/master/ansible/linkstate

**Comment by lguohan** [comment]
obseleted by #1443

**Pull request closed without merging**
