### PR TITLE
[dhcp_relay] DHCPv6 automatic test

### PR DESCRIPTION
**Pull request by shlomibitton**
### Description of PR

Summary:
DHCPv6 infrastructure and automatic test.

### Type of change

- [ ] Bug fix
- [x] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

#### What is the motivation for this PR?
Add DHCPv6 automatic test infrastructure and PTF test.

#### How did you do it?
Enhance the minigraph_facts.py and minigraph_dpg.j2 to support DHCPv6 instances.
Add DHCPv6 servers to lab.yml file.
This will deploy on a DUT DHCPv6 servers on regression run.
Develop a test with 3 test cases:
- test_dhcp_relay_default
- test_dhcp_relay_after_link_flap
- test_dhcp_relay_start_with_uplinks_down

Develop a PTF runner test to simulate the traffic according to the test case from sonic-mgmt.

#### How did you verify/test it?
- Use testbed-cli.sh to generate and deploy a minigraph with DHCPv6 instances on a switch.
- Run the test.
- This test depends on PR: https://github.com/Azure/sonic-buildimage/pull/7772

#### Supported testbed topology if it's a new test case?
T0

### CODE REVIEW

**Comment by shlomibitton** [comment]
Hey @wangxin, this test is dependent on Azure/sonic-buildimage#7772, it will now work until it is merged.

**Comment by wangxin** [comment]
@shlomibitton Can you fix the LGTM alerts `4 for Variable defined multiple times`?

**Comment by shlomibitton** [comment]
> @shlomibitton Can you fix the LGTM alerts `4 for Variable defined multiple times`?

Fixed

**Comment by tahmed-dev** [comment]
@kellyyeh, please review this PR.

**Review by kellyyeh — APPROVED** [review]
LGTM. Thanks for your work!

**Pull request merged**
