### PR TITLE
Revert "Revert "[inner hahsing] extension of PBH tests (#4848)" (#5282)"

### PR DESCRIPTION
**Pull request by AntonHryshchuk**
This reverts commit 3244df1482e009d855fe528beae460bbb266e72d.

### Description of PR

Summary: The fix for issue #5280 was provided in https://github.com/Azure/sonic-buildimage/pull/10184.
Revert back the changes, which reverted in https://github.com/Azure/sonic-mgmt/pull/5282

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [X] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012

#### What is the motivation for this PR?
Add back the changes

### CODE REVIEW

**Review by roysr-nv — APPROVED** [review]

**Comment by roysr-nv** [comment]
@wangxin  - can you please approve this change

**Review by wangxin — APPROVED** [review]

**Pull request merged**
