### PR TITLE
[sanity_check] Skip Monit's sanity check for `acms` process

### PR DESCRIPTION
**Pull request by yozhao101**
### Description of PR

Summary:
Fixes # (issue)

### Type of change

- [x ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [x ] 201911
- [ ] 202012

#### What is the motivation for this PR?
This PR aims to skip checking the service status of `acms|acms` monitored by Monit since `acms` process in ACMS container was not running in lab devices.

#### How did you do it?
Sanity check will skip the service status of `acms|acms` by checking the service name.

#### How did you verify/test it?
I manually verified this change on lab device `str-s6000-on-5`.

        01:27:08 checks._check_monit_on_dut L0589 INFO | Checking status of each Monit service...
        01:27:11 checks._check_monit_on_dut L0594 INFO | networking_uptime = 807 seconds, timeout = 0 seconds, interval = 20 seconds
        01:27:12 checks._check_monit_services_status L0276 INFO | service_name is: 'pmon|psud'
        01:27:12 checks._check_monit_services_status L0277 INFO | service_info is: '{'service_type': u'Program', 'service_status': u'Status ok'}'
        01:27:12 checks._check_monit_services_status L0276 INFO | service_name is: 'bgp|bgpmon'
        01:27:12 checks._check_monit_services_status L0277 INFO | service_info is: '{'service_type': u'Program', 'service_status': u'Status ok'}'
        01:27:12 checks._check_monit_services_status L0276 INFO | service_name is: 'swss|portsyncd'
        01:27:12 checks._check_monit_services_status L0277 INFO | service_info is: '{'service_type': u'Program', 'service_status': u'Status ok'}'
        01:27:12 checks._check_monit_services_status L0276 INFO | service_name is: 'swss|buffermgrd'
        01:27:12 checks._check_monit_services_status L0277 INFO | service_info is: '{'service_type': u'Program', 'service_status': u'Status ok'}'
        01:27:12 checks._check_monit_services_status L0276 INFO | service_name is: 'database|redis_server'
        01:27:12 checks._check_monit_services_status L0277 INFO | service_info is: '{'service_type': u'Program', 'service_status': u'Status ok'}'
        01:27:12 checks._check_monit_services_status L0276 INFO | service_name is: 'swss|vxlanmgrd'
        01:27:12 checks._check_monit_services_status L0277 INFO | service_info is: '{'service_type': u'Program', 'service_status': u'Status ok'}'
        01:27:12 checks._check_monit_services_status L0276 INFO | service_name is: 'teamd|teamsyncd'
        01:27:12 checks._check_monit_services_status L0277 INFO | service_info is: '{'service_type': u'Program', 'service_status': u'Status ok'}'
        01:27:12 checks._check_monit_services_status L0276 INFO | service_name is: 'lldp|lldpmgrd'
        01:27:12 checks._check_monit_services_status L0277 INFO | service_info is: '{'service_type': u'Program', 'service_status': u'Status ok'}'
        01:27:12 checks._check_monit_services_status L0276 INFO | service_name is: 'acms|CA_cert_downloader'
        01:27:12 checks._check_monit_services_status L0277 INFO | service_info is: '{'service_type': u'Program', 'service_status': u'Status ok'}'
        01:27:12 checks._check_monit_services_status L0276 INFO | service_name is: 'rsyslog'
        01:27:12 checks._check_monit_services_status L0277 INFO | service_info is: '{'service_type': u'Process', 'service_status': u'Running'}'
        01:27:12 checks._check_monit_services_status L0276 INFO | service_name is: 'acms|cert_converter'
        01:27:12 checks._check_monit_services_status L0277 INFO | service_info is: '{'service_type': u'Program', 'service_status': u'Status ok'}'
        01:27:12 checks._check_monit_services_status L0276 INFO | service_name is: 'acms|acms'
        01:27:12 checks._check_monit_services_status L0277 INFO | service_info is: '{'service_type': u'Program', 'service_status': u'Status failed'}'
        01:27:12 checks._check_monit_services_status L0276 INFO | service_name is: 'bgp|bgpcfgd'
        01:27:12 checks._check_monit_services_status L0277 INFO | service_info is: '{'service_type': u'Program', 'service_status': u'Status ok'}'
        01:27:12 checks._check_monit_services_status L0276 INFO | service_name is: 'pmon|thermalctld'
        01:27:12 checks._check_monit_services_status L0277 INFO | service_info is: '{'service_type': u'Program', 'service_status': u'Status ok'}'
        01:27:12 checks._check_monit_services_status L0276 INFO | service_name is: 'str-s6000-on-5'
        01:27:12 checks._check_monit_services_status L0277 INFO | service_info is: '{'service_type': u'System', 'service_status': u'Running'}'
        01:27:12 checks._check_monit_services_status L0276 INFO | service_name is: 'swss|vrfmgrd'
        01:27:12 checks._check_monit_services_status L0277 INFO | service_info is: '{'service_type': u'Program', 'service_status': u'Status ok'}'
        01:27:12 checks._check_monit_services_status L0276 INFO | service_name is: 'syncd|dsserve'
        01:27:12 checks._check_monit_services_status L0277 INFO | service_info is: '{'service_type': u'Program', 'service_status': u'Status ok'}'
        01:27:12 checks._check_monit_services_status L0276 INFO | service_name is: 'swss|neighsyncd'
        01:27:12 checks._check_monit_services_status L0277 INFO | service_info is: '{'service_type': u'Program', 'service_status': u'Status ok'}'
        01:27:12 checks._check_monit_services_status L0276 INFO | service_name is: 'bgp|fpmsyncd'
        01:27:12 checks._check_monit_services_status L0277 INFO | service_info is: '{'service_type': u'Program', 'service_status': u'Status ok'}'
        01:27:12 checks._check_monit_services_status L0276 INFO | service_name is: 'lldp|lldp_syncd'
        01:27:12 checks._check_monit_services_status L0277 INFO | service_info is: '{'service_type': u'Program', 'service_status': u'Status ok'}'
        01:27:12 checks._check_monit_services_status L0276 INFO | service_name is: 'vnetRouteCheck'
        01:27:12 checks._check_monit_services_status L0277 INFO | service_info is: '{'service_type': u'Program', 'service_status': u'Status ok'}'
        01:27:12 checks._check_monit_services_status L0276 INFO | service_name is: 'var-log'
        01:27:12 checks._check_monit_services_status L0277 INFO | service_info is: '{'service_type': u'Filesystem', 'service_status': u'Accessible'}'
        01:27:12 checks._check_monit_services_status L0276 INFO | service_name is: 'swss|vlanmgrd'
        01:27:12 checks._check_monit_services_status L0277 INFO | service_info is: '{'service_type': u'Program', 'service_status': u'Status ok'}'
        01:27:12 checks._check_monit_services_status L0276 INFO | service_name is: 'syncd|syncd'
        01:27:12 checks._check_monit_services_status L0277 INFO | service_info is: '{'service_type': u'Program', 'service_status': u'Status ok'}'
        01:27:12 checks._check_monit_services_status L0276 INFO | service_name is: 'bgp|bgpd'
        01:27:12 checks._check_monit_services_status L0277 INFO | service_info is: '{'service_type': u'Program', 'service_status': u'Status ok'}'
        01:27:12 checks._check_monit_services_status L0276 INFO | service_name is: 'bgp|zebra'
        01:27:12 checks._check_monit_services_status L0277 INFO | service_info is: '{'service_type': u'Program', 'service_status': u'Status ok'}'
        01:27:12 checks._check_monit_services_status L0276 INFO | service_name is: 'swss|intfmgrd'
        01:27:12 checks._check_monit_services_status L0277 INFO | service_info is: '{'service_type': u'Program', 'service_status': u'Status ok'}'
        01:27:12 checks._check_monit_services_status L0276 INFO | service_name is: 'lldp|lldpd_monitor'
        01:27:12 checks._check_monit_services_status L0277 INFO | service_info is: '{'service_type': u'Program', 'service_status': u'Status ok'}'
        01:27:12 checks._check_monit_services_status L0276 INFO | service_name is: 'swss|portmgrd'
        01:27:12 checks._check_monit_services_status L0277 INFO | service_info is: '{'service_type': u'Program', 'service_status': u'Status ok'}'
        01:27:12 checks._check_monit_services_status L0276 INFO | service_name is: 'pmon|sensord'
        01:27:12 checks._check_monit_services_status L0277 INFO | service_info is: '{'service_type': u'Program', 'service_status': u'Status ok'}'
        01:27:12 checks._check_monit_services_status L0276 INFO | service_name is: 'snmp|snmp_subagent'
        01:27:12 checks._check_monit_services_status L0277 INFO | service_info is: '{'service_type': u'Program', 'service_status': u'Status ok'}'
        01:27:12 checks._check_monit_services_status L0276 INFO | service_name is: 'snmp|snmpd'
        01:27:12 checks._check_monit_services_status L0277 INFO | service_info is: '{'service_type': u'Program', 'service_status': u'Status ok'}'
        01:27:12 checks._check_monit_services_status L0276 INFO | service_name is: 'diskCheck'
        01:27:12 checks._check_monit_services_status L0277 INFO | service_info is: '{'service_type': u'Program', 'service_status': u'Status ok'}'
        01:27:12 checks._check_monit_services_status L0276 INFO | service_name is: 'container_memory_telemetry'
        01:27:12 checks._check_monit_services_status L0277 INFO | service_info is: '{'service_type': u'Program', 'service_status': u'Status ok'}'
        01:27:12 checks._check_monit_services_status L0276 INFO | service_name is: 'pmon|xcvrd'
        01:27:12 checks._check_monit_services_status L0277 INFO | service_info is: '{'service_type': u'Program', 'service_status': u'Status ok'}'
        01:27:12 checks._check_monit_services_status L0276 INFO | service_name is: 'swss|orchagent'
        01:27:12 checks._check_monit_services_status L0277 INFO | service_info is: '{'service_type': u'Program', 'service_status': u'Status ok'}'
        01:27:12 checks._check_monit_services_status L0276 INFO | service_name is: 'telemetry|telemetry'
        01:27:12 checks._check_monit_services_status L0277 INFO | service_info is: '{'service_type': u'Program', 'service_status': u'Status ok'}'
        01:27:12 checks._check_monit_services_status L0276 INFO | service_name is: 'pmon|syseepromd'
        01:27:12 checks._check_monit_services_status L0277 INFO | service_info is: '{'service_type': u'Program', 'service_status': u'Status ok'}'
        01:27:12 checks._check_monit_services_status L0276 INFO | service_name is: 'radv|radvd'
        01:27:12 checks._check_monit_services_status L0277 INFO | service_info is: '{'service_type': u'Program', 'service_status': u'Status ok'}'
        01:27:12 checks._check_monit_services_status L0276 INFO | service_name is: 'swss|nbrmgrd'
        01:27:12 checks._check_monit_services_status L0277 INFO | service_info is: '{'service_type': u'Program', 'service_status': u'Status ok'}'
        01:27:12 checks._check_monit_services_status L0276 INFO | service_name is: 'root-overlay'
        01:27:12 checks._check_monit_services_status L0277 INFO | service_info is: '{'service_type': u'Filesystem', 'service_status': u'Accessible'}'
        01:27:12 checks._check_monit_services_status L0276 INFO | service_name is: 'dhcp_relay|dhcrelay_Vlan1000'
        01:27:12 checks._check_monit_services_status L0277 INFO | service_info is: '{'service_type': u'Program', 'service_status': u'Status ok'}'
        01:27:12 checks._check_monit_services_status L0276 INFO | service_name is: 'telemetry|dialout_client'
        01:27:12 checks._check_monit_services_status L0277 INFO | service_info is: '{'service_type': u'Program', 'service_status': u'Status ok'}'
        01:27:12 checks._check_monit_services_status L0276 INFO | service_name is: 'bgp|staticd'
        01:27:12 checks._check_monit_services_status L0277 INFO | service_info is: '{'service_type': u'Program', 'service_status': u'Status ok'}'
        01:27:12 checks._check_monit_services_status L0276 INFO | service_name is: 'teamd|teammgrd'
        01:27:12 checks._check_monit_services_status L0277 INFO | service_info is: '{'service_type': u'Program', 'service_status': u'Status ok'}'
        01:27:12 checks._check_monit_services_status L0276 INFO | service_name is: 'routeCheck'
        01:27:12 checks._check_monit_services_status L0277 INFO | service_info is: '{'service_type': u'Program', 'service_status': u'Status ok'}'
        01:27:12 checks._check_monit_on_dut L0636 INFO | Checking status of each Monit service was done on str-s6000-on-5

### CODE REVIEW

**Review by StormLiangMS — APPROVED** [review]
LGTM

**Comment by sumukhatv** [comment]
I think this change should not be in the public repo.

**Comment by yozhao101** [comment]
> I think this change should not be in the public repo.

Yeah, I will create an PR for internal repo.

**Comment by yozhao101** [comment]
Close this PR since another internal PR is submitted for review.

**Pull request closed without merging**
