### PR TITLE
[dualtor][orchagent] Add mac move testcases

### LINKED ISSUE #3276: Orchagent FDB/MAC Move Test Cases
Neighbor within subnet learnt on an active mux port; Note: This new neighbor must not be one configured for Server IPs in MUX_CABLE | Active Forwarding | Verify no tunnel traffic. All traffic to server should be directly forwarded; Verify CRM for neighbor
-- | -- | --
Simulate MAC move by sending same ARP req/reply from another port which is standby | Standby Forwarding | Verify that traffic to this neighbor is now forwarded to Active ToR via tunnel nexthop
Simulate FDB ageout/flush on this mac | Standby Forwarding | Verify that tunnel traffic is not impacted by fdb del event
Simulate MAC move by sending same ARP req/reply from another port which is active | Active Forwarding | Verify that traffic to this neighbor is now forwarded directly and no tunnel traffic
Simulate FDB ageout/flush on this mac | Active Dropping | Verify that traffic to this neighbor is now dropped

### PR DESCRIPTION
**Pull request by lolyu**
### Description of PR

Summary:
Fixes #3276

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

#### What is the motivation for this PR?
Verify those mac move scenarios:
1. if a new neighbor(in the VLAN subnet) is learned on an active port, the traffic to the new neighbor will be directly forwarded to the neighbor.
2. if the mac moves from an active port to another standby port, verify the traffic is directed back to T1s to the active ToR.
3. if the mac moves back to another active port, verify the traffic is directly forwarded.

Signed-off-by: Longxiang Lyu <lolv@microsoft.com>

#### How did you do it?
Add:
1. `test_mac_move.py::test_mac_move`

#### How did you verify/test it?
```
dualtor/test_mac_move.py::test_mac_move PASSED                                                                                                                                                 [100%]

===================================================================================== 1 passed in 79.14 seconds ======================================================================================
```

### CODE REVIEW

**Comment by theasianpianist** [comment]
As per the test plan, I believe these two test cases should be combined into one case - we also want to test the transition between standby and active, and back to standby to make sure the traffic goes to the tunnel/neighbor/tunnel accordingly.

**Review by theasianpianist — CHANGES_REQUESTED** [review]
As per the test plan, I believe these two test cases should be combined into one case - we also want to test the transition between standby and active, and back to standby to make sure the traffic goes to the tunnel/neighbor/tunnel accordingly.

**Comment by lolyu** [comment]
> As per the test plan, I believe these two test cases should be combined into one case - we also want to test the transition between standby and active, and back to standby to make sure the traffic goes to the tunnel/neighbor/tunnel accordingly.

@prsunny, could you please provide some of your thoughts here about how to organize those mac move testcases?

**Comment by prsunny** [comment]
> > As per the test plan, I believe these two test cases should be combined into one case - we also want to test the transition between standby and active, and back to standby to make sure the traffic goes to the tunnel/neighbor/tunnel accordingly.
> 
> @prsunny, could you please provide some of your thoughts here about how to organize those mac move testcases?

Thats right. The test is expected as a sequence of operation to perform mac-move and verify. It is better to have it combined in one case. If we have it separated, then maintaining mac-move sequence would be harder. I believe, it will make the test simple as well.

**Comment by lolyu** [comment]
@theasianpianist, updated, could you pls take another review?

**Comment by theasianpianist** [comment]
I don't see the 'Simulate FDB ageout/flush' steps from the test plan, am I missing something?

**Comment by lolyu** [comment]
> I don't see the 'Simulate FDB ageout/flush' steps from the test plan, am I missing something?

Those are two test cases, fdb flush and mac move.

**Comment by lolyu** [comment]
> I don't see the 'Simulate FDB ageout/flush' steps from the test plan, am I missing something?

FDB will learn from heartbeats immediately after FDB flush/ageout, and stopping the `icmp_responder` will leave the ToRs in an unexpected state, discussed with @prsunny , let's leave those steps in `TODO`s.

**Comment by prsunny** [comment]
> > I don't see the 'Simulate FDB ageout/flush' steps from the test plan, am I missing something?
> 
> FDB will learn from heartbeats immediately after FDB flush/ageout, and stopping the `icmp_responder` will leave the ToRs in an unexpected state, discussed with @prsunny , let's leave those steps in `TODO`s.

Agree with @lolyu that we cannot stop icmp responder. But discussed another method to use a different mac than the interface mac so that it won't get relearnt after fdbflush. @lolyu is trying out the change.

**Comment by lolyu** [comment]
```
dualtor/test_orchagent_mac_move.py::test_mac_move PASSED                                                                                                                                       [100%]

===================================================================================== 1 passed in 106.50 seconds =====================================================================================
```

**Review by prsunny — APPROVED** [review]

**Comment by theasianpianist** [comment]
If I understand the test plan, the FDB ageout step should be part of this one big test case. I believe the steps should be:

1. Learn neighbor on active port
2. MAC move to standby port
3. FDB ageout/flush, confirm no changes to standby forwarding
4. MAC move event to active port
5. FDB ageout/flush, confirm packets are dropped

@prsunny can you confirm if this is the correct flow for the test case?

**Review by theasianpianist — APPROVED** [review]
lgtm!

**Comment by lolyu** [comment]
Thank you!

**Pull request merged**
