### PR TITLE
[MgmtVrf ]: fix for  Host Unreachable' error

### LINKED ISSUE #1615: Mgmtvrf test fails with 'Host Unreachable' error
**Description**

test_mgmtvrf.py fails on setup_mvrf() function when tries to execute:
localhost.wait_for(host=var['dut_ip'], port=22, state='started', search_regex=SONIC_SSH_REGEX, timeout=90)

NOTE: mgmt vrf becomes enabled after this function execution. 

When ignoring the wait_for() function on setup_mvrf() function, the test fails on test_service_acl() test case - also on wait_for() function.
 
**Steps to reproduce the issue:**
1. Execute test_mgmtvrf.py
2. Test fails on wait_for() function saying 'Host Unreachable'. 

**Describe the results you received:**
'Host Unreachable'. 

**Describe the results you expected:**
Test should pass.

### PR DESCRIPTION
**Pull request by chitra-raghavan**
Summary:
Fixes #1615 

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

#### How did you do it?
Removed the wait_for after adding mgmt vrf. 

#### How did you verify/test it?
Tested by running in S5232 testbed. 

#### Logs 

py.test --inventory=../ansible/lab --host-pattern=sonic-s5232-01 --module-path ../ansible/library/ --testbed=vms-t0-56 --testbed_file=../ansible/testbed.csv test_mgmtvrf.py  --log-level=DEBUG --log-file mvrf-debug.log  --disable_loganalyzer -rab  -vvv
============================= test session starts ==============================
platform linux2 -- Python 2.7.12, pytest-4.6.5, py-1.8.0, pluggy-0.13.1 -- /usr/bin/python
cachedir: .pytest_cache
ansible: 2.8.7
rootdir: /var/johnar/sonic-mgmt/tests, inifile: pytest.ini
plugins: xdist-1.28.0, repeat-0.8.0, forked-1.1.3, ansible-2.2.2
collecting ... collected 10 items

test_mgmtvrf.py::TestMvrfInbound::test_ping PASSED                       [ 10%]
test_mgmtvrf.py::TestMvrfInbound::test_snmp_fact PASSED                  [ 20%]
test_mgmtvrf.py::TestMvrfOutbound::test_ping PASSED                      [ 30%]
test_mgmtvrf.py::TestMvrfOutbound::test_wget PASSED                      [ 40%]
test_mgmtvrf.py::TestMvrfOutbound::test_curl PASSED                      [ 50%]
test_mgmtvrf.py::TestServices::test_ntp PASSED                           [ 60%]
test_mgmtvrf.py::TestServices::test_service_acl PASSED                   [ 70%]
test_mgmtvrf.py::TestReboot::test_warmboot PASSED                        [ 80%]
test_mgmtvrf.py::TestReboot::test_reboot PASSED                          [ 90%]
test_mgmtvrf.py::TestReboot::test_fastboot PASSED                        [100%]

========================= 10 passed in 1549.91 seconds =========================
Triggering a new build of write_to_csv
Finished: SUCCESS

### CODE REVIEW

**Comment by chitra-raghavan** [comment]
retest this please

**Comment by daall** [comment]
retest vsimage please

**Comment by chitra-raghavan** [comment]
retest vsimage please

**Comment by chitra-raghavan** [comment]
retest vsimage please

**Comment by irene-pan1202** [comment]
@chitra-raghavan 
Solution is removed the wait_for after adding mgmt vrf. Why need to add the wait_for SSH stop after deleting mgmt vrf?
Because after deleting mgmt vrf, some models only need 1 second to disconnect, adding this confirmation seems to cause the test timeout. Thanks.

**Pull request merged**
