### PR TITLE
[fib]: Fixed FIB V4/V6: aligned facts generator

### LINKED ISSUE #1089: template syntax error in FIB test caused by PR #1063
**Description**
syntax error in template file ansible/roles/test/templates/fib.j2 caused by #1063 

**Steps to reproduce the issue:**
1.run fib test and see error on simple-fib case about template:

<10.5.208.134> SSH: EXEC sshpass -d15 ssh -C -vvv -o ControlMaster=auto -o ControlPersist=120s -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o User=root -o ConnectTimeout=10 -o ControlPath=/var/azure/.ansible/cp/ansible-ssh-%h-%p-%r -tt 10.5.208.134 'mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1567427321.27-60214546390966 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1567427321.27-60214546390966 )"'
fatal: [et6448m-M0 -> 10.5.208.134]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"dest": "/root/fib_info.txt", "src": "roles/test/templates/fib.j2"}, "module_name": "template"}, "msg": "AnsibleError: ERROR! template error while templating string: Encountered unknown tag 'elif'. You probably made a nesting mistake. Jinja is expecting this tag, but currently looking for 'endfor' or 'else'. The innermost block that needs to be closed is 'for'."}

2.also even after fixing the syntax error (missing endfor tag) ptf test is failing with indexError exception

### PR DESCRIPTION
**Pull request by nazariig**
Signed-off-by: Nazarii Hnydyn <nazariig@mellanox.com>

### Description of PR
Fixed FIB V4/V6: aligned facts generator (fixes #1089)

### Type of change

- [X] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

#### How did you do it?
* Fixed roles/test/templates/fib.j2

#### How did you verify/test it?
* Tested on t0/t1/t1-lag

#### Any platform specific information?
* N/A

#### Supported testbed topology if it's a new test case?
* N/A

### Documentation
* N/A

### CODE REVIEW

**Comment by nazariig** [comment]
@avi-milner this fixes #1089

**Comment by liat-grozovik** [comment]
@nazariig do you know what was the PR who cause that break?

**Comment by nazariig** [comment]
@liat-grozovik yes. This was mentioned in ticket: #1089

**Comment by DhinakaranDayalan** [comment]
Hi,

I tired the fix and its not resolving this issue

**Comment by nazariig** [comment]
> 
> 
> Hi,
> 
> I tired the fix and its not resolving this issue

@DhinakaranDayalan please open a bug and attach all the relevant info.
BTW. Which topo are you using? The FIB v4/v6 tests are passing on t0/ta-lag.

**Pull request merged**
