### PR TITLE
[ test_autonegotiation ] Added missing topology mark

### PR DESCRIPTION
**Pull request by SavchukRomanLv**
Signed-off-by: Roman Savchuk <romanx.savchuk@intel.com>

### Description of PR

Summary:
Fixes # (issue)

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911

#### What is the motivation for this PR?
TC skipped when run with --topology mark
`is skipped when no topology marker is given`
#### How did you do it?
Run TC with --topology=any, TC was not skipped

### CODE REVIEW

**Review by yxieca — APPROVED** [review]

**Comment by SavchukRomanLv** [comment]
@jleveque can you please check?

**Comment by bingwang-ms** [comment]
Hi @SavchukRomanLv, the test seems to be failing at most platforms.
```ValueError('sample larger than population',)
Traceback (most recent call last):
  File "/azp/agent/_work/8/s/tests/common/plugins/log_section_start/__init__.py", line 73, in _fixture_generator_decorator
    res = next(it)
  File "/azp/agent/_work/8/s/tests/platform_tests/test_auto_negotiation.py", line 62, in recover_ports
    cadidate_test_ports[duthost] = random.sample(all_ports, 3)
  File "/usr/lib/python2.7/random.py", line 325, in sample
    raise ValueError("sample larger than population")
ValueError: sample larger than population
```
Can you help take a look? Thanks

**Comment by SavchukRomanLv** [comment]
@bingwang-ms this issue fixed in [4055](https://github.com/Azure/sonic-mgmt/pull/4055)

**Pull request merged**
