### PR TITLE
Skip ecmp test scripts on Mellanox 2700 platform

### PR DESCRIPTION
**Pull request by ZhaohuiS**
Signed-off-by: Zhaohui Sun <zhaohuisun@microsoft.com>

### Description of PR

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012

#### What is the motivation for this PR?
Skip ecmp test scripts on Mellanox 2700 platform
#### How did you do it?
Add it in tests_mark_conditions.yml

#### How did you verify/test it?
Run ecmp test scripts on Mellanox  2700 testbed.

#### Any platform specific information?
Mellanox 2700

### CODE REVIEW

**Review by StormLiangMS — COMMENTED** [review]
@ZhaohuiS could you elaborate what's the reason we skip inner hash on 2700?

**Review by anish-n — DISMISSED** [review]

**Comment by yutongzhang-microsoft** [comment]
Please keep the test case name in alphabetic order.

**Comment by ZhaohuiS** [comment]
> @ZhaohuiS could you elaborate what's the reason we skip inner hash on 2700?

@StormLiangMS That ASIC version does not support PBH, Fine Grained ECMP should work with it though. I removed test_fgnhg.py for 2700 platform in my PR.

**Comment by ZhaohuiS** [comment]
> Please keep the test case name in alphabetic order.

@yutongzhang-microsoft Of course, I think the order is correct.

**Review by StormLiangMS — APPROVED** [review]
LGTM

**Pull request merged**
