### PR TITLE
[drop_counters][scapy] align code to new scapy version 2.4.5

### PR DESCRIPTION
**Pull request by nhe-NV**
Following methods have been changed in scapy version 2.4.5
1. The igmpize() is changed in IGMP
2. Can not create IP layer with specifying ip_dst to b ""

### Description of PR

Summary: Some methods have changed due to scapy version is changed to 2.4.5
Fixes # (issue) Use correct method to create igmp pkt and ip pky with absent ip_dst

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911

#### What is the motivation for this PR?
Some methods have changed due to the scapy version is changed to 2.4.5, change script to call the method in correct way

#### How did you do it?
1. Change the ip_dst from "" to None when create the IP layer
2. Change igmp_layer.igmpize(ip=ip_layer, ether=eth_layer) to igmp_layer.igmpize()

#### How did you verify/test it?
Run the test_non_routable_igmp_pkts and test_dst_ip_absent, and tests can pass

#### Any platform specific information?
No

### CODE REVIEW

**Comment by wangxin** [comment]
@nhe-NV, is this change compatible with previous scapy version?

**Comment by nhe-NV** [comment]
> 



> @nhe-NV, is this change compatible with previous scapy version?

@wangxin no, the igmpize method is not same for the scapy 2.4.5 and the previous version(such as 2.2.0.dev0), in the latest sonic-mgmt docker, we have upgraded the scapy to 2.4.5, do we also need to run the test in sonic-mgmt docker with old scapy version

**Comment by wangxin** [comment]
> > 
> 
> > @nhe-NV, is this change compatible with previous scapy version?
> 
> @wangxin no, the igmpize method is not same for the scapy 2.4.5 and the previous version(such as 2.2.0.dev0), in the latest sonic-mgmt docker, we have upgraded the scapy to 2.4.5, do we also need to run the test in sonic-mgmt docker with old scapy version

If it is incompatible with previous version, then for people stick with old sonic-mgmt docker, the test would fail. Can you add some logic using tools like `hasattr` to maintain backward compability?

**Review by liat-grozovik — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@yxieca FYI. not sure if there are other tests that are impacted due to new scapy version.

**Comment by liat-grozovik** [comment]
@nhe-NV could you pls follow up on the latest comment?

**Comment by yxieca** [comment]
@wangxin please point to an example of your recent change dealing with this issue.

**Comment by nhe-NV** [comment]
> 

Hi, @wangxin 

I submit the change to make it compatible with previous scapy version

**Review by liat-grozovik — APPROVED** [review]

**Review by wangxin — APPROVED** [review]

**Pull request merged**
