### PR TITLE
Updated External PortChannel Name Convention in minigraph template.

### PR DESCRIPTION
**Pull request by abdosi**
What I did:
Changes done in PR : https://github.com/Azure/sonic-mgmt/pull/4763  conflicted External portChannel name used  by t0-56-po2vlan topology. To fix this moving External port-channel from PortChannel10xx to PortChannel20xx

How I verify:
Manual Verification.

### CODE REVIEW

**Review by ganglyu — APPROVED** [review]

**Comment by AndriiLozovyi** [comment]
@abdosi,
These changes might impact NAT and Vrf test cases due to change of PortChannel naming template. 
Maybe better solution would be to change PortChannel naming in the topo file of  t0-56-po2vlan ?

**Comment by abdosi** [comment]
> @abdosi, These changes might impact NAT and Vrf test cases due to change of PortChannel naming template. Maybe better solution would be to change PortChannel naming in the topo file of t0-56-po2vlan ?

@ganglyu can you check this comment ? Is it possible to change  t0-56-po2vlan to use other port-channel name. I don't see any dependency that should prevent changing it.

**Comment by qiluo-msft** [comment]
@AndriiLozovyi Could you point us the code lines of "impact NAT and Vrf test cases due to change of PortChannel naming template"?
We may need to change the lines in this PR.

**Comment by ganglyu** [comment]
> > @abdosi, These changes might impact NAT and Vrf test cases due to change of PortChannel naming template. Maybe better solution would be to change PortChannel naming in the topo file of t0-56-po2vlan ?
> 
> @ganglyu can you check this comment ? Is it possible to change t0-56-po2vlan to use other port-channel name. I don't see any dependency that should prevent changing it.

I'm ok for both solutions.

**Comment by AndriiLozovyi** [comment]
@qiluo-msft,
Below is 2 PRs with changes for Vrf and NAT test suite due to PR - [4763](https://github.com/Azure/sonic-mgmt/pull/4763)
[5170](https://github.com/Azure/sonic-mgmt/pull/5170)
[5151](https://github.com/Azure/sonic-mgmt/pull/5151)

**Pull request closed without merging**
