### PR TITLE
T2 topology for a VoQ chassis with 2 multi-asic linecards and a supervisor card

### PR DESCRIPTION
**Pull request by sanmalho-git**
### Description of PR

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [x] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911

#### What is the motivation for this PR?
The current T2 topology proposed in OC was with 3 single asic linecards. 1 lincard connected
to T3 VM's and the other two connected to T1 VM's. The same routes are advertised across the T1 VM's
to the 2 linecards. This allows for ECMP coverage across fabric in a VoQ Chassis.

We now have multi-asic linecards, and the above ECMP coverage can be accomplished with 2 multi-asic linecards.
So adding this topology for a VoQ Chassis with 2 multi-asic linecards and a supervisor card.
#### How did you do it?
Adding a new topology file in which we have:
- 3 DUTs - 2 linecards (dut 0, 1) and 1 Supervisor card (dut 2). Each linecard has 2 asics (asic0 and asic1) and each asic has 18 ports
    - asic0 on linecard dut0 connected to 13 T3 VMs - 5 are on 2 port lag and 8 on a single routed port
    - asic1 on linecard dut0 connected to 13 T3 VMs - 5 are on 2 port lag and 8 on a single routed port
    - asic0 on linecard dut1 connected to 13 T1 VMs- 5 are on 2 port lag and 8 on a single routed port
    - asic1 on linecard dut1 connected to 13 T1 VMs - 5 are on 2 port lag and 8 on a single routed port
- ptf ports are numbered 0-71

### CODE REVIEW

**Comment by sanmalho-git** [comment]
@judyjoseph @abdosi  This is the topology file for a VoQ chassis with 2 multi-asic linecards with all its front-panel ports connected. Please review.

**Comment by judyjoseph** [comment]
Looks ok, few comments 

1. There are no T1's with vips in this new topology_t2 file. I see it used in bgp/test_bgp_multipath_relax.py which currently is marked only for t1, so wondering if it is really needed. In the existing t2_topo.yml there are a few T1 VM's with Vips

2. Do we need 400g in the name of the topology file ? It could be used with any multi-asic LC ?

**Comment by judyjoseph** [comment]
In addition, could you add the other topology with minimal set of interfaces "t2_chassis1_min" shared earlier in this PR or as a separate PR ?

**Comment by sanmalho-git** [comment]
@judyjoseph Have addressed your review comments
 
  - Added vips to 4 T1 VM's
      - 2 on each asic - 1 on LAG VM, and 1 on routed VM
  - Removed 400g from the t2 topology filename
  - Added T2 topology file with 3 ports per asic
       - 1 eBGP VM on a 2 port LAG
       - 1 eBGP on routed interface

Please re-review

**Comment by judyjoseph** [comment]
@arlakshm @abdosi, could you review the PR as well.

**Review by judyjoseph — APPROVED** [review]

**Pull request merged**
