### PR TITLE
[dualtor][orchagent] Add active ToR neighbor testcase

### PR DESCRIPTION
**Pull request by lolyu**
### Description of PR

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

#### What is the motivation for this PR?
Test that with neighbor entry, the traffic to the server is passed directly, without neighbor entry, the traffic is dropped.

#### How did you do it?
1. add testcase `test_active_tor_remove_neighbor_downstream_active`
2. put shared code from `test_standby_tor_remove_neighbor_downstream_standby`  to common modules.

### CODE REVIEW

**Comment by lolyu** [comment]
```
dualtor/test_orchagent_active_tor_downstream.py::test_active_tor_remove_neighbor_downstream_active PASSED                                                                                      [100%]
dualtor/test_orchagent_standby_tor_downstream.py::test_standby_tor_remove_neighbor_downstream_standby PASSED                                                                                   [100%]
dualtor/test_ipinip.py::test_decap_active_tor PASSED                                                                                                                                           [100%]
dualtor/test_ipinip.py::test_decap_standby_tor FAILED                                                                                                                                          [100%]
```
`test_ipinip.py::test_decap_standby_tor` failed due to the standby directs the tunnel traffic back to T1s.

**Comment by theasianpianist** [comment]
@prsunny I thought that the standby re-encap issue had been resolved, can you confirm?

**Review by theasianpianist — APPROVED** [review]

**Comment by prsunny** [comment]
> @prsunny I thought that the standby re-encap issue had been resolved, can you confirm?

Yes @theasianpianist. Its resolved in latest SAI. Please check/confirm two things:

1. Image version of DUT
2. Source IP of the outer packet. It should match the peer switch IP.

**Comment by theasianpianist** [comment]
@lolyu as per Prince's comment, can you re-run `test_decap_standby_tor` on a DUT with the latest internal 202012 image?

**Comment by lolyu** [comment]
@theasianpianist, the result in the previous comment is from tests on dualtor3 testbed. Yes, sure, I will track this issue.

**Pull request merged**
