### PR TITLE
Add 'testbed-cli.sh announce-routes'

### PR DESCRIPTION
**Pull request by wangxin**
### Description of PR

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [x] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

#### What is the motivation for this PR?
In PR #2741, test script for announcing IP routes to PTF docker container was deprecated.
The function of announcing IP routes is moved to 'testbed-cli.sh add-topo'. Then we do
not need to run the test script to announce IP routes after a new topology is deployed.

However, there are still occasions that people may want to re-announce the IP routes to
PTF docker containers. Because announcing routes is part of add-topo, then the only
possible way to re-announce routes is to run 'testbed-cli.sh remove-topo' and
'testbed-cli.sh add-topo'. This is inconvenient and time consuming.

#### How did you do it?
This change added a new 'announce-routes' sub-command to the testbed-cli.sh tool.
We can now just re-announce IP routes using command like below:
    ./testbed-cli.sh -t vtestbed.csv vms-kvm-t0 password.txt

Other changes:
* Corrected the inv_name field in vtestbed.csv file.
* Moved the 'announce_routes.py' module from ansible/roles/vm_set/library to ansible/library

#### How did you verify/test it?
```
johnar@2c14d1ecff9a:~/code/sonic-mgmt/ansible$ ./testbed-cli.sh -t vtestbed.csv announce-routes vms-kvm-t0 password.txt 
Announce routes 'vms-kvm-t0'
reading
Found topology vms-kvm-t0

PLAY [servers:&vm_host] *********************************************************************************************************

TASK [Check that variable vm_set_name is defined] *******************************************************************************
Thursday 11 March 2021  06:21:46 +0000 (0:00:00.160)       0:00:00.160 ******** 
skipping: [STR-ACS-VSERV-01]

TASK [Check that variable topo is defined] **************************************************************************************
Thursday 11 March 2021  06:21:46 +0000 (0:00:00.026)       0:00:00.187 ******** 
skipping: [STR-ACS-VSERV-01]

TASK [Check if it is a known topology] ******************************************************************************************
Thursday 11 March 2021  06:21:46 +0000 (0:00:00.027)       0:00:00.215 ******** 
skipping: [STR-ACS-VSERV-01]

TASK [Check that variable ptf_ip is defined] ************************************************************************************
Thursday 11 March 2021  06:21:46 +0000 (0:00:00.023)       0:00:00.238 ******** 
skipping: [STR-ACS-VSERV-01]

TASK [Load topo variables] ******************************************************************************************************
Thursday 11 March 2021  06:21:46 +0000 (0:00:00.024)       0:00:00.263 ******** 
ok: [STR-ACS-VSERV-01]

TASK [include_tasks] ************************************************************************************************************
Thursday 11 March 2021  06:21:46 +0000 (0:00:00.056)       0:00:00.319 ******** 
included: /var/johnar/code/sonic-mgmt/ansible/roles/vm_set/tasks/announce_routes.yml for STR-ACS-VSERV-01

TASK [Include variables for PTF containers] *************************************************************************************
Thursday 11 March 2021  06:21:46 +0000 (0:00:00.044)       0:00:00.363 ******** 
ok: [STR-ACS-VSERV-01]

TASK [Set ptf host] *************************************************************************************************************
Thursday 11 March 2021  06:21:46 +0000 (0:00:00.031)       0:00:00.394 ******** 
ok: [STR-ACS-VSERV-01]

TASK [Add ptf host] *************************************************************************************************************
Thursday 11 March 2021  06:21:47 +0000 (0:00:00.044)       0:00:00.439 ******** 
changed: [STR-ACS-VSERV-01]

TASK [Set facts] ****************************************************************************************************************
Thursday 11 March 2021  06:21:47 +0000 (0:00:00.044)       0:00:00.484 ******** 
ok: [STR-ACS-VSERV-01]

TASK [Start exabgp processes for IPv4 on PTF] ***********************************************************************************
Thursday 11 March 2021  06:21:47 +0000 (0:00:00.056)       0:00:00.541 ******** 
changed: [STR-ACS-VSERV-01 -> None] => (item={'key': u'ARISTA04T1', 'value': {u'vm_offset': 3, u'vlans': [31]}})
changed: [STR-ACS-VSERV-01 -> None] => (item={'key': u'ARISTA03T1', 'value': {u'vm_offset': 2, u'vlans': [30]}})
changed: [STR-ACS-VSERV-01 -> None] => (item={'key': u'ARISTA02T1', 'value': {u'vm_offset': 1, u'vlans': [29]}})
changed: [STR-ACS-VSERV-01 -> None] => (item={'key': u'ARISTA01T1', 'value': {u'vm_offset': 0, u'vlans': [28]}})

TASK [Start exabgp processes for IPv6 on PTF] ***********************************************************************************
Thursday 11 March 2021  06:21:48 +0000 (0:00:01.357)       0:00:01.898 ******** 
changed: [STR-ACS-VSERV-01 -> None] => (item={'key': u'ARISTA04T1', 'value': {u'vm_offset': 3, u'vlans': [31]}})
changed: [STR-ACS-VSERV-01 -> None] => (item={'key': u'ARISTA03T1', 'value': {u'vm_offset': 2, u'vlans': [30]}})
changed: [STR-ACS-VSERV-01 -> None] => (item={'key': u'ARISTA02T1', 'value': {u'vm_offset': 1, u'vlans': [29]}})
changed: [STR-ACS-VSERV-01 -> None] => (item={'key': u'ARISTA01T1', 'value': {u'vm_offset': 0, u'vlans': [28]}})

TASK [Verify that exabgp processes for IPv4 are started] ************************************************************************
Thursday 11 March 2021  06:21:49 +0000 (0:00:01.466)       0:00:03.365 ******** 
ok: [STR-ACS-VSERV-01 -> localhost] => (item={'key': u'ARISTA04T1', 'value': {u'vm_offset': 3, u'vlans': [31]}})
ok: [STR-ACS-VSERV-01 -> localhost] => (item={'key': u'ARISTA03T1', 'value': {u'vm_offset': 2, u'vlans': [30]}})
ok: [STR-ACS-VSERV-01 -> localhost] => (item={'key': u'ARISTA02T1', 'value': {u'vm_offset': 1, u'vlans': [29]}})
ok: [STR-ACS-VSERV-01 -> localhost] => (item={'key': u'ARISTA01T1', 'value': {u'vm_offset': 0, u'vlans': [28]}})

TASK [Verify that exabgp processes for IPv6 are started] ************************************************************************
Thursday 11 March 2021  06:21:51 +0000 (0:00:01.305)       0:00:04.671 ******** 
ok: [STR-ACS-VSERV-01 -> localhost] => (item={'key': u'ARISTA04T1', 'value': {u'vm_offset': 3, u'vlans': [31]}})
ok: [STR-ACS-VSERV-01 -> localhost] => (item={'key': u'ARISTA03T1', 'value': {u'vm_offset': 2, u'vlans': [30]}})
ok: [STR-ACS-VSERV-01 -> localhost] => (item={'key': u'ARISTA02T1', 'value': {u'vm_offset': 1, u'vlans': [29]}})
ok: [STR-ACS-VSERV-01 -> localhost] => (item={'key': u'ARISTA01T1', 'value': {u'vm_offset': 0, u'vlans': [28]}})

TASK [Announce routes] **********************************************************************************************************
Thursday 11 March 2021  06:21:52 +0000 (0:00:00.956)       0:00:05.628 ******** 
changed: [STR-ACS-VSERV-01 -> localhost]

PLAY RECAP **********************************************************************************************************************
STR-ACS-VSERV-01           : ok=11   changed=4    unreachable=0    failed=0    skipped=4    rescued=0    ignored=0   

Thursday 11 March 2021  06:22:05 +0000 (0:00:13.211)       0:00:18.839 ******** 
=============================================================================== 
Announce routes --------------------------------------------------------------------------------------------------------- 13.21s
Start exabgp processes for IPv6 on PTF ----------------------------------------------------------------------------------- 1.47s
Start exabgp processes for IPv4 on PTF ----------------------------------------------------------------------------------- 1.36s
Verify that exabgp processes for IPv4 are started ------------------------------------------------------------------------ 1.31s
Verify that exabgp processes for IPv6 are started ------------------------------------------------------------------------ 0.96s
Set facts ---------------------------------------------------------------------------------------------------------------- 0.06s
Load topo variables ------------------------------------------------------------------------------------------------------ 0.06s
Add ptf host ------------------------------------------------------------------------------------------------------------- 0.04s
Set ptf host ------------------------------------------------------------------------------------------------------------- 0.04s
include_tasks ------------------------------------------------------------------------------------------------------------ 0.04s
Include variables for PTF containers ------------------------------------------------------------------------------------- 0.03s
Check that variable topo is defined -------------------------------------------------------------------------------------- 0.03s
Check that variable vm_set_name is defined ------------------------------------------------------------------------------- 0.03s
Check that variable ptf_ip is defined ------------------------------------------------------------------------------------ 0.02s
Check if it is a known topology ------------------------------------------------------------------------------------------ 0.02s
done
```

### CODE REVIEW

**Comment by bingwang-ms** [comment]
LGTM. Just wondering if the move of file ```announce_routes.py``` will cause regression for calling in ```add-topo``` ?

**Comment by wangxin** [comment]
Moving file `announce_routes.py` won't affect `add-topo`. I have tested that.

**Review by vaibhavhd — APPROVED** [review]

**Comment by vaibhavhd** [comment]
Have you tested add-topo job via Jenkins? I remember that there were failures seen while executing announce-routes step?
These failures are not seen when add-topo is done locally.

**Comment by wangxin** [comment]
I haven't tested it via Jenkins. But I believe it is not related with this change.

**Pull request merged**
