### PR TITLE
[vlan] Fixed arp responder for VLAN interfaces

### PR DESCRIPTION
**Pull request by akokhan**
- Fixed vlan interface parsing in arp responder.
- Fixed arp response generation on vlan interface.

Signed-off-by: Andriy Kokhan <akokhan@barefootnetworks.com>

### Description of PR

Summary:
Fixes # (issue)
VLAN TC create Linux VLAN interfaces in PTF Docker. E.g., eth0.100 or eth1.200.
The Rx/Tx packets on such interfaces should be untagged. Appropriate tag will be added/stripped by Linux stack. Also, PR fixes VLAN interface template from ifname@vlanid to ifname.vlanid.

### Type of change

- [*] Bug fix

#### How did you verify/test it?

Verified on Barefoot platform

### CODE REVIEW

**Comment by akokhan** [comment]
@lguohan, @stcheng, please review.

**Comment by NStetskovych** [comment]
@lguohan please review. This PR fix arp_reply packets that influence 4th PTF TC.

**Comment by NStetskovych** [comment]
@prsunny pls review

**Comment by prsunny** [comment]
Can you check if `testcase_name=vnet_vxlan`  passes with this change. You would need to fix those failed tests before we could merge this change

**Pull request closed without merging**
