### PR TITLE
Chk disk - Use supported methods to reboot & wait

### PR DESCRIPTION
**Pull request by renukamanavalan**
### Description of PR

Summary:
Fixes # 4172

### Type of change
Use provided methods to reboot & wait

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 201911

#### What is the motivation for this PR?
Final cleanup failed

#### How did you do it?
Instead of manually executing reboot, use methods provided to reboot and as well to check for system status, upon reboot.

#### How did you verify/test it?
This assert should not occur

### CODE REVIEW

**Comment by yxieca** [comment]
@renukamanavalan please fill in the PR template.

**Comment by renukamanavalan** [comment]
> @renukamanavalan please fill in the PR template.

Thanks. Done.

**Review by yxieca — APPROVED** [review]

**Comment by renukamanavalan** [comment]
2021-09-06T16:47:20.9082595Z 
2021-09-06T16:47:20.9086191Z ==================================== ERRORS ====================================
2021-09-06T16:47:20.9088257Z _________________ ERROR at setup of test_monit_status[vlab-01] _________________

**Comment by renukamanavalan** [comment]
2021-09-07T15:32:29.9194815Z ==================================== ERRORS ====================================
2021-09-07T15:32:29.9200766Z _________________ ERROR at setup of test_monit_status[vlab-01] _________________

**Comment by renukamanavalan** [comment]
2021-09-07T15:29:45.7208891Z ==================================== ERRORS ====================================
2021-09-07T15:29:45.7210591Z _________________ ERROR at setup of test_monit_status[vlab-01] _________________

**Pull request merged**
