### PR TITLE
Add the show ip/ipv6 bgp test ro user commands

### PR DESCRIPTION
**Pull request by xumia**
### Description of PR

Summary:
Add UTs to cover the 'show ip bgp' ro commands.
Fix some of the commands that prompt rw required message, but not detected issue.
Add stricter testing checks, for any ro/rw commands, if any error log which contains the "RW permission" required message, the UT will be failed.
The checks will be succeeded after the PR https://github.com/Azure/sonic-utilities/pull/2011 merged.
```
show ip bgp neighbors 

Make sure your account has RW permission to current device.
Otherwise sudo requests will be rejected.
```

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911

#### What is the motivation for this PR?
Add test cases for PR https://github.com/Azure/sonic-utilities/pull/2011

### CODE REVIEW

**Review by qiluo-msft — APPROVED** [review]

**Comment by xumia** [comment]
The test_ro_user does not work as expected, the test should be failed.
```
AzDevOps@vmss-soni000002:~$ sshpass -p *** ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null test_rouser@10.250.0.101 show ip bgp neighbors
Warning: Permanently added '10.250.0.101' (ECDSA) to the list of known hosts.

Make sure your account has RW permission to current device.
Otherwise sudo requests will be rejected.

sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
sudo: a password is required

AzDevOps@vmss-soni000002:~$ echo $?
0
AzDevOps@vmss-soni000002
```
We cannot use the return value to check whether ro permission is correct or not.

**Comment by qiluo-msft** [comment]
>     return res['rc'] != 0 and "Make sure your account has RW permission to current device" in res['stderr']

I am wondering in `ssh_remote_ban_run`, we did check `rc != 0`. Why it is working?

---
Refers to: tests/tacacs/test_ro_user.py:54 in eeb6671. [](commit_id = eeb66719be06cd2b74d0ebc4d41497303f5bd069, deletion_comment = False)

**Review by wangxin — APPROVED** [review]

**Review by qiluo-msft — APPROVED** [review]

**Comment by xumia** [comment]
Waiting for all the following PRs complete.
https://github.com/Azure/sonic-buildimage/pull/9773
https://github.com/Azure/sonic-buildimage/pull/9774
https://github.com/Azure/sonic-buildimage/pull/9775

**Comment by wangxin** [comment]
This is an old PR which has already been included in 202012 when it was branched off.

**Pull request merged**
