### PR TITLE
[multi asic] Changes to arp tests to support multi asic platforms

### PR DESCRIPTION
**Pull request by arlakshm**
### Description of PR

Summary:
Fixes # (issue)
Changes to arp tests to support multi asic platforms
### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

#### What is the motivation for this PR?
This PR is done to support the tests in the following files on multi asic platforms
 - test_arpall.py
 - test_neighbor_mac_noptf.py
 - 

#### How did you do it?
This PR has the following changes
 - Changes to `minigraph_facts` to support gatther on facts for single asic.
 - Support in `switch_arptable` module to get neighbor entries for each namespace in the Kernel
 - Modify the tests in files to support multi asic platforms
   - test_arpall.py
   - test_neighbor_mac_noptf.py
  
#### How did you verify/test it?
**Verification on single asic**
 - test_arpall.py
```
 arlakshm@41033a037655:/data/sonic-mgmt/tests$ ./run_tests.sh -n vms-kvm-t1-lag  -d vlab03 -c arp/test_arpall.py -f vtestbed.csv -i veos_vtb -u -e '--skip_sanity --disable_loganalyzer'
=== Running tests in groups ===
/usr/local/lib/python2.7/dist-packages/ansible/parsing/vault/__init__.py:44: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.
  from cryptography.exceptions import InvalidSignature
==================================================================================================== test session starts ====================================================================================================platform linux2 -- Python 2.7.17, pytest-4.6.5, py-1.9.0, pluggy-0.13.1
ansible: 2.8.12
rootdir: /data/sonic-mgmt/tests, inifile: pytest.ini
plugins: forked-1.3.0, xdist-1.28.0, repeat-0.8.0, metadata-1.10.0, html-1.22.1, ansible-2.2.2
collected 5 items

arp/test_arpall.py::test_arp_unicast_reply[None] PASSED                                                                                                                                                               [ 20%]
arp/test_arpall.py::test_arp_expect_reply[None] PASSED                                                                                                                                                                [ 40%]
arp/test_arpall.py::test_arp_no_reply_other_intf[None] PASSED                                                                                                                                                         [ 60%]
arp/test_arpall.py::test_arp_no_reply_src_out_range[None] PASSED                                                                                                                                                      [ 80%]
arp/test_arpall.py::test_arp_garp_no_update[None] PASSED                                                                                                                                                              [100%]

---------------------------------------------------------------------------------- generated xml file: /data/sonic-mgmt/tests/logs/tr.xml -----------------------------------------------------------------------------------================================================================================================ 5 passed in 624.09 seconds =================================================================================================
arlakshm@41033a037655:/data/sonic-mgmt/tests$
```
 - test_neighbor_mac_noptf
 ```
arlakshm@41033a037655:/data/sonic-mgmt/tests$ ./run_tests.sh -n vms-kvm-t1-lag  -d vlab03 -c arp/test_neighbor_mac_noptf.py -f vtestbed.csv -i veos_vtb -u -e '--skip_sanity --disable_loganalyzer'
=== Running tests in groups ===
/usr/local/lib/python2.7/dist-packages/ansible/parsing/vault/__init__.py:44: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.
  from cryptography.exceptions import InvalidSignature
==================================================================================================== test session starts ====================================================================================================platform linux2 -- Python 2.7.17, pytest-4.6.5, py-1.9.0, pluggy-0.13.1
ansible: 2.8.12
rootdir: /data/sonic-mgmt/tests, inifile: pytest.ini
plugins: forked-1.3.0, xdist-1.28.0, repeat-0.8.0, metadata-1.10.0, html-1.22.1, ansible-2.2.2
collected 2 items

arp/test_neighbor_mac_noptf.py::TestNeighborMacNoPtf::testNeighborMacNoPtf[4-None] PASSED                                                                                                                             [ 50%]
arp/test_neighbor_mac_noptf.py::TestNeighborMacNoPtf::testNeighborMacNoPtf[6-None] PASSED                                                                                                                             [100%]

---------------------------------------------------------------------------------- generated xml file: /data/sonic-mgmt/tests/logs/tr.xml -----------------------------------------------------------------------------------
```

**Verification on Multi asic**
 - test_arpall.py
```
 arlakshm@6592658efdea:/data/sonic-mgmt/tests$ ./run_tests.sh -d multi_asic_1 -n vms13-t1-lag-2 -c arp/test_arpall.py -i /data/files/veos_vtb -f /data/files/vtestbed.csv -u -e '--skip_sanity --deep_clean --disable_loganalyzer  '
=== Running tests in groups ===
/usr/local/lib/python2.7/dist-packages/ansible/parsing/vault/__init__.py:44: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.
  from cryptography.exceptions import InvalidSignature
==================================================================================================== test session starts ====================================================================================================platform linux2 -- Python 2.7.12, pytest-4.6.5, py-1.9.0, pluggy-0.13.1
ansible: 2.8.12
rootdir: /data/sonic-mgmt/tests, inifile: pytest.ini
plugins: ansible-2.2.2, forked-1.3.0, xdist-1.28.0, html-1.22.1, repeat-0.8.0, metadata-1.10.0
collected 20 items

arp/test_arpall.py::test_arp_unicast_reply[0] PASSED                                                                                                                                                                  [  5%]
arp/test_arpall.py::test_arp_unicast_reply[1] PASSED                                                                                                                                                                  [ 10%]
arp/test_arpall.py::test_arp_unicast_reply[2] PASSED                                                                                                                                                                  [ 15%]
arp/test_arpall.py::test_arp_unicast_reply[3] PASSED                                                                                                                                                                  [ 20%]
arp/test_arpall.py::test_arp_expect_reply[0] PASSED                                                                                                                                                                   [ 25%]
arp/test_arpall.py::test_arp_expect_reply[1] PASSED                                                                                                                                                                   [ 30%]
arp/test_arpall.py::test_arp_expect_reply[2] PASSED                                                                                                                                                                   [ 35%]
arp/test_arpall.py::test_arp_expect_reply[3] PASSED                                                                                                                                                                   [ 40%]
arp/test_arpall.py::test_arp_no_reply_other_intf[0] PASSED                                                                                                                                                            [ 45%]
arp/test_arpall.py::test_arp_no_reply_other_intf[1] PASSED                                                                                                                                                            [ 50%]
arp/test_arpall.py::test_arp_no_reply_other_intf[2] PASSED                                                                                                                                                            [ 55%]
arp/test_arpall.py::test_arp_no_reply_other_intf[3] PASSED                                                                                                                                                            [ 60%]
arp/test_arpall.py::test_arp_no_reply_src_out_range[0] PASSED                                                                                                                                                         [ 65%]
arp/test_arpall.py::test_arp_no_reply_src_out_range[1] PASSED                                                                                                                                                         [ 70%]
arp/test_arpall.py::test_arp_no_reply_src_out_range[2] PASSED                                                                                                                                                         [ 75%]
arp/test_arpall.py::test_arp_no_reply_src_out_range[3] PASSED                                                                                                                                                         [ 80%]
arp/test_arpall.py::test_arp_garp_no_update[0] PASSED                                                                                                                                                                 [ 85%]
arp/test_arpall.py::test_arp_garp_no_update[1] PASSED                                                                                                                                                                 [ 90%]
arp/test_arpall.py::test_arp_garp_no_update[2] PASSED                                                                                                                                                                 [ 95%]
arp/test_arpall.py::test_arp_garp_no_update[3] PASSED                                                                                                                                                                 [100%]

---------------------------------------------------------------------------------- generated xml file: /data/sonic-mgmt/tests/logs/tr.xml -----------------------------------------------------------------------------------
=============================================================================================== 20 passed in 1279.12 seconds ================================================================================================
arlakshm@6592658efdea:/data/sonic-mgmt/tests$
```

- test_neighbor_mac_noptf

```
arlakshm@6592658efdea:/data/sonic-mgmt/tests$ ./run_tests.sh -d multi_asic_1 -n vms13-t1-lag-2 -c arp/test_neighbor_mac_noptf.py -i /data/files/veos_vtb -f /data/files/vtestbed.csv -u -e '--skip_sanity --deep_clean --disable_loganalyzer  '
=== Running tests in groups ===
/usr/local/lib/python2.7/dist-packages/ansible/parsing/vault/__init__.py:44: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.
  from cryptography.exceptions import InvalidSignature
==================================================================================================== test session starts ====================================================================================================platform linux2 -- Python 2.7.12, pytest-4.6.5, py-1.9.0, pluggy-0.13.1
ansible: 2.8.12
rootdir: /data/sonic-mgmt/tests, inifile: pytest.ini
plugins: ansible-2.2.2, forked-1.3.0, xdist-1.28.0, html-1.22.1, repeat-0.8.0, metadata-1.10.0
collected 8 items

arp/test_neighbor_mac_noptf.py::TestNeighborMacNoPtf::testNeighborMacNoPtf[4-0] PASSED                                                                                                                                [ 12%]
arp/test_neighbor_mac_noptf.py::TestNeighborMacNoPtf::testNeighborMacNoPtf[4-1] PASSED                                                                                                                                [ 25%]
arp/test_neighbor_mac_noptf.py::TestNeighborMacNoPtf::testNeighborMacNoPtf[4-2] PASSED                                                                                                                                [ 37%]
arp/test_neighbor_mac_noptf.py::TestNeighborMacNoPtf::testNeighborMacNoPtf[4-3] PASSED                                                                                                                                [ 50%]
arp/test_neighbor_mac_noptf.py::TestNeighborMacNoPtf::testNeighborMacNoPtf[6-0] PASSED                                                                                                                                [ 62%]
arp/test_neighbor_mac_noptf.py::TestNeighborMacNoPtf::testNeighborMacNoPtf[6-1] PASSED                                                                                                                                [ 75%]
arp/test_neighbor_mac_noptf.py::TestNeighborMacNoPtf::testNeighborMacNoPtf[6-2] PASSED                                                                                                                                [ 87%]
arp/test_neighbor_mac_noptf.py::TestNeighborMacNoPtf::testNeighborMacNoPtf[6-3] PASSED                                                                                                                                [100%]

---------------------------------------------------------------------------------- generated xml file: /data/sonic-mgmt/tests/logs/tr.xml -----------------------------------------------------------------------------------
===============================================
```

### CODE REVIEW

**Review by yxieca — APPROVED** [review]

**Comment by wangxin** [comment]
@arlakshm Can you resolve the merge conflicts?

**Comment by arlakshm** [comment]
> @arlakshm Can you resolve the merge conflicts?

@wangxin. All the conflicts are resolved. Please review and approve if no comments.

**Review by wangxin — APPROVED** [review]

**Pull request merged**
