### PR TITLE
Quagga templates inheritance

### PR DESCRIPTION
**Pull request by NStetskovych**
Propose changes to configure zebra for different platforms in different ways

### CODE REVIEW

**Comment by lguohan** [comment]
can you help to explain why quagga configuration is asic platform dependent?

**Comment by NStetskovych** [comment]
Actually it is not :). For now default config file for zеbra configuration contain parts that is not mandatory. Just want to propose the way every vendor can easy customize configuration (not breaking default config) using current sonic-mgmt deployment.

**Comment by qiluo-msft** [comment]
Could you give more details about "default config file for zеbra configuration contain parts that is not mandatory"?

**Comment by NStetskovych** [comment]
By current default zebra config all src ports will have loopback ip. But let`s consider the attached config that not require 'set  src' configuration. By current implementation it`s look impossible just remove minigraph_lo_interfaces from minigraph_fact.yaml (and generate other template by adding validation whether we have lo interface ) 
[DUT1.txt](https://github.com/Azure/sonic-mgmt/files/524710/DUT1.txt)

Thanks.

**Comment by NStetskovych** [comment]
Could we just remove set src config from default?

**Comment by lguohan** [comment]
no, it is required by sonic configuration.

**Comment by NStetskovych** [comment]
I mean take away from zebra default config. Do you consider attached above config valid (in the text file)? Now it is impossible to generate such config  because all src port will point to loopback ip.

**Comment by lguohan** [comment]
there is no plan to introduction hw platform specific quagga configuration, any concern to close this PR?

**Pull request closed without merging**
