### PR TITLE
[ptf_runner_reboot] cleanup ARP/FDB after test

### PR DESCRIPTION
**Pull request by stepanblyschak**
Signed-off-by: Stepan Blyschak <stepanb@mellanox.com>

### Description of PR

Summary:
Fixes # (issue)

### Type of change

- [] Bug fix
- [] Testbed and Framework(new/improvement)
- [] Test case(new/improvement)

### CODE REVIEW

**Comment by stepanblyschak** [comment]
@neethajohn The motivation is to cleanup after test.

E.g in our regression run we have the following order of test execution: 
Fast-Reboot, CRM. After fast reboot there are FDB, ARP entries untill they expire. CRM test fails when some FDB expires, because it affects other resources count.

What is the problem with cleanup? What was the root cause of t1->server traffic loss with fdb flush?
The test should repopulate FDB

**Comment by liat-grozovik** [comment]
IMO each test should be standalone and make sure the next one is not affected.

**Comment by lguohan** [comment]
for warm reboot, you should not clear the mac, since it can cause data plane disruption.

**Comment by stepanblyschak** [comment]
@lguohan This is after the test, after PTF run finished we don't run test traffic so don't care about disruption

**Comment by neethajohn** [comment]
> @neethajohn The motivation is to cleanup after test.
> E.g in our regression run we have the following order of test execution:
> Fast-Reboot, CRM. After fast reboot there are FDB, ARP entries untill they expire. CRM test fails when some FDB expires, because it affects other resources count.
> What is the problem with cleanup? What was the root cause of t1->server traffic loss with fdb flush?
> The test should repopulate FDB

Let me try out this patch on the platforms where I was seeing an issue earlier.

**Pull request merged**
