### PR TITLE
Update location of gnxi files in test_telemetry due to docker-ptf modification

### PR DESCRIPTION
**Pull request by ZhaohuiS**
### Description of PR

Summary:
Fixes # (issue)
Update location of gnxi files due to docker-ptf modification
Signed-off-by: Zhaohui Sun <zhaohuisun@microsoft.com>
### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012

#### What is the motivation for this PR?
PR https://github.com/Azure/sonic-buildimage/pull/10599 move the work directory to /root.
So gnxi is moved to /root. test_telemetry failed because of wrong file location.

#### How did you do it?
Update `/gnxi/...` to `/root/gnxi/...`

#### How did you verify/test it?
run `tests/telemetry/test_telemetry.py`

### CODE REVIEW

**Review by wangxin — APPROVED** [review]

**Comment by wangxin** [comment]
This change is not required for 202012 branch. For 202012 image, we are using PTF docker image built from 202012 branch. That PTF docker does not have change https://github.com/Azure/sonic-buildimage/pull/10599.

**Comment by wangxin** [comment]
@wenyiz2021 I guess the testbed was deployed using master branch. Then if you switch to 202012 and run this test, it will fail. 
To workaround this issue, you can re-create the PTF docker using command like:
```
./testbed-cli.sh restart-ptf <TESTBED_NAME> password.txt -e ptf_imagetag=202012
```
This command will re-create the PTF docker using image with tag `202012`.

I am not going to cherry-pick this change to 202012 because our 202012 nightly tests were using 202012 PTF docker. Cherry-pick this will break our nightly test for 2022012.

@ZhaohuiS Can you improve this test to check location of the gnxi files under both `/` and `/root`. Then it will work for PTF docker of both master and 202012 branch.

**Comment by wenyiz2021** [comment]
> @wenyiz2021 I guess the testbed was deployed using master branch. Then if you switch to 202012 and run this test, it will fail. To workaround this issue, you can re-create the PTF docker using command like:
> 
> ```
> ./testbed-cli.sh restart-ptf <TESTBED_NAME> password.txt -e ptf_imagetag=202012
> ```
> 
> This command will re-create the PTF docker using image with tag `202012`.
> 
> I am not going to cherry-pick this change to 202012 because our 202012 nightly tests were using 202012 PTF docker. Cherry-pick this will break our nightly test for 2022012.
> 
> @ZhaohuiS Can you improve this test to check location of the gnxi files under both `/` and `/root`. Then it will work for PTF docker of both master and 202012 branch.

Thanks Xin. It would be good if we get gnxi files under both dir, ow AZP run will fail on 202012.

**Comment by ZhaohuiS** [comment]
> @wenyiz2021 I guess the testbed was deployed using master branch. Then if you switch to 202012 and run this test, it will fail. To workaround this issue, you can re-create the PTF docker using command like:
> 
> ```
> ./testbed-cli.sh restart-ptf <TESTBED_NAME> password.txt -e ptf_imagetag=202012
> ```
> 
> This command will re-create the PTF docker using image with tag `202012`.
> 
> I am not going to cherry-pick this change to 202012 because our 202012 nightly tests were using 202012 PTF docker. Cherry-pick this will break our nightly test for 2022012.
> 
> @ZhaohuiS Can you improve this test to check location of the gnxi files under both `/` and `/root`. Then it will work for PTF docker of both master and 202012 branch.

Submitted a new PR #5634 to fix it.

**Comment by wangxin** [comment]
PR #5634 improved the telemetry test to look for gnxi under both `/` and `/root`. But that PR is based on this one. I have cherry picked both #5634 and this one to the 202012 branch. Now the telemetry test should work on PTF docker built from both master and 202012 branch.

**Pull request merged**
