### PR TITLE
[multi vlan] Fix Ansible condition when evaluating vlan config for T0 variants

### PR DESCRIPTION
**Pull request by stephenxs**
### Description of PR
Summary:
Fixes # (issue)
Only compute vlan parameters for t0 series topo (t0, t0-xx).
PR [[ansible] Adding support for multi vlans #1353](https://github.com/azure/sonic-mgmt/pull/1353) introduces some vlan features but only supported on t0 series topo. 
However, it tries to call this module on other topos like t1, which causes the following issue:
```
fatal: [mtbc-sonic-03-2700 -> localhost]: FAILED! => {
"changed": false, 
"msg": "Traceback (most recent call last):\n
File \"/tmp/ansible_vlan_config_payload_h5ngrh/__main__.py\", line 46, in main\n 
vlan_config = m_args['vm_topo_config']['DUT']['vlan_configs']['default_vlan_config']\n
KeyError: 'vlan_configs'\n"
}
```
This PR add logic of checking the topology and calling the module on t0 series only.

### Type of change

- [x] Bug fix
- [] Testbed and Framework(new/improvement)
- [] Test case(new/improvement)

### CODE REVIEW

**Comment by liat-grozovik** [comment]
@tahmed-dev please check the PR as it fixes an issue observed following some changes provided by you. 
To me the fix seems to be correct but the problem is that i am not sure if this was missed  or by intention and the fix need to be different.  
NOTE: who ever try to run non t0 topo is currently blocked as of that.

**Comment by tahmed-dev** [comment]
> @tahmed-dev please check the PR as it fixes an issue observed following some changes provided by you.
> To me the fix seems to be correct but the problem is that i am not sure if this was missed or by intention and the fix need to be different.
> NOTE: who ever try to run non t0 topo is currently blocked as of that.
Thanks @liat-grozovik Every t0 variant device is a ToR device. Current practice is to identify the device type by checking the dut_type from the topology file. this could be seen in:

https://github.com/Azure/sonic-mgmt/blob/master/ansible/vars/topo_t0.yml#L77 and 
https://github.com/Azure/sonic-mgmt/blob/master/ansible/vars/topo_t1.yml#L135

Which topo was used to produce this issue? Is it in public repo?

**Comment by stephenxs** [comment]
Hi @tahmed-dev, 
I saw the error in t1 and t1-lag. I suspect it can be reproduced in any non-t0 topo.

**Comment by stephenxs** [comment]
> This previous format works too, the issue was with the extra double quotation
> 
> ```
> when: ('host_interfaces' in vm_topo_config) and ('tor' in vm_topo_config['dut_type'] | lower)
> ```
> 
> Please fix this one to get going and I will take care of the rest.

Understood.
I will do it in this way.

**Pull request merged**
