### PR TITLE
[watchdog.yml] Add MSN3420 watchdog tests values

### PR DESCRIPTION
**Pull request by stepanblyschak**
Signed-off-by: Stepan Blyschak <stepanb@nvidia.com>

### Description of PR

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### CODE REVIEW

**Review by wangxin — APPROVED** [review]

**Comment by wangxin** [comment]
retest this please

**Comment by wangxin** [comment]
retest this please

**Comment by liat-grozovik** [comment]
retest vsimage please

**Comment by liat-grozovik** [comment]
retest vsimage please

**Comment by wangxin** [comment]
retest vsimage please

**Pull request merged**
