### PR TITLE
[topo]: Fix BGP IPv6 flapping for t0-56-po2vlan

### PR DESCRIPTION
**Pull request by nazariig**
Signed-off-by: Nazarii Hnydyn <nazariig@nvidia.com>

### Description of PR

**Summary:**
Fixes https://github.com/Azure/sonic-utilities/issues/1865

This is a backport of: https://github.com/Azure/sonic-mgmt/pull/3793

**Before:**
```
root@sonic:/home/admin# show ipv6 bgp summary

IPv6 Unicast Summary:
BGP router identifier 10.1.0.32, local AS number 65100 vrf-id 0
BGP table version 77853
RIB entries 12815, using 2357960 bytes of memory
Peers 8, using 167360 KiB of memory
Peer groups 4, using 256 bytes of memory


Neighbhor      V     AS    MsgRcvd    MsgSent    TblVer    InQ    OutQ  Up/Down      State/PfxRcd  NeighborName
-----------  ---  -----  ---------  ---------  --------  -----  ------  ---------  --------------  --------------
fc00::7a       4  64600      17665      35906         0      0       0  00:23:44             1473  ARISTA03T1
fc00::7e       4  64600      10071      35906         0      0       0  00:23:44                1  ARISTA04T1
fc00::8a       4  64600      17076      35906         0      0       0  00:23:44             6400  ARISTA07T1
fc00::8e       4  64600      13653      36741         0      0       0  00:23:46             6400  ARISTA08T1
fc00::72       4  64600      16873      35906         0      0       0  00:23:44             6398  ARISTA01T1
fc00::76       4  64600      16891      36739         0      0       0  00:23:45                1  ARISTA02T1
fc00::82       4  64600      13671      35906         0      0       0  00:23:43                1  ARISTA05T1
fc00::86       4  64600      19953      35906         0      0       0  00:23:43             5767  ARISTA06T1

Total number of neighbors 8
```

**After:**
```
root@sonic:/home/admin# show ipv6 bgp summary

IPv6 Unicast Summary:
BGP router identifier 10.1.0.32, local AS number 65100 vrf-id 0
BGP table version 11151
RIB entries 12817, using 2358328 bytes of memory
Peers 8, using 167360 KiB of memory
Peer groups 4, using 256 bytes of memory


Neighbhor      V     AS    MsgRcvd    MsgSent    TblVer    InQ    OutQ  Up/Down      State/PfxRcd  NeighborName
-----------  ---  -----  ---------  ---------  --------  -----  ------  ---------  --------------  --------------
fc00::7a       4  64600       3230       3237         0      0       0  00:25:21             6400  ARISTA03T1
fc00::7e       4  64600       3230       3238         0      0       0  00:25:24             6400  ARISTA04T1
fc00::8a       4  64600       3230       3238         0      0       0  00:25:24             6400  ARISTA07T1
fc00::8e       4  64600       3230       3240         0      0       0  00:25:24             6400  ARISTA08T1
fc00::72       4  64600       3230       3240         0      0       0  00:25:24             6400  ARISTA01T1
fc00::76       4  64600       3232       3240         0      0       0  00:25:24             6400  ARISTA02T1
fc00::82       4  64600       3230       3237         0      0       0  00:25:23             6400  ARISTA05T1
fc00::86       4  64600       3230       3240         0      0       0  00:25:24             6400  ARISTA06T1

Total number of neighbors 8
```

### Type of change

- [X] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911

#### What is the motivation for this PR?
* To fix BGP IPv6 flapping for `t0-56-po2vlan`

#### How did you do it?
* Fixed `topo_t0-56-po2vlan.yml`

#### How did you verify/test it?
* Ran `tests/fdb/test_fdb.py`

#### Any platform specific information?
* N/A

#### Supported testbed topology if it's a new test case?
* N/A

### Documentation 

* N/A

### CODE REVIEW

**Comment by nazariig** [comment]
@qiluo-msft can you please have a look?

**Comment by qiluo-msft** [comment]
Could you explain how it fixes the test case in `tests/fdb/test_fdb.py`?

**Comment by nazariig** [comment]
> 
> 
> Could you explain how it fixes the test case in `tests/fdb/test_fdb.py`?

@qiluo-msft the BGPv6 flapping invokes route/ECMP reconfiguration, which causes the SWSS queue overload, thus FDB clear execution takes more time

**Review by qiluo-msft — APPROVED** [review]
Please wait for other reviewers.

**Review by ganglyu — APPROVED** [review]
lgtm

**Comment by nazariig** [comment]
@qiluo-msft can you please merge?

**Pull request merged**
