### PR TITLE
[topo] Bug fix: wrong ipv6 link local address on backplane port in t0-56

### PR DESCRIPTION
**Pull request by stephenxs**
### Description of PR

Summary:
Fixes # (issue)

There are 8 VMs in t0-56 topo. The 1st half of VMs share the same IPv6 link-local addresses on backplane ports with the 2nd half, causing BGPv6 neighbour flapping.
This is to fix the issue.
We also reassigned the IP addresses in look back and back plane interfaces in the same way it has been done in t0 64 topo. By doing so those IP addresses will be easy to remember.

Signed-off-by: Stephen Sun <stephens@nvidia.com>

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911

### CODE REVIEW

**Comment by liat-grozovik** [comment]
LGTM. @wangxin could you please help to review?

**Review by liat-grozovik — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@qiluo-msft for awareness

**Comment by qiluo-msft** [comment]
> The 1st half of VMs share the same link-local addresses on backplane ports with the 2nd half

Do you mean link-local ipv6 addresses?

**Review by qiluo-msft — APPROVED** [review]

**Comment by stephenxs** [comment]
> > The 1st half of VMs share the same link-local addresses on backplane ports with the 2nd half
> 
> Do you mean link-local ipv6 addresses?

Yes. Description updated.

**Review by shi-su — COMMENTED** [review]
The changes look OK to me. Just curious, from the PR description, it seems only `bp_interface|ipv6` needs fix. Why do we need to modify other fields (i.e., `Loopback0`, `bp_interface|ipv4`)?

**Comment by stephenxs** [comment]
> The changes look OK to me. Just curious, from the PR description, it seems only `bp_interface|ipv6` needs fix. Why do we need to modify other fields (i.e., `Loopback0`, `bp_interface|ipv4`)?

Hi
This is to make the Ip addresses allocated to each VM easy to remember. IP addresses in t0 64 topo are allocated in the same way.

**Review by shi-su — APPROVED** [review]

**Pull request merged**
