### PR TITLE
[vlan]: Remove route related configuration.

### PR DESCRIPTION
**Pull request by ganglyu**
Signed-off-by: Gang Lv ganglv@microsoft.com

### Description of PR

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 201911

#### What is the motivation for this PR?
Current VLAN test is using layer 2 forwarding, so route related configuration is redundant.

#### How did you do it?
Remove create_vlan_interfaces, setUpArpResponder and add_test_routes.

#### How did you verify/test it?
Run test with t0 topo.

### CODE REVIEW

**Review by qiluo-msft — COMMENTED** [review]
LGTM. Please wait for more eyes.

**Review by qiluo-msft — APPROVED** [review]

**Comment by qiluo-msft** [comment]
Please fix lgtm alerts.

**Comment by theasianpianist** [comment]
I believe the `create_vlan_interfaces` method is necessary for some backend topologies, @neethajohn can you confirm? Also @ganglyu can you run the tests on a dual ToR topology and make sure they pass?

**Comment by prsunny** [comment]
AFAIK, this cover both Vlan and Vlan RIF scenarios. I don't think we should remove this unless you see some failures in some scenarios.

**Comment by ganglyu** [comment]
> AFAIK, this cover both Vlan and Vlan RIF scenarios. I don't think we should remove this unless you see some failures in some scenarios.

I have verified with t0 topo, and I can't find any issue.
The destination MAC address of test packet is broadcast MAC and PTF port MAC address, so this test only covers layer 2 forwarding. If we want to verify Vlan RIF, the destination must be VLAN RIF MAC address.

**Comment by ganglyu** [comment]
> I believe the `create_vlan_interfaces` method is necessary for some backend topologies, @neethajohn can you confirm? Also @ganglyu can you run the tests on a dual ToR topology and make sure they pass?

I have run the tests on a dual ToR topology, and all tests passed.

**Review by qiluo-msft — COMMENTED** [review]
The new iterations also look good to me.

**Comment by neethajohn** [comment]
@lolyu, fyi

**Review by lolyu — APPROVED** [review]
LGTM, the code change works on `t0-backend`.

**Comment by qiluo-msft** [comment]
@prsunny Do you have concern with this PR?

**Pull request merged**
