### PR TITLE
[MASIC] [QoS] Refactor MASIC QoS DSCP test 

### PR DESCRIPTION
**Pull request by smaheshm**
<!--
Please make sure you've read and understood our contributing guidelines;
https://github.com/Azure/SONiC/blob/gh-pages/CONTRIBUTING.md

Please provide following information to help code review process a bit easier:
-->
### Description of PR
Refactored MASIC QoS DSCP test to not run in the context of other qos tests.
There is no functional change in the test case, except MASIC DSCP test checks for all, including internal, BGP sessions to be up before running the test.

Summary:
Fixes # (issue)
MASIC DSCP test requires BGP to be running, where as other QoS tests filter out the BGP messages that shuts BGP session.


### Type of change

<!--
- Fill x for your type of change.
- e.g.
- [x] Bug fix
-->

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ x] Test case(new/improvement)


### Back port request
- [ ] 201911
- [ ] 202012

### Approach
#### What is the motivation for this PR?
Make MASIC tests independent of other QoS tests

#### How did you do it?
Separated out MASIC tests with single ASIC qos tests.

#### How did you verify/test it?
```
samaddik@svcstr-server-2:/var/sonic-mgmt/tests$ pytest qos/test_qos_masic.py  --testbed=vmsvc1-t1-nmasic-acs-1 --inventory=../ansible/strsvc,../ansible/veos  --testbed_file=../ansible/testbed.csv --host-pattern=svcstr-nmasic-acs-1  --module-path=../ansible/library  --topology="t1,any"    --skip_sanity

/usr/local/lib/python2.7/dist-packages/ansible/parsing/vault/__init__.py:44: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
  from cryptography.exceptions import InvalidSignature
==================================================================================================================== test session starts ====================================================================================================================
platform linux2 -- Python 2.7.17, pytest-4.6.5, py-1.10.0, pluggy-0.13.1
ansible: 2.8.12
rootdir: /var/sonic-mgmt/tests, inifile: pytest.ini
plugins: html-1.22.1, repeat-0.9.1, forked-1.3.0, xdist-1.28.0, metadata-1.11.0, ansible-2.2.2
collecting ... ['conf-name', 'group-name', 'topo', 'ptf_image_name', 'ptf', 'ptf_ip', 'ptf_ipv6', 'server', 'vm_base', 'dut', 'inv_name', 'auto_recover', 'comment']
Finished testbed info generating.
/usr/local/lib/python2.7/dist-packages/ansible/parsing/vault/__init__.py:44: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
  from cryptography.exceptions import InvalidSignature
collected 2 items

qos/test_qos_masic.py ..                                                                                                                                                                                                                              [100%]

===================================================================================================================== warnings summary ======================================================================================================================
/usr/local/lib/python2.7/dist-packages/_pytest/config/__init__.py:538
  /usr/local/lib/python2.7/dist-packages/_pytest/config/__init__.py:538: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: tests.common.dualtor
    self.import_plugin(import_spec)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
========================================================================================================== 2 passed, 1 warnings in 876.99 seconds ===========================================================================================================
s
```

#### Any platform specific information?

#### Supported testbed topology if it's a new test case?

### Documentation
<!--
(If it's a new feature, new test case)
Did you update documentation/Wiki relevant to your implementation?
Link to the wiki page?
-->

### CODE REVIEW

**Review by arlakshm — APPROVED** [review]
lgtm

**Comment by wenyiz2021** [comment]
Reason for merging this PR: Manual run of all test_qos_sai.py will fail on multi-asic qos tests, but independently run multi-asic qos test ONLY will pass. This refactor of separating MASIC into separate class might help on this, as old design have dependency on other qos tests for multi-asic qos tests, where in other qos tests BGP control packets are filtered so that they are not sent out, which causes BGP sessions to go down.

================================================================================================================ short test summary info =================================================================================================================
SKIPPED [8] /var/src/sonic-mgmt-int/tests/qos/test_qos_sai.py:371: Buffer Pool watermark test is disabled
SKIPPED [4] /var/src/sonic-mgmt-int/tests/qos/test_qos_sai.py:561: Dot1p-PG mapping is not supported on t1-64-lag
SKIPPED [4] /var/src/sonic-mgmt-int/tests/qos/test_qos_sai.py:170: PFC Xon Limit test: Need at least 3 destination ports
SKIPPED [4] /var/src/sonic-mgmt-int/tests/qos/test_qos_sai.py:844: DSCP to PG mapping test disabled
SKIPPED [4] /var/src/sonic-mgmt-int/tests/qos/test_qos_sai.py:527: Dot1p-queue mapping is not supported on t1-64-lag
SKIPPED [4] /var/src/sonic-mgmt-int/tests/qos/test_qos_sai.py:306: Headroom pool watermark is not supported
SKIPPED [4] /var/src/sonic-mgmt-int/tests/qos/test_qos_sai.py:229: Headroom pool size not supported
FAILED qos/test_qos_sai.py::TestQosSaiMasic::test_qos_masic_dscp_queue_mapping[4] - Failed: Route 10.0.0.53 doesn't have backend ASIC nexthop on ASIC 2
FAILED qos/test_qos_sai.py::TestQosSaiMasic::test_qos_masic_dscp_queue_mapping[5] - Failed: Route 10.0.0.53 doesn't have backend ASIC nexthop on ASIC 2
=================================================================================================== 2 failed, 52 passed, 32 skipped in 6472.56 seconds ===================================================================================================
INFO:root:Can not get Allure report URL. Please check logs
AzDevOps@8bcda3ef7587:/var/src/sonic-mgmt-int/tests$ sudo ./run_tests.sh -n {masic testbed} -i ../ansible/xx,../ansible/veos -u -e "--disable_loganalyzer --skip_sanity" -c qos/test_qos_sai.py::TestQosSaiMasic::test_qos_masic_dscp_queue_mapping
=== Running tests in groups ===
================================================================================================================== test session starts ==================================================================================
qos/test_qos_sai.py::TestQosSaiMasic::test_qos_masic_dscp_queue_mapping[4] PASSED                                                                                                                                                                  [ 50%]
qos/test_qos_sai.py::TestQosSaiMasic::test_qos_masic_dscp_queue_mapping[5] PASSED                                                                                                                                                                  [100%]

**Pull request merged**
