### PR TITLE
[sonic_fanout] Add dynamic port breakout support

### PR DESCRIPTION
**Pull request by lolyu**
### Description of PR

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [x] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911

#### What is the motivation for this PR?
Add dynamic port breakout support for Arista 7060 devices

Signed-off-by: Longxiang Lyu <lolv@microsoft.com>

#### How did you do it?
1. add the flex config `bcm` file for Arista 7060 devices
2. Copy the `bcm` config file to the newly-create hwsku

#### How did you verify/test it?
run `fanout.yml` over a 7060 fanout with port breakout

#### Any platform specific information?
Arista 7060
**NOTE**: not support other platforms that use `config.bcm.j2` to specify SAI bcm config

### CODE REVIEW

**Comment by lolyu** [comment]
```
admin@str-7060cx-32s-08:~$ show int s
  Interface            Lanes    Speed    MTU    FEC         Alias    Vlan    Oper    Admin             Type    Asym PFC
-----------  ---------------  -------  -----  -----  ------------  ------  ------  -------  ---------------  ----------
  Ethernet0      33,34,35,36     100G   9100     rs   Ethernet1/1   trunk      up       up  QSFP28 or later         off
  Ethernet4      37,38,39,40     100G   9100     rs   Ethernet2/1   trunk      up       up  QSFP28 or later         off
  Ethernet8      41,42,43,44     100G   9100     rs   Ethernet3/1   trunk      up       up  QSFP28 or later         off
 Ethernet12      45,46,47,48     100G   9100     rs   Ethernet4/1   trunk      up       up  QSFP28 or later         off
 Ethernet16      49,50,51,52     100G   9100     rs   Ethernet5/1   trunk      up       up  QSFP28 or later         off
 Ethernet20      53,54,55,56     100G   9100     rs   Ethernet6/1   trunk      up       up  QSFP28 or later         off
 Ethernet24      57,58,59,60     100G   9100     rs   Ethernet7/1   trunk      up       up  QSFP28 or later         off
 Ethernet28      61,62,63,64     100G   9100     rs   Ethernet8/1   trunk      up       up  QSFP28 or later         off
 Ethernet32      65,66,67,68     100G   9100     rs   Ethernet9/1   trunk      up       up  QSFP28 or later         off
 Ethernet36      69,70,71,72     100G   9100     rs  Ethernet10/1   trunk      up       up  QSFP28 or later         off
 Ethernet40      73,74,75,76     100G   9100     rs  Ethernet11/1   trunk      up       up  QSFP28 or later         off
 Ethernet44      77,78,79,80     100G   9100     rs  Ethernet12/1   trunk      up       up  QSFP28 or later         off
 Ethernet48      81,82,83,84     100G   9100     rs  Ethernet13/1   trunk      up       up  QSFP28 or later         off
 Ethernet52      85,86,87,88     100G   9100     rs  Ethernet14/1   trunk      up       up  QSFP28 or later         off
 Ethernet56      89,90,91,92     100G   9100     rs  Ethernet15/1   trunk      up       up  QSFP28 or later         off
 Ethernet60      93,94,95,96     100G   9100     rs  Ethernet16/1   trunk      up       up  QSFP28 or later         off
 Ethernet64            97,98      50G   9100    N/A  Ethernet17/1   trunk      up       up  QSFP28 or later         off
 Ethernet66           99,100      50G   9100    N/A  Ethernet17/3   trunk      up       up  QSFP28 or later         off
 Ethernet68          101,102      50G   9100    N/A  Ethernet18/1   trunk      up       up  QSFP28 or later         off
 Ethernet70          103,104      50G   9100    N/A  Ethernet18/3   trunk      up       up  QSFP28 or later         off
 Ethernet72  105,106,107,108     100G   9100     rs  Ethernet19/1  routed    down     down              N/A         off
 Ethernet76  109,110,111,112     100G   9100     rs  Ethernet20/1  routed    down     down              N/A         off
 Ethernet80  113,114,115,116     100G   9100     rs  Ethernet21/1  routed    down     down              N/A         off
 Ethernet84  117,118,119,120     100G   9100     rs  Ethernet22/1  routed    down     down              N/A         off
 Ethernet88  121,122,123,124     100G   9100     rs  Ethernet23/1  routed    down     down              N/A         off
 Ethernet92  125,126,127,128     100G   9100     rs  Ethernet24/1  routed    down     down              N/A         off
 Ethernet96          1,2,3,4     100G   9100     rs  Ethernet25/1  routed    down     down              N/A         off
Ethernet100          5,6,7,8     100G   9100     rs  Ethernet26/1  routed    down     down              N/A         off
Ethernet104       9,10,11,12     100G   9100     rs  Ethernet27/1  routed    down     down              N/A         off
Ethernet108      13,14,15,16     100G   9100     rs  Ethernet28/1  routed    down     down              N/A         off
Ethernet112      17,18,19,20     100G   9100     rs  Ethernet29/1  routed    down     down              N/A         off
Ethernet116      21,22,23,24     100G   9100     rs  Ethernet30/1  routed    down     down              N/A         off
Ethernet120      25,26,27,28     100G   9100     rs  Ethernet31/1  routed    down     down              N/A         off
Ethernet124      29,30,31,32     100G   9100     rs  Ethernet32/1   trunk      up       up  QSFP28 or later         off
```

**Comment by lolyu** [comment]
depends on https://github.com/Azure/sonic-buildimage/pull/9173

**Comment by yxieca** [comment]
I don't think we should make a copy of flex config here. We should use the flex config in image. if it is not available, then fail the operation.

For the time being, or if the back port was rejected, you can use master image for the experiment.

**Comment by lolyu** [comment]
> I don't think we should make a copy of flex config here. We should use the flex config in image. if it is not available, then fail the operation.
> 
> For the time being, or if the back port was rejected, you can use master image for the experiment.

@yxieca, updated, and tested over 20201231 image after manually copy the flex config into the platform directory.

**Review by yxieca — APPROVED** [review]

**Pull request merged**
