### PR TITLE
[dualtor][non-functional] add test template for `active-active` cable type 

### PR DESCRIPTION
**Pull request by zjswhhh**
### Description of PR

Summary:
Fixes # (issue)

Submitting this PR to re-add test template for `active-active` cable type. The change (#5424) was reverted earlier due to regression.  

sign-off: Jing Zhang zhangjing@microsoft.com 

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012

#### What is the motivation for this PR?
Re-add the roadmap for supporting `active-active` dualtor_io testcases.

#### How did you do it?
1. Pick the commit from the original PR. 
2. Import `cable_type` fixture where the modified fixtures are requested. 
3. Update `data_plane_utils.py` to re-use `DualtorIO` object. 

#### How did you verify/test it?
Tested test cases below, all passed: 
```
dualtor_io/test_normal_op.py::test_normal_op_upstream[active-standby] 
dualtor_io/test_normal_op.py::test_normal_op_downstream_active[active-standby] 
dualtor_io/test_normal_op.py::test_normal_op_downstream_standby[active-standby] 

dualtor_io/test_link_failure.py::test_active_link_down_downstream_active[active-standby] 
dualtor_io/test_link_failure.py::test_active_link_down_downstream_standby[active-standby] 
dualtor_io/test_link_failure.py::test_standby_link_down_upstream[active-standby] 
dualtor_io/test_link_failure.py::test_standby_link_down_downstream_active[active-standby] 
dualtor_io/test_link_failure.py::test_standby_link_down_downstream_standby[active-standby] 
dualtor_io/test_link_failure.py::test_active_tor_downlink_down_upstream[active-standby] 
dualtor_io/test_link_failure.py::test_active_tor_downlink_down_downstream_active[active-standby] 
dualtor_io/test_link_failure.py::test_active_tor_downlink_down_downstream_standby[active-standby] 
dualtor_io/test_link_failure.py::test_standby_tor_downlink_down_upstream[active-standby] 
dualtor_io/test_link_failure.py::test_standby_tor_downlink_down_downstream_active[active-standby] 
dualtor_io/test_link_failure.py::test_standby_tor_downlink_down_downstream_standby[active-standby] 
```

### CODE REVIEW

**Review by lolyu — DISMISSED** [review]

**Review by yxieca — APPROVED** [review]

**Comment by yxieca** [comment]
@zjswhhh did you address the LGTM issues?

**Review by lolyu — APPROVED** [review]
LGTM

**Comment by yxieca** [comment]
@zjswhhh are you able to solve the 14 unused imports identified by LGTM?

**Comment by zjswhhh** [comment]
> @zjswhhh are you able to solve the 14 unused imports identified by LGTM?

Hi Ying, the alerting for unused import is false positive. Let me check if I can find a work-around.

**Pull request merged**
