### PR TITLE
Run tests only on asics that are detected in supervisor card

### PR DESCRIPTION
**Pull request by SuvarnaMeenakshi**
### Description of PR

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911
- [ ] 202012

#### What is the motivation for this PR?
The tests uses asic_index related fixtures, run on MAX number of asics in a supervisor card and some of the tests might expect dockers of all asic namespaces to be present. supervisor card might not have all fabric cards inserted, so not all dockers will be running causing test cases to fail if run on the asics that are not detected in supervisor. This PR is to fix this by adding a inventory field specifying the list of detected asic indices.
#### How did you do it?
1. Add detected_asics field in inventory file
2. Modify conftest to use detected asics field to generate enum_asic_index fixture.
3. Modify facts of sonic host to include detected asics list.
4. Modify generation of backend_asics list for multi_asic host to use detected_asics list if it is a supervisor.

### CODE REVIEW

**Comment by sanmalho-git** [comment]
FYI - We have opened PR https://github.com/Azure/sonic-mgmt/pull/5828 for this as well. Will close that one.

**Comment by SuvarnaMeenakshi** [comment]
> FYI - We have opened PR #5828 for this as well. Will close that one.

Thank you, I will close this, you can keep that, seems like someone already reviewed it as well.

**Comment by sanmalho-git** [comment]
@SuvarnaMeenakshi  - Do you want us to include the changes to multi_asic.py and sonic.py in PR# 5828?

**Comment by SuvarnaMeenakshi** [comment]
> @SuvarnaMeenakshi - Do you want us to include the changes to multi_asic.py and sonic.py in PR# 5828?

PR # 5828 says that it is tested with enum_backend_asic index, but enum_backend_asic_index uses the backend asics from multi_asic.py. If you can confirm that PR 5828 is good for all scenarios, it should be fine.

**Comment by sanmalho-git** [comment]
For T2 chassis, the 'sub_role' is 'Fabric' for fabric_asics. Thus, the backend_asics in multi_asic.py for supervisor card in a T2 chassis is an empty list. So, our test for enum_backend_asic_index did not get parameterized (not run).  

Could you elaborate more on how enum_backend_asic_index should be handled with the 'asics_present' variable in the inventory file.

**Comment by SuvarnaMeenakshi** [comment]
> For T2 chassis, the 'sub_role' is 'Fabric' for fabric_asics. Thus, the backend_asics in multi_asic.py for supervisor card in a T2 chassis is an empty list. So, our test for enum_backend_asic_index did not get parameterized (not run).
> 
> Could you elaborate more on how enum_backend_asic_index should be handled with the 'asics_present' variable in the inventory file.

In this diff, we are updating the backend_asics of supervisor node based on inventory data to of "detected_asics" or "asics_present". 
If I have to test something on backend_asics on supervisor node on packet chassis, then I expect the test to run on all the asics that are present. 
Shall I go ahead and use this PR and you can use PR 5828 to fix  "a_dut" alone?

**Comment by sanmalho-git** [comment]
Question is whether we want to treat the fabric asics in a non packet chassis as backend_asics?

**Comment by SuvarnaMeenakshi** [comment]
> Question is whether we want to treat the fabric asics in a non packet chassis as backend_asics?

no, we do not want to treat fabric asics in a non packet chassis as backend_asics.

**Comment by sanmalho-git** [comment]
OK - assuming that for packet chassis, we do want to include them as backend asics. Please confirm. If so, we will include your changes to treat 'asics_present' as backend_asics on supervisor node for a packet chassis.

**Comment by sanmalho-git** [comment]
Have incorporated your changed into latest commit on PR#5828 - please check

**Pull request closed without merging**
