### PR TITLE
Skip SFP tests on Arista 7050qx-32s

### PR DESCRIPTION
**Pull request by prgeor**
Signed-off-by: Prince George <prgeor@microsoft.com>

### Description of PR
Skip SFP test on Arista 7050qx-32s for 202012 release

In 7050qx platform the SFP ports 1 to 4 when operational,  QSFP port 5 is not available for use. The SFP test currently don't have any means to know ports that are operational mutually exclusive in a platform. To fix this later on platform.json will be enhanced to capture this information. 

Also, ensure sfp_port_indices[] list is a unique set of indices (i.e no duplicate indices) for breakout case as well .

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911

#### What is the motivation for this PR?
1. SFP test failure on Arista due to 7050qx-32s incorrect SFP index being tested
2. SFP test failure when breakout is enabled

#### How did you verify/test it?
Ran test_sfp.py successfully on 7050qx  and str2-7050cx3-acs-11(has breakout enabled)

#### Any platform specific information?

SFP test won't run on Arista 7050qx-32s for 202012 release

### CODE REVIEW

**Review by sujinmkang — APPROVED** [review]

**Comment by yxieca** [comment]
@prgeor I thought either hwsku.json or skip SFP test on disabled port should make test pass? Why do we still need to slip?

**Comment by prgeor** [comment]
> @prgeor I thought either hwsku.json or skip SFP test on disabled port should make test pass? Why do we still need to slip?

@yxieca SFP test reads SFP names for each physical port from platform.json. The test cannot figure out to skip port name qsfp5 because SFP 1 to 4 is enabled. We didn't want to have Arista specific fix in common test code to skip qsfp5 instead it was decided  with Guohan to enhance platform.json to 

> @prgeor I thought either hwsku.json or skip SFP test on disabled port should make test pass? Why do we still need to slip?



> @prgeor I thought either hwsku.json or skip SFP test on disabled port should make test pass? Why do we still need to slip?

On 7050qx the port indices can be 5 to 36 or 1 to 36 (5 skipped). The SFP test fact check here [https://github.com/Azure/sonic-mgmt/blob/master/tests/platform_tests/api/test_sfp.py#L144](https://github.com/Azure/sonic-mgmt/blob/master/tests/platform_tests/api/test_sfp.py#L144) doesn't have the knowledge based upon current platform.json to know when to skip a port (this is different from skipping RJ45 ports in hwsku.json and port not part of connection graph). It was discussed with Guohan to improve existing platform.json where we capture  mutually exclusive ports.

**Comment by wangxin** [comment]
@prgeor Can you address the LGTM alert and resolve the merge conflicts?

**Comment by prgeor** [comment]
Issue fixed in PR [https://github.com/Azure/sonic-mgmt/pull/4464](https://github.com/Azure/sonic-mgmt/pull/4464)

**Pull request closed without merging**
