### PR TITLE
Converted a few T1 topology testcases for T2 topology to run on multi-dut, and new dut selection mechanism

### PR DESCRIPTION
**Pull request by oxygen980**
### Description of PR

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

#### What is the motivation for this PR?
Need the capability to run T1 applicable tests against a T2 chassis
#### How did you do it?

A sonic T2 chassis is a chassis with multiple linecards and a supervisor card. This chassis is represented as a testbed with multiple DUTs (for each linecard and a supervisor card). Thus, we used the multi-dut approach to modify tests to execute against a T2 chassis.

There was also capability to run tests against a single randomly selected DUT from the multi-duts in a testbed using 'rand_one_dut_hostname' fixture. This assumes that all DUTs in the testbed have the same hwsku.  However, in a T2 chassis, we could have linecards with different hwsku's. So, we need to run the tests against a single randomly selected DUT per hwsku for a T2 chassis. 

We used the 'enum_rand_one_per_hwsku_frontend_hostname' dut selection fixture defined in pytest_generate_tests. For consistency of the random selected DUT list across a module, we made 'enum_rand_one_per_hwsku_frontend_hostname' fixture return the same set of random duts per hwsku for a pytest module.

Following test cases were modified to run against one random frontend linecard per hwsku in a T2 chassis
- test_interfaces.py
- test_nbr_health.py
- iface_namingmode/test_iface_namingmode.py
- arp/conftest.py
- arp/test_arpall.py
- arp/test_neighbor_mac_noptf.py
- route/test_default_route.py
- route/test_route_perf.py
- monit/test_monit_status.py
- portstat/test_portstat.py
- read_mac/test_read_mac_metadata.py
- syslog/test_syslog.py

The changes were:
- use enum_dut_frontend_hostname instead of enum_dut_hostname to execute against all frontend linecard
- use enum_rand_one_per_hwsku_frontend_hostname instead of rand_one_dut_hostname to execute against one random frontend linecard per hwsku.
- Included 't2' topology in topology checks
- Incorporated changes required to support 'Inband' interfaces on the linecards.

#### How did you verify/test it?
Ran modified tests against a T2 chassis with topology defined in ansible/vars/topo-t2.yml.

### CODE REVIEW

**Comment by sanmalho-git** [comment]
retest vsimage please

**Comment by shubav** [comment]
@yxieca @wangxin could you please review these changes? This includes the new dut selection mechanism too. If this looks fine, we will push another PR which converts a couple more tests. Thanks.

**Comment by oxygen980** [comment]
retest vsimage please

**Comment by oxygen980** [comment]
retest vsimage please

**Review by yxieca — APPROVED** [review]

**Pull request merged**
