### PR TITLE
Add previous GCU tests to kvm daily test

### PR DESCRIPTION
**Pull request by wen587**
### Description of PR

Summary:
Add previous Generic Configer Updater tests into kvm test suite
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 201911

#### What is the motivation for this PR?
Move GCU test into kvm daily test
#### How did you do it?
Add GCU test case into kvmtest.sh
#### How did you verify/test it?
Run test of sonic-mgmt/tests/generic_config_updater/*.py on KVM

### CODE REVIEW

**Comment by wen587** [comment]
https://github.com/Azure/sonic-utilities/pull/2006
Loopback test can only pass after above PR merge.

**Review by qiluo-msft — DISMISSED** [review]

**Review by qiluo-msft — APPROVED** [review]

**Pull request merged**
