### PR TITLE
[drop_packets]: Skip cisco-8000 unsupported test cases

### PR DESCRIPTION
**Pull request by vperumal**
### Description of PR

The following packets will not be dropped by Cisco-8000 platforms:

- SIP/DIP link local [test_src_ip_link_local]
- SIP class E  [test_src_ip_is_class_e]
- SIP/DIP with 0.0.0.0 [test_ip_is_zero_addr]
 

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911

#### What is the motivation for this PR?
SIP/DIP link local, SIP class E and SIP/DIP with 0.0.0.0 packets will not be dropped by Cisco-8000 platforms

#### How did you do it?
For these test cases, require the ASIC type be non cisco-8000.

#### How did you verify/test it?
Ran on a cisco-8000 device and verified tests are skipped instead of failing

### CODE REVIEW

**Review by wangxin — DISMISSED** [review]

**Comment by sachinv-msft** [comment]
@wangxin please merge this PR

**Comment by sachinv-msft** [comment]
@wangxin could you please merge this PR?

**Comment by wangxin** [comment]
@vperumal Can you resolve the merge conflicts?

**Comment by vperumal** [comment]
@wangxin, I resolved the conflict. Kindly take a look and let me know if I need to make any other changes

**Comment by wangxin** [comment]
@vperumal There are merge conflicts again. Can you resolve the conflicts?

**Comment by vperumal** [comment]
@wangxin , Resolved the conflicts

**Comment by sachinv-msft** [comment]
@wangxin could you please merge the PR?

**Comment by sachinv-msft** [comment]
@wangxin please review the PR!

**Review by wangxin — APPROVED** [review]

**Pull request merged**
