### PR TITLE
[ memory_checker ] Removed hardcoded proxy from memory checker test

### PR DESCRIPTION
**Pull request by SavchukRomanLv**
Signed-off-by: Roman Savchuk <romanx.savchuk@intel.com>

### Description of PR

Summary:
Fixes # (issue)

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

### Back port request
- [ ] 201911

#### What is the motivation for this PR?
TC can not install stress tool due to hardcoded proxy settings
#### How did you do it?
Added ability to read proxy settings from creds
#### How did you verify/test it?
Run TC, stress tool have been successfully installed and deleted after test run

### CODE REVIEW

**Comment by yxieca** [comment]
@SavchukRomanLv please solve the merge conflict.

**Comment by yxieca** [comment]
@yozhao101 please look into this change. I think the change is good. Please make sure the proxy is configured in creds if our nightly tests requires that.

**Comment by SavchukRomanLv** [comment]
@yxieca resolved

**Review by yxieca — APPROVED** [review]

**Comment by yxieca** [comment]
> @yozhao101 please look into this change. I think the change is good. Please make sure the proxy is configured in creds if our nightly tests requires that.

Looks like we have other tests already getting proxy settings via the same method.

**Pull request merged**
